### ISSUE TITLE
Oracle NoSQL compatibility 

### ISSUE THREAD

**Issue by Rihcus** [vrtmrz/obsidian-livesync#103]
Hi sorry to bother do you think obsidian-livesync would work with Oracle NoSQL?
https://www.oracle.com/database/nosql/

Its limits are a bit more generous compared to ibm
https://www.oracle.com/cloud/free/#always-free

Also out of curiosity how many reads/writes does live sync normally use? (

**Comment by vrtmrz** [comment]
Sorry for being late!
Oracle NoSQL is not compatible with CouchDB, so Self-hosted LiveSync can not use it.
