### ISSUE TITLE
Use SQLite instead of couchdb ?

### ISSUE THREAD

**Issue by Drezzler** [vrtmrz/obsidian-livesync#104]
Hello @vrtmrz , thank you so much for all the time and effort you have put into this plug-in. 

Is their any specific reason you chose couchdb for this plug-in instead of a more versatile SQLite ?

**Comment by vrtmrz** [comment]
Thank you for asking me!
CouchDB is a database that is very easy to replicate and can be communicated via HTTP from a browser.
And, PouchDB that the database used in LiveSync is a compatible database with this. And it runs on the browser. 
So we can use CouchDB as a server without any modifications. 

If we want to use SQLite on the server, we may have to write the server software. It is far less reliable than OSS which is already well-used. 
Of course, Also I am used to PouchDB. These are the reasons I chose them.

I hope this answer your question.

**Comment by Drezzler** [comment]
Thank you for explaining. 

I was just reading a book on django python framework the other day, and it seems couchdb is actually meant/tuned for file storage.
