### ISSUE TITLE
cannot connect to your test server

### ISSUE THREAD

**Issue by ycbrd** [vrtmrz/obsidian-livesync#105]
wondering what happened ...
![image](https://user-images.githubusercontent.com/105804326/187013706-d471f069-9e90-498f-af9c-335634c94a72.png)

**Comment by ycbrd** [comment]
Please，can I use my NAS (Synology) as the server? CouchDB？

**Comment by vrtmrz** [comment]
Wow, Sorry for your inconvenience. 
I rebooted the server a few days ago, perhaps I forgot to boot services. 
I will check it later. 

> Please，can I use my NAS (Synology) as the server? CouchDB？

If your Synology supports Docker, you can use it. 
https://github.com/vrtmrz/obsidian-livesync/issues/79

**Comment by ycbrd** [comment]
Thank you 😋
