### ISSUE TITLE
Fetch Fails with CORS

### ISSUE THREAD

**Issue by Vyeche** [vrtmrz/obsidian-livesync#111]
Fetch Fails, re-fetching seems to correct it.
CORS is on in IBM Cloud, not sure if it's something else?

`Access to fetch at '...bluemix.cloudantnosqldb.appdomain.cloud/folder/_all_docs?include_docs=true' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

![image](https://user-images.githubusercontent.com/972377/189154759-741e7219-5e6e-4d80-9dce-2f60c10f6f81.png)

**Comment by vrtmrz** [comment]
We have to enable CORS setting in Cloudant as like [This doc](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_cloudant.md#database-setup).

Coincidentally, we have footage. 
I hope that it helps you.
https://user-images.githubusercontent.com/45774780/189270621-72b68975-8176-411b-8bdd-81fbe7b503e7.mp4

**Comment by Vyeche** [comment]
> We have to enable CORS setting in Cloudant as like [This doc](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_cloudant.md#database-setup).
> 
> Coincidentally, we have footage. 
> I hope that it helps you.
> https://user-images.githubusercontent.com/45774780/189270621-72b68975-8176-411b-8bdd-81fbe7b503e7.mp4

I mean it's enabled, but an error is coming anyway. I feel it might be too many files being synced and not having a delay?

**Comment by vrtmrz** [comment]
Thank you for checking it again! Then, could you also check what will be shown if you access the address by the browser which error occurred in Obsidian? (Please check it in DevTools too)

My vault has around 500 files but it can be synchronised. Possibly there are a lot of change sets. Could you please try completely rebuilding the local and the remote databases once by using the `Rebuild everything` button on the `🛰️  Remote database configuration` after your device is surely connectable?

**Comment by Vyeche** [comment]
Hi,

The screenshots I shared earlier with cors were with a rebuild from remote.

I did a lock, then pushed to remote to rebuild with local files when I move
to another device with fetch on a clean vault or filled vault. That's when
I noticed issues.

Kind regards,
Vye

**Comment by vrtmrz** [comment]
Oh, still the same error is happening?
If you don't try rebuilding databases once connecting settings are configured, please do it again.  
And restore other devices as following instructions:
1. Copy your configuration on the original device, by `Copy setup URI` in the command palette. It asks you the passphrase. Please type anything you like.
2. In the new device, install only Self-hosted LiveSync. and setup by `Open setup URI` from the command palette. You asked for the passphrase so type what you typed.
3. Answer like this
- Yes to `Importing LiveSync's conf, OK?`
- No to `Keep local DB?` 
- Yes to `Keep remote DB?`
- No to `Rebuild the database?`
- Yes to `Replicate once?`
 
This procedure would bring bach other devices synchronise to normal.

**Comment by vrtmrz** [comment]
Hi! Do you still have the same error?
I have created a new feature to simplify the configuration of LiveSync. [Quick setup](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/quick_setup.md) is.
If you are still in trouble, please try it once and rebuild the database again.

**Comment by Vyeche** [comment]
Hey there,

I'm not seeing the cors issue because I stopped using remote sync with
dropbox. However, I do notice when I move files around, it keeps folders
and and bugs out sometimes.

Kind regards,
Vye

**Comment by hilsonp** [comment]
Hello @vrtmrz,

I have 2 Win10 laptops and one iPhone running your plugin and syncing one vault through a self-hosted couchdb.
Except the issue https://github.com/vrtmrz/obsidian-livesync/issues/161 files are syncing correctly (as far as I could see).

I first setup the couchdb, 
then I setup Laptop1 and synced it to the db
then I setup Laptop2 and synced to the db
then I setup the iPhone and synced to the db.

The cors error is seen on Laptop2. I don't know if I can check this on the iPhone anyway ;-)

What is the safest way to restart from scratch ? How to delete everything (Laptop2, iPhone, db) except Laptop1, then redo the setup ?

This is unclear for me.

Then, once I resynced everything, I would see if the cors error is still there on Laptop2.

**Comment by hilsonp** [comment]
You can forget my question. I could clear up everything and my cors issue is followed up by #161
