### ISSUE TITLE
Error while syncing

### ISSUE THREAD

**Issue by Robertschv** [vrtmrz/obsidian-livesync#115]
I tried to sync my vault today with another computer, but is not retrieving all the files.

The only way I could make it sync was to disable the "Read chunks online." option in Sync settings.

Does anyone have the same error?

EDIT:  I am using IBM Cloudant

**Comment by vrtmrz** [comment]
I'm really sorry, I missed this issue!

It should have been fixed at 0.15.9. Could you please try the latest version?
