### ISSUE TITLE
“Apply Encryption settings” destroys my remote DB when applied

### ISSUE THREAD

**Issue by Robertschv** [vrtmrz/obsidian-livesync#116]
When I click on the “Apply Encryption settings” button on a new device (deviceA) where I want to sync my Vault, it destroys the remote DB. 

The problem? I need to go to my other device (deviceB) where I already had the encryption settings applied and where I did sync the local DB with Remote DB before, to “Overwrite the Remote DB” again so the new device (deviceA) where I applied the settings can retrieve the files from the remote DB.

And if I don't click on that button, the passphrase is not applied, so the files that are received in the new device(deviceA) are (obviously) encrypted.

Why does it need to destroy the remote DB? There is already a DB in there. The button could just retrieve the files from remote DB instead, no?

It kind of scare me that I would lose my files, because the deviceB would sync the empty DB that created the deviceA after applied the settings.

**Comment by vrtmrz** [comment]
Sorry for being late! 
Now this pane lacks the feature as you said. It designed to  avoid leaking the data which encrypted by previous passphrases unexpectedly.
 

> It kind of scare me that I would lose my files, because the deviceB would sync the empty DB that created the deviceA after applied the settings.

Absolutely as you said. We have to confirm that it is surely expected.
Recommended way to configure the second device is `Open setup uri`. But it could be handy for minor configuration changes.

It will be fixed! Thank you for your good advice!

**Comment by Robertschv** [comment]
Thank you for the answer, I tried with ``Open setup uri`` and it works perfectly.

BTW, sorry for being late, I didn't have much time this month.
