### ISSUE TITLE
Proxy Authentication Required

### ISSUE THREAD

**Issue by cdrfun** [vrtmrz/obsidian-livesync#118]
Hey there,
Obsidian Livesync seems to ignore configured proxy authentication. Installing Plugins in Obsidian is no problem, so I think it's a plugin specific problem. When I'm at a location without a proxy, everything syncs as expected.

**Comment by vrtmrz** [comment]
Thank you for sharing this! I didn't notice it.
I will try reproducing it with some proxy.

**Comment by vrtmrz** [comment]
@cdrfun sorry, I could not set up the server to reproduce this yet.
Do you if I ask you to capture the log shown in the devtool?
(I think it responds as 407)

Please conceal the authorization information(it should be authorization or proxy-authorization)

**Comment by cdrfun** [comment]
Sure. 
The log says the preflight for CORS was not successful:
![grafik](https://user-images.githubusercontent.com/146877/191678251-6e816002-b1f7-4c86-b792-167f5832a400.png)

But looking at the Network log
![grafik](https://user-images.githubusercontent.com/146877/191677963-9374c983-a74c-4dcb-94e6-ab885681e242.png)

It seems like the preflight request was blocked by the proxy:
![grafik](https://user-images.githubusercontent.com/146877/191678044-de88e1db-13be-4174-beaa-7044b358432f.png)

**Comment by vrtmrz** [comment]
Thank you for the detailed information!

It reproduced! But unfortunately, it seems to be an obsidian's specification.
Some other plugin acts like this. And several workarounds, which I tried were not effective.

I will post on this issue in the official forum.

**Comment by cdrfun** [comment]
Today I had some time to tinker around with this problem and found a solution that works for me. Maybe it's helpful for someone else:

I used [px](https://github.com/genotrance/px) to create my own local proxy server which handles the authentication to the upstream proxy and Obsidian can connect to.

After installing px, you have to configure it using the documentation I'm posting my config as an example:
`px --username=<USERNAME> --auth=BASIC --proxy=<server:port>`

This will start a proxy which can only be accessed by local applications. Next we have to tell Obsidian to use this proxy. This can be done by passing it through a parameter [documentation](https://www.electronjs.org/de/docs/latest/api/command-line-switches#--proxy-serveraddressport):
`.\Obsidian.exe --proxy-server=localhost:3128`

I hope this helps anyone. I'll write a little script to start/stop the proxy with Obsidian. And a big shoutout to the creators of [px](https://github.com/genotrance/px)!

**Comment by vrtmrz** [comment]
@cdrfun Thank you for looking into this! I think it's a perfect workaround. And it works for other plug-ins.
Sorry for having been late and late to report at the forum!
