### ISSUE TITLE
Could this plugin support the webdav and S3 service ?

### ISSUE THREAD

**Issue by sky90038528** [vrtmrz/obsidian-livesync#120]
Could this plugin support the webdav and S3 service like tencent cloud & ali cloud ?

tencent cloud :
cloud.tencent.com
ali cloud: 
www.aliyun.com

**Comment by vrtmrz** [comment]
Thank you for asking me! But I'm afraid I should give you this reply.
This plugin only supports the database that has compatibility with CouchDB.
