### ISSUE TITLE
Not all files synced to IBM Cloud

### ISSUE THREAD

**Issue by simzdk** [vrtmrz/obsidian-livesync#126]
Hi
Im trying to setup a DB, but im not sure if im hit with a API limit to IBM. 
When I setup the configuration, I can see it sends 435 documents(?) to IBM
![202210 - Obsidian - 2022-10-10 at 11 12 11](https://user-images.githubusercontent.com/155539/194833680-b1f2b5b8-0609-4a12-bc68-2a5aa0d2a9d6.png)

But when I look in the DB directly, it seems something is missing: 
My Structure: 
![202210 - Obsidian - 2022-10-10 at 11 15 33](https://user-images.githubusercontent.com/155539/194833862-3c0645b4-6d06-4ea9-8f3f-b3101eccf45a.png)

at IBM (which I guess it sorted):
![202210 - Safari - 2022-10-10 at 11 16 08](https://user-images.githubusercontent.com/155539/194833995-176089d6-f409-4044-ba08-ed7e6e886475.png)

Sometimes when I try, I get to the 40 folder. But never the entire thing. 
If I look in the log, the 10 folder is between:
![202210 - Obsidian - 2022-10-10 at 11 17 54](https://user-images.githubusercontent.com/155539/194834285-9d6929f2-4d5b-4de2-be8c-601258d8f9ee.png)

**Comment by simzdk** [comment]
Anyway I can force an total update from the source, ensure everything is present at IBM, and the purge and replicate that to all other devices?

**Comment by vrtmrz** [comment]
Thank you for opening up this issue!
LiveSync only synchronises files, not folders. If the folder is empty, will be ignored. 
Do all folders contains files?

> Force total update

If we want to make sure every file exists, we can use `Verify all files` on the `Hatch` pane on the setting dialog.
Discard everything on the remote database and make it again can be done by `Rebuild everything` on the `Remote database configuration` pane.
If the remote database has been rebuilt, all other devices should detect the rebuilding. Then, we have to `Fetch rebuilt DB` in the `Local database configuration` pane.

**Comment by simzdk** [comment]
Yes, those folder contain files. I was thinking something in the naming cause those folders and files not to be copied, as I cannot find them if I look directly in the IBM CouchDB. 
![image](https://user-images.githubusercontent.com/155539/195304422-c06cfbea-5b82-4be6-8d12-80cf7411c3f0.png)

**Comment by vrtmrz** [comment]
Sorry for my assumption. And thank you for trying to verify. 

Indeed, emojis can be suspicious. I will investigate it. If it's not too much trouble, could you give me an example of which files are being ignored?

**Comment by simzdk** [comment]
> If it's not too much trouble, could you give me an example of which files are being ignored?

Filenames or entire content of the files?

**Comment by vrtmrz** [comment]
> Filenames or entire content of the files?

Path of the file as the text, please. We can copy it from the command palette.

**Comment by simzdk** [comment]
> > Filenames or entire content of the files?
> 
> Path of the file as the text, please. We can copy it from the command palette.

https://pastebin.com/wG6hS1yq

**Comment by simzdk** [comment]
Looking more into this. When I click "Check database configuration", I get this in Dev Tools - Console: 
![202210 - Obsidian - 2022-10-12 at 17 36 49](https://user-images.githubusercontent.com/155539/195386725-a6868ea3-dbb3-48d5-955f-2fd71374510c.png)

Verify and repair all files:
https://share.cleanshot.com/PlZ5uW

**Comment by vrtmrz** [comment]
Sorry for missing the issue for a long time. It must be fixed on previous updates.
Please feel free to re-open the Issue. Thank you so much.
