### ISSUE TITLE
Could not retrieve chunks Error, vault will not Fetch data from working database.

### ISSUE THREAD

**Issue by Cityjohn** [vrtmrz/obsidian-livesync#129]
I'm not sure what is giong on. I tried installing a vault on my laptop using the exact same settings as on my phone and computer but after an hour of trying I still can't get it to sync. It sync's perfectly fine on the other devices.

I keep getting two distinct not so discript errors among others.

Something went wrong & Could not retrieve chunks,.

![screen](https://user-images.githubusercontent.com/34970833/194969246-00b806a1-b356-4629-8d77-e1ce266ddb0a.jpg)

![screen2 jog](https://user-images.githubusercontent.com/34970833/194969361-1a0d28f3-71b8-49d8-b86d-613d810b66b1.PNG)

Does anyone have any suggestion as to how to remedy this? I've already tried several times to start a new vault, won't work.

**Comment by vrtmrz** [comment]
Thank you for opening the issue and the detailed log.
Is the chunk causing the error always the same ids (following the log, `h:+-1589cb2d0`)?
If so, we have to make it again by clicking `Verify and repair` on the `Hatch` pane in the setting dialog in the device which has the files.
Otherwise, we have several possibilities. Please check the network pane on DevTools and look for red requests.

**Comment by Cityjohn** [comment]
Hmm, it looks like these are all different batches

![image](https://user-images.githubusercontent.com/34970833/195464361-f24a2d2e-4680-4b38-8f89-50b15dbd9d6e.png)

To check if it was something to do with networking as I have a mesh network I opened several other vaults running through the same host, albeit on seperate domains, but all on the same server. They work fine and live-sync update is almost instant.

![image](https://user-images.githubusercontent.com/34970833/195464976-a9851fea-5152-4414-a5ef-3b5f78e977c9.png)

I think live-sync is updating the notes I'm working on but does not fetch the rest of the vault. I tried verifying all files and it just completed the proces without errors saying it was done at the end.

Then I Fetched DB again and it gave me the following error again:

![image](https://user-images.githubusercontent.com/34970833/195466040-0fa13d4f-d350-4e45-8b42-a15221ac3546.png)

**Comment by Cityjohn** [comment]
Hmm I've tried to connect to this vault with 2 other laptops and I get the same errors and the database will only partially load, when I say partially I mean only like 20% on initialization.

**Comment by thehappymiller** [comment]
In the same vault as above I get the following errors.

![image](https://user-images.githubusercontent.com/115862472/196031705-272ef821-0b2a-4198-97f3-4f36ced68d33.png)

**Comment by thehappymiller** [comment]
As time goes on more notes are syncing but definitely not all of them

**Comment by Cityjohn** [comment]
We resolved the problem by shutting down and restarting the couchDB server in Docker.

**Comment by vrtmrz** [comment]
Thank you for the information!

I am wondering why we needed to reboot CouchDB. But in fact, sometimes a restart has solved things.
Perhaps we need a FAQ.
