### ISSUE TITLE
entry not found, maybe deleted (it is normal behavior)

### ISSUE THREAD

**Issue by Vyeche** [vrtmrz/obsidian-livesync#136]
Hi, 

I'm seeing a ton of these and I don't know how to correct quickly. 
Nothing is shown in Corrupted or missing data. How do I address this?
Please advise.

![image](https://user-images.githubusercontent.com/972377/197806841-3080273f-b82f-4cd7-9857-bf272cfe1c50.png)
![image](https://user-images.githubusercontent.com/972377/197807216-cfca9c72-5dd9-4296-8d49-103d6c435235.png)

**Comment by vrtmrz** [comment]
Sorry for this, The expression was too much as it came to mind. My laziness.

This means 
> We keep the deleted document for history and diff, but it could not be extracted without explicit parameters.  So it shall be failed to extract to the storage. Then it acts as same as the case that the entry was found and suddenly deleted and had been not found while in the boot sequence. So it is expected and normal behaviour.

However, it had been a so rude message, I fixed this at v0.16.5. (Just retrieving with the parameter and judging correctly)
Could you please try this version?

**Comment by Vyeche** [comment]
Okay, what should I do when I see the adjusted message? Is this the delete meta flag I need to set?

**Comment by vrtmrz** [comment]
This message can be ignored. Just history has been detected.
(But I have begun to think this message should be shown as a verbose one...)
History of deleted metadata can be removed by enabling `Delete metadata of deleted files` (immediately when we deleted the files) or `Delete old metadata of deleted files on start-up` (after configured days passed).

**Comment by Vyeche** [comment]
Yeah, that is a good idea. Will it conflict with choosing a conflict file? I asked a similar question on another item. Sorry for the duplicate.

**Comment by vrtmrz** [comment]
will remove metadata on deletion. But if the conflict occurs again after synchronisation, it will be detected (CouchDB is amazing).
Even if we have dismissed the message at this time, we can open the conflict-resolving dialogue by `Pick a file...` later.

However, If we left the conflict of deleted files and it has been cleaned up at start-up. it might be completely erased.
