### ISSUE TITLE
Can it be simpler, such as direct synchronization onedive, just log in to your account, or log in to Tencent Cloud's tutorial

### ISSUE THREAD

**Issue by syec0607** [vrtmrz/obsidian-livesync#14]
Can it be simpler, such as direct synchronization onedive, just log in to your account, or log in to Tencent Cloud's tutorial

**Comment by vrtmrz** [comment]
I think It's not LiveSync, near-LiveSync, or complementary of LiveSync.

For your information:
I tried to make a plugin that as you said. As the complementary of Official "Sync" and Self-hosted LiveSync. Cloud Backup.
But there are a few limitations, I realized it's nonrealistic or may not be simple so much.

OneDrive, GoogleDrive, or other any drive may not accept the connections from obsidian by CORS limitations. If you want to access these hosts, need a proxy server to modify the request. To be secured, require
users to host the server.

A self-hosted WebDAV server can use this without request-modifying-proxies. But still, self-hosting is required.

And, currently, mobile Obsidian has the limitations that it can't access the non-secure endpoint or self-signed endpoint. So self hosted server should be exposed globally. It's should not be done in so easy and optimistic attitudes.

Totally, It is not simple.

I'm really sorry for I couldn't realize your idea.

**Comment by syec0607** [comment]
I followed your tutorial and succeeded, but I encountered difficulties in editing a lot of text. There was a problem with synchronization when my single document was 90,000 words. Is there a telegram group?

**Comment by syec0607** [comment]
minimum chunk size and LongLine threshold

If I don't want to use this feature how to turn it off.
Hope to add a closed function

**Comment by syec0607** [comment]
I hope that my document can be completely synchronized, and I don’t want to be divided into many parts, I hope to add a switch function, I can turn off this function
