### ISSUE TITLE
minimum chunk size and LongLine threshold

### ISSUE THREAD

**Issue by syec0607** [vrtmrz/obsidian-livesync#15]
minimum chunk size and LongLine threshold

If I don't want to use this feature how to turn it off.
Hope to add a closed function

**Comment by syec0607** [comment]
If I don't want to use this feature how to turn it off.
Hope to add a closed function

**Comment by syec0607** [comment]
I hope that my document can be completely synchronized, and I don’t want to be divided into many parts, I hope to add a switch function, I can turn off this function

**Comment by syec0607** [comment]
Replace every character to x except newline and "#" 

What's the meaning

**Comment by vrtmrz** [comment]
I'm sorrt for my bad english.
Please replace every letters except # into x
```
lolem ipsum 
# Topic 1
foo bar
```
to
```
xxxxx xxxxx 
# xxxxx x
xxx xxx
```

And I understood your idea.
But cloudant has the size limitations of each document (1MB)

What is the real problem?
CPU Load or transfer amount?

The earlier version of this plugin had been implemented as you said. And it worked but terribly poor performance.

If I can, I hope to improve it to work well with your notes too.
May I ask what is the matter, and what language are you writing? I will get the sample docs from Wikipedia.

**Comment by syec0607** [comment]
The word count of my single document is about 100,000 words. I use it to write articles. It is very troublesome to upload by splitting. Maybe it can increase the word count of split paragraphs.
By the way, your project is really good, I hope you can stick to it

**Comment by syec0607** [comment]
The word count of my single document is about 100,000 words. I use it to write articles. It is very troublesome to upload by splitting. Maybe it can increase the word count of split paragraphs.
By the way, your project is really good, I hope you can stick to it

**Comment by vrtmrz** [comment]
Wow... It's a really big note. How many letters? 

But what does it mean about "troublesome"? 
So many error happend?

If you really want to make chunk longer, try below once before adding feature.
1. close obsidian
2. Open `your vault/.obsidian/plugin/obsidian-livesync/data.json`
3. Set 100000 to minimumChunkSize and  longLineThreshold
4. Open Obsidian and test editing your note.

If performance will getting better, I change it.
(current setting limit is for the safery)

And may I ask again, what language do you writing? It's very important. Especially there's KANJI, CYRILLIC or something non-ascii chars.

**Comment by vrtmrz** [comment]
Close this issue once.
But feel free to open it again, if you need.
