### ISSUE TITLE
Renaming files after sync creates duplicate

### ISSUE THREAD

**Issue by Robertschv** [vrtmrz/obsidian-livesync#155]
- I create a file with the name test1 in DEVICE 1, I synchronize with IBM cloud.

- Then DEVICE 2 I synchronize with the cloud.

- Then I rename it to test2 on either device, and sync, the device that syncs with the cloud creates a copy of the file with the new name instead of renaming it.  

So, the device where I rename the file is fine, but on the second one I have a “duplicate” file, one with the old name and one with the new name.

However, this does not happen if the second device has not synced with the cloud yet, i.e, 

I create a test3 file, let it sync, then rename it and let it sync again, then sync the second device, and it gets the file with the new name.

**Comment by plutoghost** [comment]
#151

**Comment by vrtmrz** [comment]
Thank you for the information on the reproducing procedure! It has been very helpful for me! 

I will address this problem at #151, let me close this one, please.
