### ISSUE TITLE
unsymmetrical labeling of some button

### ISSUE THREAD

**Issue by JojoBr0** [vrtmrz/obsidian-livesync#156]
I've noticed an unsymmetrical labeling of some buttons in the settings menu and i'm not sure if this is intended:

![obsidian-livesync_2](https://user-images.githubusercontent.com/92635650/209362530-517c29f9-6f5f-48ba-b8f5-5c1b37b236f2.png)

This is caused by the following [style.css](https://github.com/vrtmrz/obsidian-livesync/blob/main/styles.css) settings:
[.sls-btn-left](https://github.com/vrtmrz/obsidian-livesync/blob/4dabadd5ea5269d90f53a14c8d0f30ef9c0999ce/styles.css#L88)
[.sls-btn-right](https://github.com/vrtmrz/obsidian-livesync/blob/4dabadd5ea5269d90f53a14c8d0f30ef9c0999ce/styles.css#L92)

**Comment by vrtmrz** [comment]
Thank you for pointing that out. 
It looks had been corrupted a bit long ago. It has been fixed at version 0.17.7. Could your please check this version?

**Comment by JojoBr0** [comment]
Thx for the fast response.

Yes, release 0.17.7 seems to fix the issue👍
