### ISSUE TITLE
How to delete other or old configs of plugins and their settings?

### ISSUE THREAD

**Issue by invisprints** [vrtmrz/obsidian-livesync#158]
Hi, I am a newbie to using the plugin. The plugin is amazing and works well across my devices. However, I find in plugins and their settings, there are some configs that I don't want to keep them. My question is how to delete them?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/15833553/209755141-a92d6b2c-16ba-4c6c-b38e-67c5cb2fc62f.png">
I want to delete configs named mobi and mobile-. And it seems there are multiple settings in one config, such as 0.2.1(Even) and - (Older). I want to delete these settings, can you help me?

**Comment by mhdali** [comment]
Hello, 

DANGER: Make sure you have backups!!

I'm also looking for the best solution to this problem. However, I managed to delete my old devices using CouchDB Fauxton (by accessing http://<couchdb_ip>/_utils), then selected **databases**, then selected the name of **my database**, then select "Run a query with **Mango**", then paste the following:
```
{
   "selector": {
      "_id": {
         "$regex": "ps:<NAME_OF_OLD_DEVICE>*"
      }
   }
}
``` 
**Make sure ALL the entries belong to your old device**, then select all entries and delete them.

**Comment by vrtmrz** [comment]
Thank you for asking me! However, unfortunately 
This plug-in missing the feature. 
@mhdali 's pointed operation is the best workaround

**Comment by invisprints** [comment]
Thx, but in the latest version, it shows "No plugins found" in all my devices. I don't know what happens

<img width="830" alt="截屏2023-01-23 下午8 37 18" src="https://user-images.githubusercontent.com/15833553/214041453-90869978-92f0-42ba-bdd9-a4e9e469bf61.png">

**Comment by invisprints** [comment]
@mhdali @vrtmrz Thanks, it works!
It seems the latest release [0.17.17](https://github.com/vrtmrz/obsidian-livesync/releases/tag/0.17.17), [0.17.16](https://github.com/vrtmrz/obsidian-livesync/releases/tag/0.17.16) fixed the "No plugins found"problem. Everything works well!

**Comment by vrtmrz** [comment]
Sorry for being late to reply! I am very relived to hear that!
