### ISSUE TITLE
iPhone "could not connect to: Remote URI is not valid" when setting up second device

### ISSUE THREAD

**Issue by NoughtKin** [vrtmrz/obsidian-livesync#159]
![image](https://user-images.githubusercontent.com/121004366/210862381-d5e6ddb9-fe5d-48d9-9c38-8129a9b1fc59.jpeg)

After I paste the setup URI in "Open setup URI", type in paraphrase, select "yes" - "set up for secondary ..." and it appeared like the picture above. I already used the "Discard the existing configuration and set up" just to make sure a fresh config, but it did not work. Anybody help me pls? Ty 😁

**Comment by NoughtKin** [comment]
>

**Comment by NoughtKin** [comment]
> This error will be reported only if a URI doesn't start with https:// or http://. Is your URI correct?

Oh sr first time using these and I pressing stuff all over the place haha. Yeah it did start with https://, but I already changed my backup method using Obsidian Git alr.

**Comment by vrtmrz** [comment]
Thank you for asking me! I wonder why it has not been copied correctly. 
I'll miss you a bit, but I'm glad to hear that you are not troubled now! 

Of course, I will help you if you are going to use this again! Feel free to re-open this! Cheers!
