### ISSUE TITLE
Stopped syncing hidden files

### ISSUE THREAD

**Issue by dliberalesso** [vrtmrz/obsidian-livesync#162]
I don't know why (because it was working yesterday) but it no longer syncs hidden files.

I even started from zero on another server instance, and it refuses to sync hidden files.

If my undertsanding of the logs is correct, the files are being sent to the local DB (PouchDB), i.e.:

`18/01/2023 16:41:28->STORAGE --> DB:.obsidian/snippets/rainbow-tags.css: (hidden) Done`.

But aren't showing inside the remote database (CouchDB).

BTW, I'm using fly.io.

**Comment by vrtmrz** [comment]
Thank you for asking me, and sorry. This is my fault, owning my barbarous fixes!
Fixed at v0.17.15, could you please try this version?

**Comment by dliberalesso** [comment]
It worked!
