### ISSUE TITLE
"Error while loading Self-hosted LiveSync" (Obsidian is not synced with the Self-hosted LiveSync plugin.)

### ISSUE THREAD

**Issue by dlphnkck** [vrtmrz/obsidian-livesync#166]
Hello, Nice to meet you. I have always found the LiveSync plugin very useful.
I'm not sure if this is the right place, but I have a question.

I have been unable to synchronize with Obsidian for a few days ago, and I would like to ask for your advice.

**Enviroment**
Client: 5 units
1. Windows 10
2. Linux
3. iPad
4. Android x2

- CouchDB : Fly.io
- Obsidian ver 1.1.9

Vault:
- 1,278 files
- size : 105 MB. e.g. Excalidraw Japanese font file 29 MB

- Self-hosted LiveSync plugin ver 0.17.17

**Sync Status Log**
> 2023/1/27 16:11:16->loading plugin
> 2023/1/27 16:11:16->Self-hosted LiveSync v0.17.17 0.17.17 
> 2023/1/27 16:11:16->Open Database...
....
> 2023/1/27 16:11:28->Could not retrieve chunks
> 2023/1/27 16:11:28->Error while loading Self-hosted LiveSync
> 2023/1/27 16:11:28->TypeError:Cannot read properties of undefined (reading 'status')

Stop here and do not proceed.
That is all. What seems to be the problem? Thank you in advance.

**Comment by vrtmrz** [comment]
@dlphnkck  
Thank you for reporting this! Very helpful!

I saw this message surely, but I thought it might be something like a timing problem, and had just rebuilt the database immediately. It is not good that pretending didn't see it. 

With your help, I found that we were letting errors getaway. 
Fixed at 0.17.18. Could you please try this version?

**Comment by dlphnkck** [comment]
Thank you for taking the time to respond.

I updated to version 0.17.18, but the lack of synchronization did not change. The "Sync Status" log is as follows.[1]

On my end, should I perform either option

1. "Rebuild everything (Rebuild local and remote database with local files.)" <- Remote Database configuration
2. "Fetch rebuilt DB (Restore or reconstruct local database from remote database)" <- Local Database configuration,

to rebuild the database?

Since backups are taken daily, I have had experience running the command 'Fetch rebuilt DB' on each terminal multiple times when the error message 'Fetch rebuilt DB' was displayed.

That is all. Best regards.

1. Sync Status Log
2023/1/28 16:48:33->loading plugin
2023/1/28 16:48:33->Self-hosted LiveSync v0.17.18 0.17.18
2023/1/28 16:48:33->Open Database...
2023/1/28 16:48:34->Open Database...
2023/1/28 16:48:35->Database Info
2023/1/28 16:48:35->Database is now ready.
2023/1/28 16:48:37->Database closed (by close)
2023/1/28 16:48:37->Open Database...
2023/1/28 16:48:41->Open Database...
2023/1/28 16:48:42->Database Info
2023/1/28 16:48:43->Database is now ready.
2023/1/28 16:48:44->Initialize and checking database files
2023/1/28 16:48:44->Updating database by new files
2023/1/28 16:48:44->UPDATE DATABASE
2023/1/28 16:48:44->UPDATE DATABASE done.
2023/1/28 16:48:44->UPDATE Storage
...
2023/1/28 16:48:51->Error:Failed to collect one of chunks
2023/1/28 16:48:52->Error while loading Self-hosted LiveSync
2023/1/28 16:48:53->Content saved:i:.obsidian/core-plugins-migration.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/app.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/appearance.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/community-plugins.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/core-plugins.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/plugins/obsidian-toggl-integration/data.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/plugins/calendar/data.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->Content saved:i:.obsidian/plugins/quickadd/data.json ,chunks: 1 (new:0, skip:1, cache:0)
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/core-plugins-migration.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/plugins/obsidian-toggl-integration/data.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/appearance.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/app.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/community-plugins.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/core-plugins.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/plugins/calendar/data.json: (hidden) Done
2023/1/28 16:48:53->STORAGE --> DB:.obsidian/plugins/quickadd/data.json: (hidden) Done

**Comment by vrtmrz** [comment]
Thank you for testing! And, sorry to have wasted your time.

Eventually, I thought back, that there was a minor change which remove the delays for collecting chunks on the boot sequence to address the possibility of being offline, but this may not have been as good as it seemed in the first place.

I will address it soon!

**Comment by vrtmrz** [comment]
I looked into the relevant routines but was not so wrong. but in some cases, error handling was not yet sufficient.
Fixed and add logging at v0.17.19.
I am sorry to say this is the second time, but could you try again?

**Comment by dlphnkck** [comment]
I updated the LiveSync plugin to version 0.17.19 and suddenly it syncs between each of my 5 devices!

So far, it syncs just as it did before. It was very helpful. Thank you for your valuable time.

I will continue to use of the LiveSync plugin in the future. Thank you very much for taking the time to respond to our request.

**Comment by vrtmrz** [comment]
I am so relieved to hear that! It's great to hear that you find this plugin useful and that you like it.
Sorry for the inconvenience, and thank you very much for helping improvements of this plug-in.
