### ISSUE TITLE
File changes are synced, but don't merged automatically in other devices.

### ISSUE THREAD

**Issue by takeaship** [vrtmrz/obsidian-livesync#179]
- Self-hosted LiveSync version: 0.17.25
- 3 Devices: 
    - Android 13
    - Windows 11
    - Windows 11
- Settings
    - a preset configuration "LiveSync" is applied.

Changes in each devices seems to be synced in file history. 
But don't merged automatically in other devices.

To update files, select `Self-Hosted LiveSync Show History` > `Back to this (newer) revision` manually is required.
How to merge changes from other devices automatically?

**Comment by vrtmrz** [comment]
Thank you for pointing this out to me!
It was not only while in conflicting but also modified documents would not be updated.
Fixed at v0.17.26, Could you please try this once?

**Comment by takeaship** [comment]
Thank you, I confirmed this problem is fixed.
