### ISSUE TITLE
[FR] add some debug into "test" button for CouchDB

### ISSUE THREAD

**Issue by thehotery** [vrtmrz/obsidian-livesync#18]
Its, of course, related with issue about lack of documentation about CouchDB, but anyway..
I'm first time using Coach DB and stuck with "not connected error"...  Its says nothing about what happend. I'm added ssl (maybe its the reason, like issue in android), tested connection with curl (its works), then discovered that i'm not enabled CORS... Its stupid mistake, but really can help new users.
Please consider to add some debug function that shows actual error (no connection to server, permission issue, CORS not enabled, cant resolve domain name,..)

**Comment by vrtmrz** [comment]
There is no stupid mistake. Only there's no information to understand what's going on! 
Thank you for the great suggestions.
It will be implemented!

**Comment by vrtmrz** [comment]
Implemented! but there're some limitations,
If you reached the server, a verbose message will be shown(e.g., authentication error)
But from the limitation of the runtime, network error isn't shown.
And every error log is shown in more detail.

**Comment by thehotery** [comment]
Its great! now its much easy to use
