### ISSUE TITLE
Requests blocked by CORS policy

### ISSUE THREAD

**Issue by FaraSeer** [vrtmrz/obsidian-livesync#181]
Hello!
I installed coachDB with the recommended settings and I have https URL to it from KeenDNS.
When I setup a single obsidian vault on desktop, everething seems OK.
When I setup the second one (on another desktop), at first, everything is OK as well, both instances can sync (I use open-copy URL mechanism for subsequent instances).
However, after re-opening one of instances, I start getting CORS error:
```
plugin:obsidian-livesync:21932 Obsidian Vault:2/21/2023, 11:36:44 PM->Before LiveSync, start OneShot once...
plugin:obsidian-livesync:21932 Obsidian Vault:2/21/2023, 11:36:44 PM->Oneshot Sync begin... (pullOnly)
index.html:1 Access to fetch at 'https://<my-url>' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
<my-url>:1          Failed to load resource: net::ERR_FAILED
plugin:obsidian-livesync:21932 Obsidian Vault:2/21/2023, 11:36:45 PM->TypeError:Failed to fetch
plugin:obsidian-livesync:21932 Obsidian Vault:2/21/2023, 11:36:45 PM->could not connect to <my-url>: TypeError:Failed to fetch
**Note** This error caused by many reasons. The only sure thing is you didn't touch the server.
To check details, open inspector.
plugin:obsidian-livesync:21932 Obsidian Vault:2/21/2023, 11:36:45 PM->Could not connect to server.
```
Re-importing settings from URI helps, but only before next application re-opening.

The same situation with the android application - I am constantly get CORS error (with CORS origin http://localhost) and cannot connect to DB at all. If I am trying to connect android app to my server as subsequent app, seems that it breaks other connections.
All of them start sending the following requests (here is the coachDB log part) and have the same log messages as above:
```
[notice] 2023-02-21T20:35:28.609110Z nonode@nohost <0.19457.0> 8118c50279 192.168.1.53 192.168.1.1 undefined OPTIONS /<my-db>/ 401 ok 0
[notice] 2023-02-21T20:36:45.385574Z nonode@nohost <0.20084.0> 4527d09ffb 192.168.1.53 192.168.1.1 undefined OPTIONS /<my-db>/ 401 ok 1
```
In normal situation with the first connection of the desktop app I don't see any OPTIONS requests at all.

Could you please help me with this issue?

P.S. I installed recent updates.

**Comment by vrtmrz** [comment]
Thank you for asking me! This must be troubling.

I would like to see what the Android device sent to the server and received, could you please capture them?

We can connect the device to your PC or Mac with the cable; with debug enabled. [Remote debug android devices](https://developer.chrome.com/docs/devtools/remote-debugging/) is a good document.

Then, please capture the request and response that raises `401` from the network pane on DevTools.

**Comment by FaraSeer** [comment]
@vrtmrz sorry for long response. Seems that I managed to fix the issue.
I just moved from KeenDNS to other one and set up https on my own reverse proxy. After that, syncronization worked properly.

Thanks anyway!
