### ISSUE TITLE
Daily file overwrite

### ISSUE THREAD

**Issue by MattLParker** [vrtmrz/obsidian-livesync#182]
Can't find any combination of settings that, When using a "daily" note extension. If I make changes on one device, then for example, on an ipad/ios, I "Share" some text to obsidian and hit daily, basically every time the ios device will over write anything that was there from any other device.

**Comment by vrtmrz** [comment]
Thank you for reporting this issue! 
This might be a part of #122. I will investigate it!

**Comment by MattLParker** [comment]
You are absolutely right and is directly related. My apologies for missing the original and for my far less than ideal explanation.

**Comment by vrtmrz** [comment]
Sorry for referring slightly neglected issue. However, we could notice that it has not been fixed yet now, I would like to thank you once again!

However, this can be a bit difficult. In some cases, I could synchronise the shared piece of the document. Have you noticed any other behaviour? If you have, please let me know that on #122.
