### ISSUE TITLE
LiveSync plugin settings: the skip pattern to default and select Cross-platform: workspace-mobile.json

### ISSUE THREAD

**Issue by dlphnkck** [vrtmrz/obsidian-livesync#188]
- Self-hosted LiveSync plugin Version 0.17.30
- Windows, Linux, Android, iPad.

Hi, I'm looking forward to using your LiveSync plugin. I always feel comfortable using the LiveSync plugin. Thank you very much.

I read a post about syncing the `workspace.json` and `workspace-mobile.json` files with the Obsidian Git plugin, "[workspace.json always shows up in source control : ObsidianMD (reddit.com)](https://www.reddit.com/r/ObsidianMD/comments/11ifeua/workspacejson_always_shows_up_in_source_control/)" made me think.

In the LiveSync plugin settings, go to

Sync Settings -> Skip patterns -> Restore the skip pattern to default and select Cross-platform:

`\/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$`

is set.
With this regex, wouldn't `workspace.json` for desktop be skipped on sync, but `workspace-mobile.json` for mobile not be skipped on sync, but synced every time?
Is this behavior what you are aiming for?

If I am wrong, I apologize.
Thank you in advance for your time. I am not in a hurry for a response. I would appreciate it if you could respond when you are available.

**Comment by hilsonp** [comment]
I found the following skip pattern worked best for me:
`\/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$,\/workspace-mobile.json`

I thought I submitted a PR for this but it seems not.

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
The default value had not been updated for a long time. I hope to fix it and I very much agree with @hilsonp. 

Since we are here, I will accept it if you can give me a PR, and I do not mind at all if you leave it to me.

**Comment by dlphnkck** [comment]
@vrtmrz and @hilsonp, sorry for the delayed response.

Thanks to your help, I've been monitoring for a few days after adding `\/workspace-mobile.json$` to Sync Settings->Skip patterns in the LiveSync plugin. 
As a result, the `workspace-mobile.json` conflict that used to occur when syncing between mobile devices has been resolved and I now have much less merging to do when syncing. 
Thank you very much.

I would be happy to give you a PR if you want, and I will leave it  to you.
Thanks for your time.
