### ISSUE TITLE
Merge infinite loop

### ISSUE THREAD

**Issue by stefandanzl** [vrtmrz/obsidian-livesync#189]
I copied my vault to another PC of mine, changed the Devicename in the LiveSync Settings and chose "fetch DB"
Now it hasn't synced any files added on mobile because it continously is trying to check files for merging according to ever reoccurring log entries like the following:

```
5.3.2023, 21:03:48->DB -> STORAGE (modify,force,plain) Journal/2023/2023-02/2023-02-25 Sat.md
5.3.2023, 21:03:48->automatically merged:Journal/2023/2023-02/2023-02-25 Sat.md
5.3.2023, 21:03:48->conflict:Automatically merged, but we have to check it again
```
![image](https://user-images.githubusercontent.com/19376127/222983022-723cc756-5a66-415a-aa39-0dc62f97b1b7.png)
in the Statusbar you can see how many files the system has been trying to sync but the vault only contains a total of 640 files

Would you advice against copying the vault files manually to a new device and instead let LiveSync get them on its own from the DB for the first synchronization?

I'm using the following sync settings at the moment:

![image](https://user-images.githubusercontent.com/19376127/222983320-969552af-68bf-4fea-84d1-63fbbc7b93e5.png)

**Comment by stefandanzl** [comment]
Also I've got the issue that I can't just recreate my vault from a backup because the database data still remaing on the PC is always messing up the freshly recovered vault with later added files. In which directory are those files stored? This happens still with disabled Wifi.

**Comment by stefandanzl** [comment]
I fixed it by once again resetting all Obsidian clients and my CouchDB Server.
I would recommend adding some detection mechanism for copied vaults on other devices - the timestamps of the files should be exactly the same in those cases with the data being identical aswell.
As far as I know this is what breaks the system, if that's the case maybe add some sort of warning label not to copy over files but instead only fetch them through the database server.

**Comment by stefandanzl** [comment]
Hey once again, some days ago I saw that you added very interesting details to the [README.md](https://github.com/vrtmrz/obsidian-livesync/blob/main/README.md)

>Also, with `redflag2.md` placed, we can automatically rebuild both the local and the remote databases during the boot-up sequence. With `redflag3.md`, we can discard only the local database and fetch from the remote again.

For the above stated scenario of copying your vault to another device `redflag3.md` would be ideal then I guess, without risking any unwanted uploading behaviour or having to first boot up Obsidian without internet connection!

I did not dare to try it yet but assuming from your previous answer I should not expect any issues because of the "created" date being the same on two devices, is that right?
Or should I play it safe and generally also delete all note files and directories in the Vault folder when creating the `redflag3.md` file after copying it to another device?

One definitive problem of mine was some custom (but not executed) script in my vault that Obsidian did not like when being created by LiveSync.

Is there any way to view the "pending" files, which are displayed with "⌛"? Maybe by activating verbose logging?

**Comment by hilsonp** [comment]
This is definitely not answering all your questions but you can find how I safely copied my vault from one device to two other using the redflag2.md and redflag3.md. 

https://github.com/vrtmrz/obsidian-livesync/issues/192#issuecomment-1481867704

In your case, if you remote db is ok, you may simply use the redflag3.md on the device to be rebuilt but I would definitely delete files on this device (with a proper backup first). 

Once the device is rebuilt, it is easy to compare the clean vault with the backup using folder comparison tools.

**Comment by vrtmrz** [comment]
@stefandanzl 
> For the above stated scenario of copying your vault to another device redflag3.md would be ideal then I guess, without risking any unwanted uploading behaviour or having to first boot up Obsidian without internet connection!

Yes, this is right if we are sure the configuration has been correct. 

> I did not dare to try it yet but assuming from your previous answer I should not expect any issues because of the "created" date being the same on two devices, is that right?
Or should I play it safe and generally also delete all note files and directories in the Vault folder when creating the redflag3.md file after copying it to another device?

If modified times are (almost) matched, the files will not be compared. and if modified times are not matched, the file is compared with the remote one. If there is no difference in the files afterwards, no action is performed in the vault (Just only the confliction on the database will be merged). 

As described above, using the existing files might work for reducing transfer volumes or resurrecting local changes. However, you all are correct, absolutely safer to empty the vault once.
