### ISSUE TITLE
"Open settings and check message" without any apparent error but no sync to remote CouchDB happens

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#19]
Testing the connection works without errors, an initial upload/sync using Drop and send worked, too, but from that point on, I get a message "Open settings and check message" and no changes are actually pushed to the remote CouchDB.

The message log reports this:

```
25.11.2021, 10:48:29->save ok:id:h:9a7835c0 rev:1-1b7f5fd78f1448aecf909f728961e119  
25.11.2021, 10:48:29->note content saven, pieces:5 new:1, skip:4, cache:4  
25.11.2021, 10:48:29->note saven:0-WorkInProgress/Obsidian LiveSync.md:6-0984a9894c70267934145d5e5468ee5b  
25.11.2021, 10:48:29->put database:0-WorkInProgress/Obsidian LiveSync.md(plain)
```

Nothing further in the developer console, also no apparent network traffic, so I suppose something is stuck without an error message...

**Comment by vrtmrz** [comment]
It's the warning message that the database version has been upgraded. That indicates the plugin should be upgraded on every device.
When the notice has been shown, you can see the message with a red border in the setting dialog.
and the button 'I got and updated' is inside there. Could you press that after you have updated?

**Comment by arminus** [comment]
Ok, I didn't realize that I had to click that message, i.e. the button didn't visually quite show up like a button... But now everything seems to work - from one device. Will test with a 2nd device later ;-)
