### ISSUE TITLE
Failsafe procedure

### ISSUE THREAD

**Issue by hilsonp** [vrtmrz/obsidian-livesync#192]
I have 3 devices syncing the same vault: LaptopA (Win10), LaptopB (Win10), MobileA (iOS)

For whatever unknown reason, my devices went out of sync.
This is scary because it defeat the whole idea of a sync solution.

I tried to get this quatuor (3 devices + CouchDB) in sync but whatever I tried, I fail.

Can you please provide a step by step procedure to:
- Take LaptopA files as reference to rebuild LaptopA local db and overwrite CouchDB completely.
- Dismiss local files and local database on LaptopB and rebuild both local files and local database from the newly rebuild CouchDB.
- Dismiss local files and local database on MobileA and rebuild both local files and local database from the newly rebuild CouchDB.

**Comment by vrtmrz** [comment]
Thank you for your question! Actually, this step has got complicated day by day.
The following procedure is the most stable one at the moment.

1. On Laptop A (The reference device), perform `Rebuild everything`. 
  Then, once the remote and local databases should be right.
2. Copy the Setup-URI on Laptop A with a temporary passphrase(anything right).
3. On Laptop B and MobileA, perform `Open Setup-URI` and paste the setup URI into the dialogue, and answer `yes` to `Importing LiveSync's conf, OK?`. Then we will be asked `How would you like to set it up?`, please answer `Set it up as secondary or subsequent device`.
  Step 3 may take a bit long, but we can perform it parallelly.

If we are sure that the configurations of all devices matched, we can perform `Fetch` on Laptop B and Mobile A, instead of steps 2 and 3.
And for your information, if for some reason the configuration dialogue cannot be displayed,  we can place `redflag3.md` (no extension required within Obsidian) and restart Obsidian. If the file exists, `Fetch` is automatically performed.

For further reference, `redflag2.md` does Step 1. I now realise that they are not documented.

**Comment by hilsonp** [comment]
@vrtmrz thank you again for your availability !

For the record the problem I had before you explained me was the following:

Laptop A (reference) had files : A B C
Laptop B had files : A C D
Mobile A had files : B C E

I somehow did your procedure and ended up with:
Laptop A : A B C
Laptop B : A B C D
Mobile A : A B C E

This was not quite correct as my goal was to have the exact same content everywhere (A B C) coming from the reference machine Laptop A.

In the next comment, I will document the exact process I followed to get everything aligned as simply as possible.

Thank you for your help and hoping this can help you write a FAQ.

**Comment by hilsonp** [comment]
# Goal

Elect one Obsidian client's vault as reference and reset/overwrite the CouchDB and all other Obsidian clients with this reference vault.

# Initial situation

- Laptop A: Has some content and is declared as the reference content that we want to keep.
- CouchDB: Has some content that we are ready to reset/loose.
- Laptop B: Will be reset/overwritten with Laptop A vault's content.
- Mobile C: Will be reset/overwritten with Laptop A vault's content. 

# Target situation

Laptop A (filesystem and local livesync DB), CouchDB, Laptop B (filesystem and local livesync DB) and Mobile C (filesystem and local livesync DB) all have the exact same content coming from Laptop A's vault.

# Assumptions

1. The Obsidian Livesync plugin version is the same on all devices
2. The Obsidian Livesync plugin configuration is the same on all devices, especially:
   Otherwise, you may read https://github.com/vrtmrz/obsidian-livesync/issues/192#issuecomment-1479038160
   - The chunk size
   - The batch size
   -  The batch limit

# Procedure

1. Stop/kill Obsidian on all clients (Laptop A, Laptop B, Mobile C)
2. Make a backup of the vault's folder on each client.
4. **Important:** Delete everything **except the .obsidian folder** in Laptop B and Mobile C's vaults.
5. Recreate Laptop A local Livesync DB and remote CouchDB
   1. Create a file or directory named redflag**2**.md in the root of Laptop A's vault.
   2. Start Obsidian on Laptop A.
    The redflag2.md forces a "Rebuild everything" action at the Obsidian startup and reset/overwrite the local Livesync DB and the remote CouchDB with the existing files found in the Laptop A vault.
6. Recreate the Laptop B and Mobile C vault (local DB and files) from the fresh CouchDB
   1. Create a file or directory named redflag**3**.md in the root of Laptop B and Mobile C's vaults.
   2. Start Obsidian on Laptop B and Mobile C.
    The redflag3.md forces a "Fetch" action at the Obsidian startup and reset/overwrite the local Livesync DB then launch the synchro with the remote CouchDB.
7. Once the synchro has completed everywhere:
   1. Stop Obsidian on all clients.
   2. Remove the redflag2.md and redflag3.md.
   3. Start Obsidian and re-set the Livesync's Sync Settings (eg: Livesync set to ON).

At this point, the 3 devices should have the same vault content 🎉.
You may use any folder comparison tool to compare the freshly (re)created vault and the vault backup backup you took at point 2 in order to bring back in your vault any extra content that was present on Laptop B and Mobile C before the reset.

**Comment by vrtmrz** [comment]
I really appreciate this (with the document structure too!)
I have just noted this chaos in [the new doc](https://docs.vrtmrz.net/LiveSync/procedures/Setup+Self-hosted+LiveSync+to+secondary+or+subsequent+devices). I will modify it to mention the deletion.
I saw the discussion first and missed this (in addition to that I wrote as if to raise the white flag), and I regret that let you resolve this in such a tedious way.
Let me say thank you again!

**Comment by hilsonp** [comment]
It’s ok 👌 I did not loose data and your first message was really helpful. If you need help with writing docs, we may find some way to collaborate.Again thank you for the products you build. Le 24 mars 2023 à 09:36, vorotamoroz ***@***.***> a écrit :﻿
I really appreciate this (with the document structure too!)
I have just noted this chaos in the new doc. I will modify it to mention the deletion.
I saw the discussion first and missed this (in addition to that I wrote as if to raise the white flag), and I regret that let you resolve this in such a tedious way.
Let me say thank you again!
