### ISSUE TITLE
There are always errors in log even though all data is synced successfully

### ISSUE THREAD

**Issue by WinkeyLin** [vrtmrz/obsidian-livesync#197]
Here are the logs, I'm a little concerned about whether it will corrupt my files. Is this normal or I have configured something wrong? Thanks in advance.

```
2023/4/4 16:28:53->HTTP:GET to:/_changes?style=all_docs&feed=longpoll&heartbeat=30000&since=181-g1AAAACLeJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5MT4XKMBubpxomGicgq4Yh_Y8FiDJ0ACk_kNNCQObYpZoYmmRZI6uJwsAfSgrOA&limit=250 -> failed
2023/4/4 16:28:53->TypeError:Failed to fetch
2023/4/4 16:28:53->replication paused
2023/4/4 16:28:55->replication paused
2023/4/4 16:30:08->HTTP:GET to:/_changes?style=all_docs&feed=longpoll&heartbeat=30000&since=181-g1AAAACLeJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5MT4XKMBubpxomGicgq4Yh_Y8FiDJ0ACk_kNNCQObYpZoYmmRZI6uJwsAfSgrOA&limit=250 -> failed
2023/4/4 16:30:08->TypeError:Failed to fetch
2023/4/4 16:30:08->replication paused
2023/4/4 16:30:09->replication paused
2023/4/4 16:31:22->HTTP:GET to:/_changes?style=all_docs&feed=longpoll&heartbeat=30000&since=181-g1AAAACLeJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5MT4XKMBubpxomGicgq4Yh_Y8FiDJ0ACk_kNNCQObYpZoYmmRZI6uJwsAfSgrOA&limit=250 -> failed
2023/4/4 16:31:22->TypeError:Failed to fetch
2023/4/4 16:31:22->replication paused
2023/4/4 16:31:24->replication paused
```

![image](https://user-images.githubusercontent.com/56619122/229735557-9b572077-962a-45a2-a6c9-ff53ece88c7a.png)

**Comment by vrtmrz** [comment]
Sorry for being late! 
HTTP 504 error means `Gateway timed out`.
Self-hosted LiveSync watches the remote database for LiveSync by long pooling. If you are behind the proxy, the timeout of the gateway might be shorter than the one the LiveSync waits for, or the proxy detects the no-transferring and disconnect them.

Could you please try enabling `Use timeouts instead of heartbeats`?

**Comment by WinkeyLin** [comment]
I try to enable the option but the errors remains. Then I find it is CDN that causes the problem, when I stop using it everything work fine, though I don't know the specific reson.
Thanks for your great work again!

**Comment by onnyyonn** [comment]
@WinkeyLin I am facing the same issue. Can you please elaborate what you mean by CDN?
