### ISSUE TITLE
CORS problem with multiple devices (Windows and iOS)

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#20]
As it turns out, the CORS configuration differs per device. Obsidian running on Windows requires an Access-Control-Allow-Origin 'app://obsidian.md' but Obsidian running on an iPad apparently  'capacitor://localhost' 

The problem is that neither setting 2 Access-Control-Allow-Origin headers is working:

```
Access to fetch at '...' from origin 'app://obsidian.md' has been blocked by CORS policy:
The 'Access-Control-Allow-Origin' header contains multiple values 'capacitor://localhost, app://obsidian.md',
but only one is allowed. Have the server send the header with a valid value, or,
if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

nor setting Access-Control-Allow-Origin to "*" is working:

```
Access to fetch at '...' from origin 'app://obsidian.md' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check:
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*'
when the request's credentials mode is 'include'.
```

**Comment by vrtmrz** [comment]
Did you keep the Caddy's CORS configurations?

Please disable all CORS configurations and make them transparent to CouchDB once.

If you set wildcard on the CouchDB's configuration, CouchDB will send the origin on  "Access-Control-Allow-Origin" automatically from the request header's "Origin".

And CouchDB's origins settings is the same:
```sample
[cors]
origins="app://obsidian.md,capacitor://localhost"
```
If the host of the request is listed up, CouchDB will send the matched one.

**Comment by arminus** [comment]
Ok, I now disabled all of Caddy's CORS headers and set CouchDB's local.ini to

```
[cors]
origins = "app://obsidian.md,capacitor://localhost"
```

With that, I'm back to square one:

```
Access to fetch at '...' from origin 'app://obsidian.md' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin'
header is present on the requested resource. If an opaque response serves your needs, set the
request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Seems to me as if Caddy won't pass the CouchDB headers (if they are indeed set) back to the client?

But actually, I don't necessarily need to stick with Caddy, if you have a working Traefik etc. docker-compose.yml, I'd gladly test that...

**Comment by vrtmrz** [comment]
Thank you for your try!
Your docker-compose.yml doesn't seem wrong. 
I'll try to reproduce this issue, and post the sample using traefik too.

**Comment by arminus** [comment]
Ok, I figured it out. The problem were your double quotes for the 2 origins in CouchDB's local.ini.

So removing all CORS configs form the caddy labels and having

```
[cors]
origins = app://obsidian.md,capacitor://localhost
```

in local.ini finally works :-) Let's see how it goes with an Android client...

**Comment by vrtmrz** [comment]
Oh, excuse me. I didn't notice this!

Android's origin was http://localhost when I started writing.
But looks like one of your writing is accepted now.
I'll check with the debugger later! Thank you so much!

**Comment by vrtmrz** [comment]
Solved by related issues and the [repo](https://github.com/vrtmrz/self-hosted-livesync-server).
