### ISSUE TITLE
.obsidian folder is visible and is not syncing correctly

### ISSUE THREAD

**Issue by Sirtz** [vrtmrz/obsidian-livesync#206]
Hi,

I have been using livesync on a couple of devices, everything working perfectly usually. Today I installed obsidian on my linux laptop, specifically the flatpak version. Once I set up livesync again with the setup URI, it set everything up but also created a new folder named "i:.obsidian". I believe this folder is for settings and themes and should be hidden by default, so I am wondering why it is showing up. 
Attached is the folder and log errors.
I hope there is a way to fix this, I also don't want to break my database so i hope nothing serious is wrong. 

![Screenshot from 2023-04-26 18-04-36](https://user-images.githubusercontent.com/26656736/234622557-0741dc75-2525-4b04-aafd-e8e7b3a5d951.png)
![Screenshot from 2023-04-26 18-05-10](https://user-images.githubusercontent.com/26656736/234622562-92fe5dea-b679-4f6c-9e37-46ede8b6a4e3.png)

**Comment by vrtmrz** [comment]
Thank you very much for opening this issue!
Just today, I opened my Chromebook for the first time in a while and noticed the same error occurred.
I will address this issue soon!

**Comment by vrtmrz** [comment]
@Sirtz 
This issue should have been fixed at v0.19.1. It had been caused by changing the logic which determines what filenames are accepted. 
Could you please check the latest version?

Also, please delete these incorrectly created files manually. Sorry for your inconvenience!

**Comment by Sirtz** [comment]
Manually merging + deleting worked for me, everything seems to be fixed now. Thank you very much!

**Comment by vrtmrz** [comment]
I am relieved to hear that!
