### ISSUE TITLE
File with platform dependent name has been skipped

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#21]
It appears I have a note with a $ sign in its name, that file doesn't gets synced into an iOS vault. Can't those special characters be escaped/unicoded/etc. ?

**Comment by vrtmrz** [comment]
I may have fallen asleep: I completely misunderstood the specification.
Tested by Mac, Windows, Linux, Android, and iOS. Every device allowed $sign.

This will be fixed in the next release!

Sorry for trouble you. And thank you for your report! 
Always helpful!

**Comment by vrtmrz** [comment]
Fixed on 0.1.22.
