### ISSUE TITLE
Error while loading Self-hosted LiveSync on PC

### ISSUE THREAD

**Issue by TH6661349** [vrtmrz/obsidian-livesync#211]
Hi! I'm currently using fly.io on Windows 10 and iPhone to share notes, but the method stops working ever since April this year. What is the possible culprit? Customization sync and hidden file sync are both enabled. Obsidian 1.2.7 and the plugin version 0.19.3.

I'm done fixing database configuration and confirmed the database connection works.

Opening Obsidian on Win gives me an "Error while loading Self-hosted LiveSync". Also, when I update a file, update gets running forever.
![](https://i.imgur.com/wj23xma.png)

Thanks in advance.

**Comment by TH6661349** [comment]
Hmm, it seems that I ran out of memory on fly.io while trying to fix the problem.

**Comment by TH6661349** [comment]
Thanks for the reply! Enabled the `Verbose log` and here's a result of `Show log`.

2023/5/10 20:07:35->Enumerating files... 31
2023/5/10 20:07:35->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-daily-notes-viewer.md
2023/5/10 20:07:35->Enumerating files... 32
2023/5/10 20:07:35->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-day-planner.md
2023/5/10 20:07:35->Enumerating files... 33
2023/5/10 20:07:35->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-dictionary-plugin.md
2023/5/10 20:07:35->Enumerating files... 34
2023/5/10 20:07:35->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-emoji-toolbar.md
2023/5/10 20:07:36->Enumerating files... 35
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-excalidraw-plugin.md
2023/5/10 20:07:36->Enumerating files... 36
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-footnotes.md
2023/5/10 20:07:36->Enumerating files... 37
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-fullscreen-plugin.md
2023/5/10 20:07:36->Enumerating files... 38
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-hotkeys-for-templates.md
2023/5/10 20:07:36->Enumerating files... 39
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-hover-editor.md
2023/5/10 20:07:36->Enumerating files... 40
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-icon-folder.md
2023/5/10 20:07:36->Enumerating files... 41
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-icons-plugin.md
2023/5/10 20:07:36->Enumerating files... 42
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-imgur-plugin.md
2023/5/10 20:07:36->Enumerating files... 43
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-kanban.md
2023/5/10 20:07:36->Enumerating files... 44
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-kindle-plugin.md
2023/5/10 20:07:36->Enumerating files... 45
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-latex.md
2023/5/10 20:07:36->Enumerating files... 46
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-link-archive.md
2023/5/10 20:07:36->Enumerating files... 47
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-list-callouts.md
2023/5/10 20:07:36->Enumerating files... 48
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-livesync.md
2023/5/10 20:07:36->Enumerating files... 49
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-map-view.md
2023/5/10 20:07:36->Enumerating files... 50
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-metatable.md
2023/5/10 20:07:36->Enumerating files... 51
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-mind-map.md
2023/5/10 20:07:36->Enumerating files... 52
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-minimal-settings.md
2023/5/10 20:07:36->Enumerating files... 53
2023/5/10 20:07:36->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-outliner.md
2023/5/10 20:07:37->Some chunks are not exists both on remote and local database.
2023/5/10 20:07:37->Could not retrieve chunks
2023/5/10 20:07:37->Something went wrong on reading PC-main/PLUGIN_MAIN/obsidian-outliner.md(ix:PC-main/PLUGIN_MAIN/obsidian-outliner.md) from database:
2023/5/10 20:07:37->Error:Failed to collect one of chunks
2023/5/10 20:07:37->Enumerating files... 54
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-pandoc.md
2023/5/10 20:07:37->Enumerating files... 55
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-relative-line-numbers.md
2023/5/10 20:07:37->Enumerating files... 56
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-style-settings.md
2023/5/10 20:07:37->Enumerating files... 57
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-tabs.md
2023/5/10 20:07:37->Enumerating files... 58
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-timelines.md
2023/5/10 20:07:37->Enumerating files... 59
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-tracker.md
2023/5/10 20:07:37->Enumerating files... 60
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-zoom.md
2023/5/10 20:07:37->Enumerating files... 61
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/obsidian42-brat.md
2023/5/10 20:07:37->Enumerating files... 62
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/pane-relief.md
2023/5/10 20:07:37->Enumerating files... 63
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/periodic-notes.md
2023/5/10 20:07:37->Enumerating files... 64
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/quick-explorer.md
2023/5/10 20:07:37->Enumerating files... 65
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/quickadd.md
2023/5/10 20:07:37->Enumerating files... 66
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/recent-files-obsidian.md
2023/5/10 20:07:37->Enumerating files... 67
2023/5/10 20:07:37->plugin-ix:PC-main/PLUGIN_MAIN/review-obsidian.md
2023/5/10 20:07:38->Some chunks are not exists both on remote and local database.
2023/5/10 20:07:38->Could not retrieve chunks
2023/5/10 20:07:38->Something went wrong on reading PC-main/PLUGIN_MAIN/review-obsidian.md(ix:PC-main/PLUGIN_MAIN/review-obsidian.md) from database:
2023/5/10 20:07:38->Error:Failed to collect one of chunks
2023/5/10 20:07:38->Enumerating files... 68
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/simple-embeds.md
2023/5/10 20:07:38->Enumerating files... 69
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/sliding-panes-obsidian.md
2023/5/10 20:07:38->Enumerating files... 70
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/smart-random-note.md
2023/5/10 20:07:38->Enumerating files... 71
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/supercharged-links-obsidian.md
2023/5/10 20:07:38->Enumerating files... 72
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/table-editor-obsidian.md
2023/5/10 20:07:38->Enumerating files... 73
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/tag-wrangler.md
2023/5/10 20:07:38->Enumerating files... 74
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/templater-obsidian.md
2023/5/10 20:07:38->Enumerating files... 75
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/url-into-selection.md
2023/5/10 20:07:38->Enumerating files... 76
2023/5/10 20:07:38->plugin-ix:PC-main/PLUGIN_MAIN/various-complements.md

Also, here's a result of `Make report` if it helps.
----remote config----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace.json$\
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: false
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
workingUseDynamicIterationCount: false


BTW, is it normal that I need to fix database config manually each time I open Obsidian?

**Comment by TH6661349** [comment]
Another error message I forgot to attach.
![](https://i.imgur.com/CaRGoDX.png)

**Comment by huotui-xiaoji** [comment]
I also hit this issue on my ipad and ios sync.

**Comment by vrtmrz** [comment]
Thank you for the detail! And sorry for being late.
These chunk-retrieving errors are indeed a problem, however, resetting the configuration might be caused by the default configuration of fly.io having been migrated to their V2 platform. On the V2 platform, automatically starting and stopping machine has been implemented and enabled by default. 
More information is [here](https://fly.io/docs/apps/autostart-stop/). In summary, we should configure `auto_stop_machines` and `auto_start_machines` false in `fly.toml` like below:
```toml
# fly.toml app configuration file generated for the-app-name on 2023-05-16T08:37:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "the-app-name"
primary_region = "nrt"

[build]
  image = "couchdb:latest"

[http_service]
  internal_port = 5984
  force_https = true
  auto_stop_machines = false  
  auto_start_machines = false
  min_machines_running = 0

[env]
  COUCHDB_USER = "alkcsa93"
[mounts]
  source="couchdata"
  destination="/opt/couchdb/data"
```
[The gist](https://gist.github.com/vrtmrz/6715f01bf038c9f66e9d2768c3fdee36) has also been updated recently. If you have used this gist to make the CouchDB server, and troublesome to fetch `fly.toml`, modify it and deploy it again, I really regret to say this but please make the instance once again.

However, possibly we need an adjusted docker image to be more suitable.

Back to the topic, I will investigate the problem soon. Sorry for your inconvenience have not been resolved immediately.

**Comment by vrtmrz** [comment]
Today, I released v0.19.4, and it includes fixes for retrieving chunks. 
When the chunk could be parsed as false, it could not be resolved anymore. 

If this is caused by other reasons, it may not be fixed totally. However, it would help to isolate the problem.
I would be grateful if you could try v0.19.4.

**Comment by TH6661349** [comment]
Sorry for being late. I didn't get notified for some reason.

My fly.io page says `Your app is running in our Apps v1 platform. We'd recommend migrating to our Apps v2 platform for better reliability.`. Should I migrate it? I guess auto start/stop thingy is not a problem at the moment since my app seems to be on V1. Anyway resetting the configuration problem seems to be fixed by the latest update.

I tried the latest version, and my iOS's sync status is 💤 forever. Sync Status says, LiveSync begin... -> Replication paused. My PC version still says `Error while loading Self-hosted LiveSync` and the log is below.

2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-auto-link-title.md
2023/5/21 19:22:16->Enumerating files... 27
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-charts.md
2023/5/21 19:22:16->Enumerating files... 28
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-chartsview-plugin.md
2023/5/21 19:22:16->Enumerating files... 29
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-checklist-plugin.md
2023/5/21 19:22:16->Enumerating files... 30
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-daily-notes-viewer.md
2023/5/21 19:22:16->Enumerating files... 31
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-day-planner.md
2023/5/21 19:22:16->Enumerating files... 32
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-dictionary-plugin.md
2023/5/21 19:22:16->Enumerating files... 33
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-emoji-toolbar.md
2023/5/21 19:22:16->Enumerating files... 34
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-excalidraw-plugin.md
2023/5/21 19:22:16->Enumerating files... 35
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-footnotes.md
2023/5/21 19:22:16->Enumerating files... 36
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-fullscreen-plugin.md
2023/5/21 19:22:16->Enumerating files... 37
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-hotkeys-for-templates.md
2023/5/21 19:22:16->Enumerating files... 38
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-hover-editor.md
2023/5/21 19:22:16->Enumerating files... 39
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-icon-folder.md
2023/5/21 19:22:16->Enumerating files... 40
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-icons-plugin.md
2023/5/21 19:22:16->Enumerating files... 41
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-imgur-plugin.md
2023/5/21 19:22:16->Enumerating files... 42
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-kanban.md
2023/5/21 19:22:16->Enumerating files... 43
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-kindle-plugin.md
2023/5/21 19:22:16->Enumerating files... 44
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-latex.md
2023/5/21 19:22:16->Enumerating files... 45
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-link-archive.md
2023/5/21 19:22:16->Enumerating files... 46
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-list-callouts.md
2023/5/21 19:22:16->Enumerating files... 47
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-livesync.md
2023/5/21 19:22:16->Enumerating files... 48
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-map-view.md
2023/5/21 19:22:16->Enumerating files... 49
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-metatable.md
2023/5/21 19:22:16->Enumerating files... 50
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-mind-map.md
2023/5/21 19:22:16->Enumerating files... 51
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-minimal-settings.md
2023/5/21 19:22:16->Enumerating files... 52
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-outliner.md
2023/5/21 19:22:16->Enumerating files... 53
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-pandoc.md
2023/5/21 19:22:16->Enumerating files... 54
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-relative-line-numbers.md
2023/5/21 19:22:16->Enumerating files... 55
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-style-settings.md
2023/5/21 19:22:16->Enumerating files... 56
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-tabs.md
2023/5/21 19:22:16->Enumerating files... 57
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-timelines.md
2023/5/21 19:22:16->Enumerating files... 58
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-tracker.md
2023/5/21 19:22:16->Enumerating files... 59
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian-zoom.md
2023/5/21 19:22:16->Enumerating files... 60
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/obsidian42-brat.md
2023/5/21 19:22:16->Enumerating files... 61
2023/5/21 19:22:16->plugin-ix:PC-main/PLUGIN_MAIN/pane-relief.md
2023/5/21 19:22:17->Enumerating files... 62
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/periodic-notes.md
2023/5/21 19:22:17->Enumerating files... 63
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/quick-explorer.md
2023/5/21 19:22:17->Enumerating files... 64
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/quickadd.md
2023/5/21 19:22:17->Enumerating files... 65
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/recent-files-obsidian.md
2023/5/21 19:22:17->Enumerating files... 66
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/review-obsidian.md
2023/5/21 19:22:17->Enumerating files... 67
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/simple-embeds.md
2023/5/21 19:22:17->Enumerating files... 68
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/sliding-panes-obsidian.md
2023/5/21 19:22:17->Enumerating files... 69
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/smart-random-note.md
2023/5/21 19:22:17->Enumerating files... 70
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/supercharged-links-obsidian.md
2023/5/21 19:22:17->Enumerating files... 71
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/table-editor-obsidian.md
2023/5/21 19:22:17->Enumerating files... 72
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/tag-wrangler.md
2023/5/21 19:22:17->Enumerating files... 73
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/templater-obsidian.md
2023/5/21 19:22:17->Enumerating files... 74
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/url-into-selection.md
2023/5/21 19:22:17->Enumerating files... 75
2023/5/21 19:22:17->plugin-ix:PC-main/PLUGIN_MAIN/various-complements.md
2023/5/21 19:22:17->All files enumerated

**Comment by TH6661349** [comment]
Just reporting 0.19.5 still does not fix the issue, unfortunately.

**Comment by vrtmrz** [comment]
Thank you for your reply! Unfortunately, some instances on fly.io are automatically migrated to V2. 
Could you please check the database configuration once again? It might be lost.

May rebuilding the instance having persistence will fix this problem on V2.
  
The Colab note for making the CouchDB instance which has been rewritten for V2 is here:
https://gist.github.com/vrtmrz/b437a539af25ef191bd452aae369242f

I so regret to ask you to do over and over, but I hope that these things could help us.

**Comment by TH6661349** [comment]
Much appreciated for your continuous support!

I checked the configuration again, but it works perfectly. Actually it works without issues ever since 0.19.4, so I believe it's not migrated to v2 automatically in this case. I can try to migrate it manually and run the latest colab, but I'd like to make it clear whether it's necessary or not before actually doing it.

入院されたと伺い驚きました。痛みはひとまず落ち着かれたようで何よりです。こちら、全く急ぎの要件ではありませんので、まずは治療に専念いただき、一日も早く全快されることを祈念しております。いつも問題解決に向けてお付き合いいただきありがとうございます。

**Comment by vrtmrz** [comment]
Thank you for the detail! I am very glad to hear that!
As you mentioned, if you have not been troubled about the previous fly.io image, you can leave it!

ありがとうございます！結局原因もわからぬままですが、まぁ元気になってきたので退院までの日を指折り数えています。
こちらこそ、いつも気長に解決までお付き合いいただいてありがとうございます。なんでもおっしゃってくださいね。

**Comment by TH6661349** [comment]
Hi, since the configuration started to corrupt again after tweaking skip patterns, I tried rebuilding the instance (I went with colab). The setup wizard was quite useful for this! It seems that both Win and iOS sync stable for now. Maybe I should've tried your suggestion earlier.

One thing I'm puzzled about was Replication from Fauxton, but I just rebuild the database from scratch. Thank you so much again for your continuous support!

**Comment by TH6661349** [comment]
Hmm, sorry for appearing over and over, the app kept asking me to fetch rebuild DB and I did it, and then the connection starts to be unstable again, so I started it over from scratch. This time, only 200 out of 1947 files syncs and the plugin settings do not sync on iOS. What should I do?

**Comment by vrtmrz** [comment]
Thank you for trying it out! I am very happy to hear that building the database has become easier for you!

However, it is sad to hear that the synchronisation got unstable again. May I ask what message or log had shown while the situation? 
And one more possibility, could you please check the Dashboard of fly.io and make sure the resource does not run out?
If so, possibly we have to use a bit lower batch size and batch limit, chunk size.

**Comment by TH6661349** [comment]
An error message on PC, although the databse connection has been stable since I built this new instance.
![](https://i.imgur.com/5zBUcQm.png)

Here's a result of the new `Make report` just in case.
----remote config----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/,
  \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333

This is the log on iOS when the problem happens.
![](https://i.imgur.com/N73DwhY.jpeg)
![](https://i.imgur.com/Gha0oh7.jpeg)
![](https://i.imgur.com/DE6XHV8.jpeg)
![](https://i.imgur.com/umkDemD.jpeg)
![](https://i.imgur.com/56bZSBE.jpeg)
![](https://i.imgur.com/Bf9K9Nf.jpeg)
![](https://i.imgur.com/mTWPlJe.jpeg)

I checked the dashboard, and it's ok, I guess?
![](https://i.imgur.com/iMDkucS.png)

Below is possibly an error message monitoring says.
[error] 2023-06-05T19:50:47.574576Z nonode@nohost emulator -------- Error in process <0.1026.0> with exit value:

2023-06-05T19:50:47.575 {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

Thanks!

**Comment by TH6661349** [comment]
I updated to 0.19.10 and this is an error message I forgot to attach previously.
![](https://i.imgur.com/xZL6D9x.png)

**Comment by TH6661349** [comment]
The new colab notebook fixed the issue.
See -> https://github.com/vrtmrz/obsidian-livesync/issues/225
