### ISSUE TITLE
[Question] How to use this database with multiply users?

### ISSUE THREAD

**Issue by BobWs** [vrtmrz/obsidian-livesync#212]
Hi,
I,m testing your plugin and I have manage to setup the database as described and it is working for one user, but I was wondering how do I set this up for multiply users, each with their own vault? Is this possible? 
So e.g. 
user1 > vault1
user2 > vault2
user3 > vault3
etc.

**Comment by vrtmrz** [comment]
Hello, thank you for asking me!
I would not recommend it, but here are some ways to do it.

1. Making multiple users (`user1`, `user2` and `user3`) following the [CouchDB doc](https://docs.couchdb.org/en/stable/intro/security.html#users-documents).
2. Making databases `vault1`, `vault2` and `vault3`. And make sure that configuring permission. ([doc](http://localhost:15984/_utils/docs/api/database/security.html#db-security). )
3. Test synchronisation from each user's device, and make sure that E2EE and path obfuscation are enabled.
4. 
However, some operations can only be performed with administrative rights. (e.g. database rebuild). Dedicated CouchDB instances are preferred (Or making a proxy server for this might be the rigid right way; like the tasting server that once existed).

**Comment by BobWs** [comment]
Thank you for explaining!
