### ISSUE TITLE
How to remove encryption?

### ISSUE THREAD

**Issue by Michaelpalacce** [vrtmrz/obsidian-livesync#217]
Hey!

I've been using the self hosted livesync plugin for a while and was wondering what needs to be done if I want to remove encryption from a setup that uses encryption?

Do I just remove encryption settings and Overwrite the remote database?

**Comment by vrtmrz** [comment]
Hello, Thank you for asking me! We need to rebuild the database.

When we turn off the `End to End encryption` toggle, we will see a pen icon aside. Then, press the `Apply and Rebuild` button.

Changing passphrase and Path Obfuscation are also the same.

**Comment by Michaelpalacce** [comment]
Thank you for the reply!
