### ISSUE TITLE
Remote database settings cannot be edited anymore

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#22]
All 4 fields in the Remote database settings cannot be edited anymore. Single click into the textfield -> no edit cursor, value can't be changed.

**Comment by vrtmrz** [comment]
Since 0.1.16, these settings are locked while any synchronization is enabled to avoid corrupting the database.

All synchronization is disabled?

**Comment by arminus** [comment]
Ah, I wasn't aware that I had to disable sync in order to change these values.
