### ISSUE TITLE
笔记移动到另一个文件夹并同步后重复出现在2个文件夹中

### ISSUE THREAD

**Issue by lylunula** [vrtmrz/obsidian-livesync#223]
场景：有A、B、C三个设备，日常主要是A、B之间用Self-hosted LiveSync同步，非常顺畅，但是有时候会隔几周打开C，此时会遇到同步问题，即移动了文件夹的笔记会在原来文件夹和新的文件夹下同时出现。

原来的A、B、C的笔记结构是：

- 文件夹1:
    - 笔记a
    - 笔记b
- 文件夹2:
    - 笔记c

中间改为了：此时A、B同步了，C一直没有打开

- 文件夹1:
    - 笔记a
- 文件夹2:
    - 笔记b
    - 笔记c

过了几周打开了C，此时同步之后是：

- 文件夹1:
    - 笔记a
    - 笔记b
- 文件夹2:
    - 笔记b
    - 笔记c

可以看到此时笔记b出现了2次，请问一下是如何避免这个问题

---powered by deepl---

Scenario: There are three devices A, B and C. The daily syncing is mainly between A and B with Self-hosted LiveSync, which is very smooth, but sometimes C will be opened every few weeks, at which time the syncing problem will be encountered, i.e. the notes that have moved folders will appear under the original folder and the new folder at the same time.

The original A, B and C notes structure is

- Folder 1.
    - Notes a
    - Notes b
- Folder 2.
    - Notes c

Changed in the middle: at this point A and B are synced and C is never opened

- Folder 1.
    - Notes a
- Folder 2.
    - Notes b
    - Note c

C was opened after a few weeks, at which point after syncing it was

- Folder 1.
    - Notes a
    - Notes b
- Folder 2.
    - Notes b
    - Note c

You can see that note b appears 2 times at this point, so please ask how to avoid this problem

**Comment by vrtmrz** [comment]
Thank you for asking! I have understood your situation. May I ask you a few more things?

- Has note B been edited on device C while offline?
- Have you enabled `Do not keep metadata of deleted files`?
- I know that this is troublesome, however, could you please check the history of note B (in folder 1) on each device, by `Pick a file to show history`?  It is possible that it has been modified several times. It would be very helpful if you could make a sort of timeline. We probably need to infer propagation.

Like this:
| Time / Device | Device A | Device B | Device C | 
| - | - |  - | - |
| 05 Jun. 23:00 | edit | - | - |
| 05 Jun. 23:05 | - | edit | - |
| 05 Jun. 23:15 | - | - | edit |
| 08 Jun. 04:01 | delete | - | - |

**Comment by lylunula** [comment]
1. no, In fact, Device C is my iPhone, and I only sync it for viewing when I'm on a trip, so I basically don't modify it on Device C
2. no
3. In fact, I had to work very hard the day before to filter out the duplicate synced files and delete them, and I couldn't find the notes history

**Comment by lylunula** [comment]
Are you talking about the file recovery in the core plugin, I saw that there is no 'File integrity' function?

**Comment by vrtmrz** [comment]
No, I have implemented the `Show vault history` feature in Self-hosted LiveSync. It can be opened from the command palette.

**Comment by lylunula** [comment]
Roger, this feature is very useful. Thanks for the suggestion, but I have deleted the notes that were having sync problems as I was in a hurry. Next time I encounter the same problem, I will follow the steps you provided to check.
Thx~
