### ISSUE TITLE
docs/setup_own_server_ja.mdの誤り

### ISSUE THREAD

**Issue by satoko138** [vrtmrz/obsidian-livesync#228]
はじめまして。便利に使わせていただいています。

docs/setup_own_server_ja.mdに記載のlocal.iniに誤りがありました。

```
[chttpd_auth]
max_http_request_size = 4294967296
```
`max_http_request_size`は、`[chttpd]`配下かと思います。
→ObsidianのCheck database configurationで警告が出まして、chttpd配下に修正したところ解消しました。
→英語、中国語のmdでは、chttpd配下に記載されていました。

**Comment by vrtmrz** [comment]
こんにちは！イシュー作成いただきありがとうございます。
ありがとうございます！ご指摘の通りでしたので、修正しました。

**Comment by satoko138** [comment]
対応ありがとうございました！
