### ISSUE TITLE
Multiple datasource with target folder

### ISSUE THREAD

**Issue by zoic21** [vrtmrz/obsidian-livesync#229]
Hello,

I wonder if it's possible to define a new data source (same couchdb or not) affect to only one folder ? The idea it's to share folder between user with dedicated coudb server or database or prefix.

Thanks in advance.

**Comment by vrtmrz** [comment]
Thank you for asking me!
I had thought that it should be performed near CouchDB, and made [livesync-classroom](https://github.com/vrtmrz/livesync-classroom).
Does this meet your expectations?
