### ISSUE TITLE
Android version can download updated content from PC, but cannot upload modified content from mobile phone

### ISSUE THREAD

**Issue by xktder** [vrtmrz/obsidian-livesync#231]
Thank you to the author for providing such an excellent plugin. Thank you.
The Android version can download updated content from the PC, but cannot upload modified content from the phone.
The phone is Huawei's Mate20, and the phone system is Hongmeng.
The livesync plugin version is 0.19.11.
Couchdb uses a self built NAS Docker.

![Screenshot_20230622_101219_md obsidian](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/80ddbe57-a891-476e-8441-e8ef540c2eb2)

2023/6/22 上午9:53:58->{ "cors": { "credentials": "true", "headers": "accept, authorization, content-type, origin, referer", "max_age": "3600", "methods": "GET, PUT, POST, HEAD, DELETE", "origins": "app://obsidian.md,capacitor://localhost,http://localhost" }, "chttpd": { "bind_address": "any", "enable_cors": "true", "max_http_request_size": "4294967296", "port": "5984", "require_valid_user": "true" }, "admins": { "admin": "-pbkdf2-8facf49798d2f7c3e12f47c3f7df49ed00d883a3,aaa92519ed106acdc8d1a9d4f1447c01,10" }, "vendor": { "name": "The Apache Software Foundation" }, "feature_flags": { "partitioned||*": "true" }, "chttpd_auth": { "authentication_redirect": "/_utils/session.html", "hash_algorithms": "sha256, sha", "require_valid_user": "true", "secret": "a530739b0cdb3a9c816971dc2022adf9" }, "indexers": { "couch_mrview": "true" }, "prometheus": { "additional_port": "false", "bind_address": "127.0.0.1", "port": "17986" }, "httpd": { "WWW-Authenticate": "Basic realm=\"couchdb\"", "bind_address": "127.0.0.1", "enable_cors": "true", "port": "5986" }, "smoosh": { "state_dir": "./data" }, "couch_httpd_auth": { "authentication_db": "_users" }, "couchdb_engines": { "couch": "couch_bt_engine" }, "couchdb": { "database_dir": "./data", "max_document_size": "50000000", "single_node": "true", "uuid": "dd1b2836284650121a15b2eaa4c2ffe7", "view_index_dir": "./data" } }
2023/6/22 上午9:53:58->Checking configuration failed
2023/6/22 上午9:53:58->TypeError:checkResultDiv.replaceChildren is not a function

**Comment by xktder** [comment]
This is the information for devtool debugging.
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/5451557b-be0d-4f33-a137-e5e3a0293dda)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/4e908041-51d6-4d07-b53c-ecac2dac2edd)

**Comment by vrtmrz** [comment]
Thank you for opening this issue! 
I think that the error is not the direct reason for the synchronisation problem. However, it could indicate that the browser which hosts your Obsidian is a bit older. 
I am ashamed to say that I don't know much about Hongmeng, But could you please check the WebView version, if it is based on Android? It could be shown by evaluating `navigator.appVersion` on the console of DevTool.
And, is there some other error shown on any point in the following procedure?
1. Creating a new note
2. Type something
3. Save
4. Replicate

My guess is that either the hash value calculation when storing the notes or the encryption may have failed when replicating.

**Comment by xktder** [comment]
非常感谢您百忙之中帮忙回复，谢谢。
按照您给的提示，我发现有个webview的选项可以选择。其中我的手机自带的google webview的版本比huawei webview的版本低些，我重新选择huawei选项后，livesync的上传功能正常了。
再次感谢您开发如此优秀的插件。谢谢。
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/4b0659a0-1392-42a7-a1a3-2b3f6791ac84)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/fac9b76e-e256-4e0f-a7ec-755b49214565)

**Comment by vrtmrz** [comment]
I am so relieved to hear that! 
And so thank you for the investigation and the information. This conversation will help all Huawei users.
