### ISSUE TITLE
Moved note is not deleted from Remote DB

### ISSUE THREAD

**Issue by butaixianran** [vrtmrz/obsidian-livesync#24]
Try this:
1. Set sync when: Startup, Open note and save note.
2. Create a note, for example: note001, save it.
3. Change note name to note002, write something in it, save it, then move it to another folder.
4. Close Obsidian.
5. Restart Obsidian, now, you got:
* a note named note001 under root, 
* a note name note002 under root  
* and a note under your folder name note002.

See, you get 3 notes, but it should be one. Seems this plugin does not delete those notes who changed name or moved to another folder from remote DB.

IBM cloud is used in this case.

**Comment by vrtmrz** [comment]
Thank you for reporting this issue! 

It reproduced.

If the plugin waiting for the first replication after startup or processing something heavy job (e.g. plugin boot-up sequence), reflecting the local database from vault change is delayed for these job has been completed.

In this situation, closing Obsidian would be left the old file in the database.
(After the next boot, the new file will be saved automatically again. So you don't lose the file.)

**Comment by vrtmrz** [comment]
@butaixianran 
Thank you for your information.
I fixed the plugin's behavior of updating the database.
I'm not sure that these fixes resolve this issue directly, but could you please check it again too?

**Comment by butaixianran** [comment]
well, here is the case:
After I change file name and move it, if I close Obsidian immediately, when I open it, it comes with 3 files.
But, if I wait some time before I close Obsidian,  there is no problem after I re-open Obsidian.

**Comment by vrtmrz** [comment]
@butaixianran 

I'm really sorry for the delay. I tried several workarounds, but none of them reasonably solved this problem.
So we have added a new feature to let you know how many processes are currently pending.
When you delete or rename a file, please wait until all pending processes are finished.

Does this feature solve your problem?

**Comment by butaixianran** [comment]
That could be helpful.
