### ISSUE TITLE
Keep getting conflict from log created by Make.md plugin

### ISSUE THREAD

**Issue by thucngyyen** [vrtmrz/obsidian-livesync#240]
- I have Make.md install with obsidian-livesync, Make.md create Context/spacesLastSync.log file and everytime I make any change, I keep getting conflict in this file. Does anyone know what happen here?

**Comment by vrtmrz** [comment]
Thank you for opening this issue!
I am afraid to be less familiar with the Make.md, does the file `spacesLastSync` should be synchronised?
If the file controls that synchronising status, or should be handled on each device, perhaps this should be ignored. Ignoring files can be configured at `Regular expression to ignore files` on the `Sync Settings` pane.

**Comment by thucngyyen** [comment]
I asked Make.md maintainer and this is what they say about the file "The file helps keep track of the sync status of the Spaces database". So I think it doesn't have to be sync. Let me try ignoring this file. Thank you for your help!
