### ISSUE TITLE
New folder is not synchronized between different devices.

### ISSUE THREAD

**Issue by butaixianran** [vrtmrz/obsidian-livesync#25]
Try this:
* set all devices' sync to when: obsidian started and note saved.
* Open Obsidian from desktop.
* Create a new folder, for example folder01. create a note under this folder and put something into this note, and save this note.
* Open Obsidian from mobile, folder01 and its note are not there.

**Comment by butaixianran** [comment]
Well, I figure out the problem. 
Folders and files are acturally synchronized, just do not showed in notion list. 

Because there're some conflicts happened on other files. So, there is a window pop out, ask user how to handle these conflicts.

**The problem is: this window is behind the main Obsidian window, so, you may never gonna see it, especially on mobile.**

**Before you handled with this window, new folder and note will never display in note list, even if they are already downloaded to your vault. But since you can't see this window on mobile, you never gonna have a chance to handle it.**

The solution here is: Set "Use newer file if conflicted(beta)" to On. Then you won't has this problem any more.

Better set this option to On as default, even it is still on beta.

**Comment by vrtmrz** [comment]
Thank you for informing me!
It's something wrong, but showing dialog is the standard function of Obsidian.
May I ask your Obsidian's version?

And perhaps we require the feature that "Show docs that having conflictions".
(If you know the file that you chose "Not now", the dialog will be shown when you pick the file again.)

**Comment by butaixianran** [comment]
Obsidian is the latest. Version: 0.12.19

I don't know about "Show docs that having conflictions", for now, turn on "Use newer file if conflicted(beta)" is fine to me.

**Comment by vrtmrz** [comment]
@butaixianran 
Thank you for your information.
I fixed the plugin's some issues about the conflict resolving dialog.

I'm not sure that these fixes resolve this issue directly, but could you please check it again?

And "Resolve if conflicted" menu has been added.

**Comment by butaixianran** [comment]
This issue is fixed, you can close it now.

**Comment by vrtmrz** [comment]
Thanks a lot!
