### ISSUE TITLE
After sync, device folders show up in obsidian, "ix::" prefix

### ISSUE THREAD

**Issue by fritzcloud** [vrtmrz/obsidian-livesync#252]
I am on fedora linux, obsidian from flatpak, latest version. I copied my setup URL and set it up as a subsequent device. It synced everything perfectly, but these folder still show up:

![Pasted image](https://github.com/vrtmrz/obsidian-livesync/assets/26656736/3d6cc04c-0113-434f-b6ce-30a70469cec9)

I think a similar thing happened before: https://github.com/vrtmrz/obsidian-livesync/issues/206

Thank you!

**Comment by vrtmrz** [comment]
Thank you for the report! The reason has been exactly as you mentioned. 
However, allowing `:` in filenames is a Linux-specific behaviour, designed as the loosest pattern in some of the file systems I referenced.  I felt it was a bit too broad for Obsidian to handle, so I decided to ignore files containing `:`; back in the first place.
v0.19.17 contains this change. Could you please check the behaviour?

**Comment by fritzcloud** [comment]
Perfect, that worked, thank you for the quick fix!
