### ISSUE TITLE
"The file that having platform dependent name has been arrived." - if Apostrophe Present

### ISSUE THREAD

**Issue by kwjfef** [vrtmrz/obsidian-livesync#27]
Similar to #21, in the latest release (0.2.0) the same occurs if there are apostrophes ' in the file name.

In addition, once the file name has been changed (e.g., from "Jennifer's Story - One.md" to "Jennifers Story - One.md") to allow for syncing, a notification will remain persistent on start-up.

"The file that having platform dependent name has been arrived. This file has skipped: Jennifer's Story - One.md"
This is despite the file name having been corrected and the file already syncing correctly.

**Comment by vrtmrz** [comment]
Thank you for notifying this! 
Reproduced. 
You're right, caused by the same reason.
And I figured out I missed one more letter.
I'll fix it soon.

**Comment by vrtmrz** [comment]
I think it is solved. If any problems are left, please reopen.
