### ISSUE TITLE
Settings Clarity, Rephrasing & Typos

### ISSUE THREAD

**Issue by ghost** [vrtmrz/obsidian-livesync#28]
#### Below are a few examples and how they could be improved:
---
  ![remote config](https://user-images.githubusercontent.com/94068456/146999139-ec37610b-d587-49e8-95c9-cd034e3bb325.png)
  **"These settings are kept locked while synchronisation is in progress."**

![empty folders](https://user-images.githubusercontent.com/94068456/146999290-ff229c4c-0131-41ee-8831-07b60bc6c8fc.png)
**"Enabled - empty folders stored locally are synced to the remote database.
Disabled - empty folders stored locally are not synced to the remote database, and those that become empty on another device will not sync to other devices."**

![corrupted data](https://user-images.githubusercontent.com/94068456/146999613-09c29e5b-6b4f-4527-93ac-21f25f06c918.png)
**"There is no corrupted data."**

---

I would like to also point out, though, that I very much like the new settings layout. It is far more organised and structured compared that of earlier releases. This combined with improvements to the text will make the plugin far easier to use.

If you'd like any help with re-writing anything, including anything in the docs, I'd be more than happy to help!

**Comment by vrtmrz** [comment]
Very very thank you for your check! Actually, I'm not so good at English writing.
Please feel free to let me know if it is strange or difficult to understand.

This is a big chance to improve this plugin and my English :)
Reading is not so bad, so if there's something misunderstanding in each other, I will explain.

Of course, any pull requests are welcome too.

First, I'll brush the plugin up like this issue.

**Comment by vrtmrz** [comment]
@kwjfef I wrote some ideas, to add a little detail. Could you check it?

> "These settings are kept locked while synchronisation is in progress."

"These settings are kept locked while you turn on any automatic synchronization." is ok?
(Yes, you have a good point. I have to lock this setting while synchronization is in progress, in addition to current behavior.)
So, finally, this note would be like this? : "These settings are kept locked while you turn on any automatic synchronization or in progress."

> "Enabled - empty folders stored locally are synced to the remote database.
> Disabled - empty folders stored locally are not synced to the remote database, and those that become empty on another device will not sync to other devices."

How is the below?
Disabled - Delete the folder if it becomes empty by replication.
Enabled - Do nothing to the folder, even if replication has deleted any files.

**Comment by kwjfef** [comment]
> **I'm not so good at English writing.**

No worries, you've done a great job so far! It's just a case of fixing minor grammatical errors now.

> **"These settings are kept locked while you turn on any automatic synchronization or in progress."**

The addition of "automatic" I think is better than my initial suggestion, as automatic implies that there are settings enabled causing replication to take place whenever an edit is made. As this isn't happening at all times, I feel that "in progress" becomes redundant.
It might be better to rephrase this instead as:
**"These settings are kept locked while automatic synchronisation options are enabled. Disable these options in the "Sync Settings" tab to unlock."**

> **"Disabled - Delete the folder if it becomes empty by replication.
Enabled - Do nothing to the folder, even if replication has deleted any files."**

This suggests that if a folder is detected as empty during replication, it will be deleted from both the local vault as well as the remote vault if the setting is disabled, which isn't the case as the folder is still kept intact locally.
I think it is important to specify this as the setting can be changed per device.
Please correct me if I'm misunderstanding the role of this setting, but from my testing, this is what I've found it does.

**Comment by vrtmrz** [comment]
Thank you for your kindness! I'm very encouraged!

> "These settings are kept locked while automatic synchronisation options are enabled. Disable these options in the "Sync Settings" tab to unlock."
This is awesome! Thank you!

> which isn't the case as the folder is still kept intact locally.
Oh... really? I think it is a problem.
I'll investigate more.

**Comment by vrtmrz** [comment]
Close this issue once.
