### ISSUE TITLE
Always prompts that the database needs to be encrypted

### ISSUE THREAD

**Issue by appdev** [vrtmrz/obsidian-livesync#29]
I'm not sure if this encryption is necessary? I have turned off end-to-end encryption。

Although it still prompts frequently, it can be successfully synchronized

![image](https://user-images.githubusercontent.com/9107717/147304346-8c4b2f5c-110a-4b0b-9518-6e1925d077dd.png)

![image](https://user-images.githubusercontent.com/9107717/147304491-59677a24-120e-4a0a-bfdc-afd5f0a7ea0a.png)

**Comment by appdev** [comment]
I'm using my own server and I don't know if this has an impact.

**Comment by vrtmrz** [comment]
Thank you for using this plugin! 
Encryption is not required if you don't want to synchronize the installed plugin.
But if you want to synchronize the plugin and these settings, encryption is required. Some plugins' configuration contains credentials for their servers. (e.g. Self-hosted LiveSync, LanguageTools)

If you don't mind that not using plugin synchronization, turn off "Enable plugin synchronization." in "Plugins and settings"

**Comment by appdev** [comment]
Thanks, I thought it might be better to put this description in the tips

**Comment by vrtmrz** [comment]
You're welcome! I'll write this into the descriptions of plugins and settings synchronization.
