### ISSUE TITLE
Recovery procedure, start from scratch

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#30]
Some combination of vault refactorings (file deletes and renames) and probably delayed plugin updates on my mobile device has led to a situation where my "main vault" on the PC gets pretty much polluted by changes I had made days ago. Prior to that, I had error messages like "something went wrong on reading elements of ..." etc. and I tried to reset from the mobile side with "Reset local database". In short, I seem to have produced a mess.

What is the best recovery procedure from this? I'm basically prepared to wipe everything (including the remote DB) and start from scratch from a vault as recovered from filesystem backup, but I don't understand the concept for the local database, how do I effectively wipe that? It seems that with the plugin active, it starts to "do something" (i.e. in my case recreating files which were either deleted or moved days ago) as soon as I start Obsidian and the plugin is active.

Also, I don't quite understand the warning on the INITIALIZE button in the settings, in particular the last part "remote data will be merged or corrupted"...

**Comment by arminus** [comment]
OK, this is really getting painful now.

So I wiped everything (I think): Restored the broken Vault form backup, deleted the plugin, reinstalled it - the remote DB should no longer play a role at this stage, I wiped CouchDB's data dir for the docker container just to be on the safe side. However, as soon as I activate the plugin on the "clean" vault" again, it pumps out heaps of "something went wrong on reading elements of ... from database" and pulls in files which had either been deleted or moved into som other folder in the past. There's no way to recover from this, because this happens right after activating the plugin and from then on, my vault is "broken".

So: Where does the plugin store its local DB so that I can manually wipe or delete that, too - before re-activating the plugin?

**Comment by arminus** [comment]
Ok, figured that one out: Obsidian's Electron Dev Tools -> Application -> Storage -> IndexedDB -> _pouch_Obsidian-livesync -> Delete.

Reinstall, DB is really rebuilt from the Vault now.

**Comment by vrtmrz** [comment]
I'm really sorry for being late to respond to this big problem,  
I think you may had been in chaos.

The steps that your figured out
> Ok, figured that one out: Obsidian's Electron Dev Tools -> Application -> Storage -> IndexedDB -> _pouch_Obsidian-livesync -> Delete.

is "Reset local database". 

"Local Database" is the PouchDB's database that creates in the Obsidian's indexed DB locally.
Sorry for the ambiguous word.

The simple way you don't want to completely drop the history, press "Verify and repair" from every device.
1. If doesn't solve at once, try this 2 or 3 times:
	1. Try in all device
		1. Press "Verify and repair".
		2. Replicate.
2. Maybe some docs are still corrupted, it does not exist in all devices. Please delete these database entries from the ambulance icon.

The most simple restructuring procedure is as below:
1. Stop all synchronization in all devices.
2. Press "Drop and Send" from the main device.
3. Wait for a while till the plugin says "done".
4. Press "Drop and receive" on other devices.

Or manually like below:
1. Stop all synchronization in all devices.
2. From the main device.
	1. Lock remote database.
	2. Reset remote database.
	3. Initialize the local database again.
	4. Replicate once.
3. From another device.
	1. Reset local database.
	2. Unlock the remote device with the device.
	3. Replicate

And, **The spec making this issue as serious is bootup database reconstruction**. LiveSync checks the internal stats and tries to resolve the differences: Assuming the filesystem changed while obsidian didn't run, or the vault was temporarily non-writable, or  LiveSync hanged and files and it's stored in LocalDatabase has been different. in this phase, you saw the heap of messages.

I'll note this into the docs. but we may need the "See the reference" button or grouping the buttons as like below:
- Not so dangerous button. like "Open the hood" in the car  (i.e. "Verify and repair" button). 
- Dangerous button, like "Stop engine now and extinguish the fire" in the car (i.e. "Initialize local database" button)

**Comment by arminus** [comment]
Thanks for the thorough explanation. 

The basic problem IMHO was that due to my settings, as soon as I started Obsidian, your plugin started to recreate previously deleted or moved files from the local PouchDB. I still don't understand why it did that. I do understand you need that in order for the replication to work with the remote CouchDB - but the downside seems to be that it can create weird situations. Maybe in conjunction with interrupted syncs? (i.e. Obsidian being shut down while some sync was still running ?).

At any rate, IMHO the combination of local file store, local PouchDB (a kind of cache), CouchDB, remote PouchDB, remote file store, in conjunction with quite some settings may lead to possible fault scenarios for which I'd probably need a huge diagram to fully comprehend technically.

From a pure user perspective, though: In a recovery scenario, I should consider one vault in its file system representation on a given device to be the one and only master/single source of truth. I think it would be helpful to have some "re-initialize" flag, probably to be added/edited directly in your plugin's data.json (so that "normal" Obsidian start up doesn't trigger anything else).

With this flag being active, everything would be completely re-initialized and pushed downstream from the local vault. With the steps you listed above, I still see something "undesirable" still going on in the background after startup until you had the chance to actually "click the buttons" - at least based on my experience.

Also, concerning the side-effects of unintended interrupted synchronizations: I don't know if Obsidian allows to hook into the shutdown process so that you could warn the user if a sync is still running and then delay the shutdown until the sync has finished?

At any rate, I have now switched off all auto-sync and will sync only manually and keep a careful eye on the sync log.

**Comment by vrtmrz** [comment]
You're right, we need the feature to suspend the bootup sequence.
But editing data.json is so hard in iOS.
Instead of that, I'm making a new feature that suspends bootup synchronization local database and file system if `checkerflag.md` is on the root of the vault.
It would be useful.

**Comment by vrtmrz** [comment]
I apologize for the hasty reply.

> At any rate, IMHO the combination of local file store, local PouchDB (a kind of cache), CouchDB, remote PouchDB, remote file store, in conjunction with quite some settings may lead to possible fault scenarios for which I'd probably need a huge diagram to fully comprehend technically. 

This could be [this diagram](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/tech_info.md)?

<img src='https://github.com/vrtmrz/obsidian-livesync/raw/main/images/1.png' width='600'> and 
<img src='https://github.com/vrtmrz/obsidian-livesync/raw/main/images/2.png' width='600'>.

And at the version 0.4.0, I implemented `redflag.md` feature.
If `redflag.md` is placed in the Vault, the plugin will not perform the startup sequence and stops watching vault changing. So we can press the buttons calmly.
This should help us in the future.

**Comment by vrtmrz** [comment]
@arminus 
Is this problem solved by "redflag.md" ?

**Comment by arminus** [comment]
I can confirm that the presence of redflag.md in the root dir of the vault blocks any sync attempts.
