### ISSUE TITLE
obsidian-livesync 0.20.4 restarts constantly on iPhone

### ISSUE THREAD

**Issue by ZhXWei** [vrtmrz/obsidian-livesync#304]
obsidian-livesync 0.20.4 restarts constantly on iPhone during enumeration while using Obsidian 1.4.16, iOS version is 17, and the device is iPhone 12.

**Comment by vrtmrz** [comment]
Thank you for opening this issue!

On my iPhone, it does not restart so often, however, I have heard some similar issues. I still wonder what happened with iOS, but I hope to resolve this.
One possibility, v0.20.4 has a bug about enumerating files on the database. This problem caused a lot of database access or network access. This could be one reason for restarting.
Today, I released v0.20.5 and the bug has been resolved. 

Could you please check this version and whether the problem has gotten better?

And if it still exists(Unfortunately, it might be). Please let me see [the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report) for better troubleshooting.

**Comment by ZhXWei** [comment]
Thank you for your prompt response and issue resolution. The problem has not recurred and the real-time synchronization is still being tested,There are multiple terminal devices involved. so I really appreciate your help.

**Comment by vrtmrz** [comment]
I am so glad to hear that and my work seems effective! thank you for your testing!
If you think that this has been enough fixed, please close the issue!
