### ISSUE TITLE
What constitutes a completed sync?

### ISSUE THREAD

**Issue by rakugakijin** [vrtmrz/obsidian-livesync#31]
Is it the file size? Or is it the update date?
1. In the morning, I start writing my daily notes on my iPhone obsidian. I go to work and write on my iPhone until I get home. 2.
When I get home, I start up obsidian on my computer, and it creates a daily note with only today's templates.
I'd like the daily note created in 1 to remain, but if it's just the update time, the brand new daily note in 2 will be chosen.
When the software can't decide, it asks me which of the two files I want to choose, sometimes it asks and sometimes it doesn't. I was scared to use the PC side of the daily note.
I'm too scared to open the Daily Note on the PC side.

**Comment by vrtmrz** [comment]
Each document has revisions and hash. If the revision can be connected, its means these docs are made from one so can be merged. 
If some device has continuous revisions, these changes are merged into one tree automatically in the replication.

This is the case of `r2a` to `r4a`
```
  ,--> r2a -> r3a -> r4a
r1 --> r2b -> r3b
  `--> r2c -> r3c
```

But the initial hash of the documents does not match (even if the name is the same), LiveSync and replication treat these docs differently. It won't merge automatically (In the design.)

This case:
```
r1 --> r2a -> r3a

s1 --> s2a -> s2a
```

If you sync the daily note from both devices, replication saves the conflicted docs as-is into the local database. (was in the design.).
(And, If you do not set "Use newer file if conflicted")
And, You can see the merge dialog, when Self-hosted LiveSync detects the doc has a different revision in synchronization, or you run "Resolve if conflicted" (you can use this feature in the menu in Ctrl+P) manually.

So, what the "complete" of the synchronization is, as below:
"All documents that hadn't been deleted are collected."

If the actual behavior is not correct to my explanation, could you please notify me of the reproducing step and show me the log if you can?

**Comment by vrtmrz** [comment]
Did you get your questions answered?
I'm going to close the Issue once. But if you have any problems, please re-open it.
