### ISSUE TITLE
upgrade to V0.20.6 occur "DB -> STORAGE(create,plain) ERROR, could not write"

### ISSUE THREAD

**Issue by xktder** [vrtmrz/obsidian-livesync#317]
## problem

After I upgrade to V0.20.6，Computer and phone synchronization occur "DB -> STORAGE(create,plain) ERROR, could not write"

![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/6827d93c-56b6-40a9-a80e-9c70cb51bc2c)

## version
V0.20.6

**Comment by xktder** [comment]
## maybe
It may be related to this reason, as it indicates that there are two Database folders, but there is actually only one Database folder, and lowercase databases do not have this folder.

![89)GSLG8 1`QKUTCIH~EA@H](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/35b1d4f7-81e8-4da0-89b0-f443ef685ce6)

![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/af76b357-098e-4153-b5f0-c8403c467efc)

**Comment by xktder** [comment]
## difficult problem

### Expected results
I originally intended to reset the entire local synchronization record and then pull the remote library information again. Local data is no longer needed, and remote data is directly used to overwrite the local data. I have tried various methods of plugins.


### final
My remote library is broken and uncomfortable.

### cause
I did the following:
- 1、Discard the existing configuration and set up​.
- 2、Uninstalled plugin.
- 3、Exit program obsidian.
- 4、Download the livesync plugin again.
- 5、Ensure that the synchronization address is invalid.
- 6、But he experienced the phenomenon of pulling remote data. I don't know, why can he pull data without any remote library address configuration? And I still unload the overloaded livesync, so it should not be able to pull any data.

## why?
I tried
- Discard the existing configuration and set up
- Do not discard the existing configuration and set up again
- Fetch rebuilt DB
- Discard local database to reset or uninstall Self-hosted LiveSync
There is no operation that can help me completely empty the local.


![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/6a166681-0b51-4eba-b55b-962665966f56)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/da831e03-2eb6-42e6-9df4-6b35477458bc)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/068343d3-72a8-47da-af3a-f77db1747721)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/6f76d242-c1ef-4a18-b504-6b286b028839)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/50117187-8fa6-4f86-8505-5816835f6825)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/106290226/a5b82fa9-f053-4672-8731-d9e86eb04ce9)

**Comment by dlphnkck** [comment]
I'm sorry to bother you. 
I am not at all familiar with the LiveSync plugin, but is "Redflag.md" relevant? If not, I'm sorry.

[obsidian\-livesync/README\.md at 280d9e1dd9e7c9cdc6991b7399584294bd34300d · vrtmrz/obsidian\-livesync](https://github.com/vrtmrz/obsidian-livesync/blob/280d9e1dd9e7c9cdc6991b7399584294bd34300d/README.md)
> - To stop the boot-up sequence (eg. for fixing problems on databases), you can put a redflag.md file (or directory) at the root of your vault. Tip for iOS: a redflag directory can be created at the root of the vault using the File application.
> - Also, with redflag2.md placed, we can automatically rebuild both the local and the remote databases during the boot-up sequence. With redflag3.md, we can discard only the local database and fetch from the remote again.

- [Recovery procedure, start from scratch · Issue \#30 · vrtmrz/obsidian\-livesync](https://github.com/vrtmrz/obsidian-livesync/issues/30) (2021)
- [any way to reset local database manually by deleting files on windows? · vrtmrz/obsidian\-livesync · Discussion \#147](https://github.com/vrtmrz/obsidian-livesync/discussions/147) (2022)

**Comment by xktder** [comment]
> 很抱歉打扰您。我完全不熟悉 LiveSync 插件，但“Redflag.md”相关吗？如果没有，我很抱歉。
> 
> [黑曜石-livesync/README.md 在 280d9e1dd9e7c9cdc6991b7399584294bd34300d ·VRTMRZ/黑曜石-LiveSync](https://github.com/vrtmrz/obsidian-livesync/blob/280d9e1dd9e7c9cdc6991b7399584294bd34300d/README.md)
> 
> > * 要停止启动序列（例如，用于修复数据库上的问题），可以将 redflag.md 文件（或目录）放在保管库的根目录下。iOS 提示：可以使用文件应用程序在 Vault 的根目录下创建一个红旗目录。
> > * 此外，放置 redflag2.md 后，我们可以在启动序列中自动重建本地和远程数据库。使用 redflag3.md，我们可以只丢弃本地数据库并再次从远程获取。
> 
> * [恢复过程，从头开始 ·期刊 #30 ·VRTMRZ/黑曜石实时同步](https://github.com/vrtmrz/obsidian-livesync/issues/30) （2021）
> * [有什么方法可以通过删除Windows上的文件来手动重置本地数据库吗？ · VRTMRZ/黑曜石直播同步 ·讨论 #147](https://github.com/vrtmrz/obsidian-livesync/discussions/147) （2022）

Thank you for your reply. It's my problem and I haven't read the existing materials carefully. I will continue to try again.

**Comment by vrtmrz** [comment]
Sorry for being late! 
Strange behaviour when remote data vaults contain mixed-case files. This is due a specification trouble. I am sorry to make you inconvenient. 
I am very annoyed about this. We could make `/Database/` and `/database/` if on Linux or iOS, but could not on Windows.
So we could not merge `/Database/` and `/database/` by unified simple logic. (In other words, there might be some ways, if we could accept overwriting of `aaa.md` changes to `aaA.md` and `Database/aa.md` to `database/aa.md`)

For now, in such cases, this is just a workaround but following instructions may help us.

- Rename the `Database` folder to `Database_` (anything you like) by Windows Explorer
- After the file scan, restart Obsidian
- A `database` folder will be created, and please move its files into the `Database_` folder.
- Wait for the scan, and rename `Database_` back  to `Database`

--- 
Second problem

The file resurrecting problem seems to be caused uncleared local database.
The process which you have done `Discard local database to reset or uninstall Self-hosted LiveSync` does this, but seems to not work in your environment.

As you all mentioned, the `Redflag` series might be helpful for us. We should use `redflag3.md` to discard the local and fetch again. However, some good names might be required. Thank you for your support @dlphnkck!

**Comment by xktder** [comment]
Thank you for your reply.
Rebuild the library to address the first issue.
