### ISSUE TITLE
Should I close obsidian when I'm not using it every day?

### ISSUE THREAD

**Issue by rakugakijin** [vrtmrz/obsidian-livesync#32]
Because of the slow synchronization of livesync, I almost always leave the PC side obsidian running.
The data connection is slow because I use pocket wifi.
Reason 2. obsidian alone uses more than half of the processing power of my PC.

**Comment by vrtmrz** [comment]
Could you try the "Batch database update" and "Periodic Sync"?
This could be useful in narrow bandwidth connections. and uses less CPU power.

You can set the recommended configuration by "Miscellaneous"->"Presets"

![image](https://user-images.githubusercontent.com/45774780/147426950-247580d8-8d7b-4458-9cea-465d56766d54.png)

**Comment by vrtmrz** [comment]
Did you solve the problem?
I'm going to close the Issue once. But if you have any problems, please re-open it.
