### ISSUE TITLE
Is the function "‎Enable plugin synchronization‎" cancelled ?

### ISSUE THREAD

**Issue by zyyfriends** [vrtmrz/obsidian-livesync#324]
I can't find this function in menu .
![image](https://github.com/vrtmrz/obsidian-livesync/assets/42362178/e9770b9f-f118-403e-95c4-a7da2dfe8efd)

**Comment by dlphnkck** [comment]
Hello. Excuse me for interrupting.

## Actually happened & Reproducing procedure
Have you attempted to click the "Open" button?
[Customization sync: allow certain files to be synced without user interaction · Issue \#278 · vrtmrz/obsidian\-livesync](https://github.com/vrtmrz/obsidian-livesync/issues/278#issuecomment-1711175315)

or "Sync Settings" tab->Hidden files->Hidden file synchronization?

## Report materials
Do you have iOS or Android?
What LiveSync plugin version are you using?
Is there any information available under the "Hatch" tab -> "Make report" and "Obsidian debug info" section?

**Comment by vrtmrz** [comment]
Sorry for being late!

`Enable plugin synchronisation` has been just renamed to `Enable Customization Sync`. 
Would you mind if I ask you to try it?

**Comment by zyyfriends** [comment]
thank you all, and I solved the problem with the answer below

> Hello. Excuse me for interrupting.
> 
> ## Actually happened & Reproducing procedure
> Have you attempted to click the "Open" button? [Customization sync: allow certain files to be synced without user interaction · Issue #278 · vrtmrz/obsidian-livesync](https://github.com/vrtmrz/obsidian-livesync/issues/278#issuecomment-1711175315)
> 
> or "Sync Settings" tab->Hidden files->Hidden file synchronization?
> 
> ## Report materials
> Do you have iOS or Android? What LiveSync plugin version are you using? Is there any information available under the "Hatch" tab -> "Make report" and "Obsidian debug info" section?

**Comment by vrtmrz** [comment]
Indeed! Thanks for your daily contribution, @dlphnkck !
