### ISSUE TITLE
bug：I didn't even input the plugin settings, so it automatically synced

### ISSUE THREAD

**Issue by ingxhe** [vrtmrz/obsidian-livesync#326]
I didn't even input the plugin settings, so it automatically synced

**Comment by ingxhe** [comment]
![image](https://github.com/vrtmrz/obsidian-livesync/assets/30750321/1c90505c-94e5-4329-affc-9fe512aa19a5)

**Comment by ingxhe** [comment]
why？？？？？？？？？？？？？？？？？？？？？

**Comment by ingxhe** [comment]
It may be a local database. I understand

**Comment by vrtmrz** [comment]
Thank you for your notice!
I suspect you were so much surprised when the files suddenly appeared. The situation would be as you realised. 
If I may explain a little intrusively furthermore, if we want to use the same vault name, we can set a `Database suffix` to avoid this.
