### ISSUE TITLE
get cors when i use docker to set couchdb

### ISSUE THREAD

**Issue by lin0kin** [vrtmrz/obsidian-livesync#33]
sorry to bother, when i test it on docker, i get this :

<img width="423" alt="Snipaste_2021-12-26_01-08-32" src="https://user-images.githubusercontent.com/30078096/147390029-81087052-593d-4faa-9dc3-27f2f202562d.png">

i need nginx to solve cors problem or something i miss?

thx

**Comment by arminus** [comment]
I think you need an https connection to start with. See [this repo](https://github.com/vrtmrz/self-hosted-livesync-server) for sample docker-compose files.

**Comment by lin0kin** [comment]
> I think you need an https connection to start with. See [this repo](https://github.com/vrtmrz/self-hosted-livesync-server) for sample docker-compose files.

i understand. thanks for reply
Is there a way to use http?

**Comment by vrtmrz** [comment]
If you're using from only PC, HTTPS is not required, 
But CORS setting is always required. 

Your CouchDB looks like less the configuration. 
Could you please check the sample `local.ini`?
https://github.com/vrtmrz/self-hosted-livesync-server/blob/a4deee3eccf18ae26a91349231bb84b6c9c46fa3/conf/local.ini#L15-L20

**Comment by lin0kin** [comment]
> If you're using from only PC, HTTPS is not required, But CORS setting is always required.
> 
> Your CouchDB looks like less the configuration. Could you please check the sample `local.ini`? https://github.com/vrtmrz/self-hosted-livesync-server/blob/a4deee3eccf18ae26a91349231bb84b6c9c46fa3/conf/local.ini#L15-L20

yeah, iuse it on ipad.

i will learn https to solve it.

thx bro
