### ISSUE TITLE
Database does not get fetched on ios, but sync works for linux and macos

### ISSUE THREAD

**Issue by 9WooPWooP8** [vrtmrz/obsidian-livesync#335]
## Abstract
Unable to sync ios with self hosted couchdb, even though sync works for linux and macos.

## Expected behaviour
- remote database gets installed to iphone

## Actually happened
- The connection to the database seems to be fine. Connection check results in success.
- OneShot sync begins, but no files appear to be pulled.
- "Looking for the point last synchronized point message" gets logged, nothing happens after that.
- When clicking replication button, message shows that replication is already in progress

## Reproducing procedure

1. Press fetch and replace local db button on ios.

### Report from the LiveSync
[gist](https://gist.github.com/9WooPWooP8/a4031edfe5ecf61dc13a49943db30648)

### Plug-in log

<details>
<summary>Plug-in log</summary>
Uu:23/11/2023, 19:19:04->Hidden files and plugin synchronization have been temporarily disabled. Please enable them after the fetching, if you need them.
Uu:23/11/2023, 19:19:04->All synchronization have been temporarily disabled. Please enable them after the fetching, if you need them.

Uu:23/11/2023, 19:19:06->Hidden files and plugin synchronization have been temporarily disabled. Please enable them after the fetching, if you need them.
Uu:23/11/2023, 19:19:06->Suspending reflection: Database and storage changes will not be reflected in each other until completely finished the fetching.

Uu:23/11/2023, 19:19:06->Database closed for reset Database.
Uu:23/11/2023, 19:19:06->Opening Database..
Uu:23/11/2023, 19:19:06->Database is now ready.
Uu:23/11/2023, 19:19:06->Local Database Reset
Uu:23/11/2023, 19:19:09->Mark this device as 'resolved'.
Uu:23/11/2023, 19:19:10->Database closed (by close)

Uu:23/11/2023, 19:19:10->Waiting for ready...
Uu:23/11/2023, 19:19:10->CompileError:WebAssembly.Module doesn't parse at byte 90: references are not enabled, in function at index 3

Uu:23/11/2023, 19:19:10->Opening Database...
Uu:23/11/2023, 19:19:10->Database is now ready.
Uu:23/11/2023, 19:19:10->OneShot Sync begin... (pullOnly)
Uu:23/11/2023, 19:19:12->Looking for the point last synchronized point.
</details>

**Comment by dlphnkck** [comment]
Hi. I'm a newbie not familiar with the LiveSync plugin, sorry for any extra help.

> Plug-in log 
> Uu:23/11/2023, 19:19:10->CompileError:WebAssembly.Module doesn't parse at byte 90: references are not enabled, in function at index 3

I have never seen this error with the LiveSync plugin.

- Is your CouchDB environment Fly.io or IBM Cloudant?
- Do you enable `Verbose Log`?
- Do you have a Network log? 

Sorry if this is misplaced.

**Comment by 9WooPWooP8** [comment]
Hey!
1) I rent a vps, my CouchDB is running there.
2) verbose log was not enabled.

**Comment by 9WooPWooP8** [comment]
Hey, accidently closed issue, sorry.

1) I rent a vps, my CouchDB is running there. I set up a reverse proxy with nginx using https.
2) Verbose log was not enabled. Here is the verbose version
<details>
<summary>Verbose log</summary>
Uu:26/11/2023, 14:22:49->Cache initialized 300 / 50000000
Uu:26/11/2023, 14:22:49->Hidden files and plugin synchronization have been temporarily disabled. Please enable them after the fetching, if you need them.
Uu:26/11/2023, 14:22:49->Suspending reflection: Database and storage changes will not be reflected in each other until completely finished the fetching.
Uu:26/11/2023, 14:22:49->Cache initialized 300 / 50000000
Uu:26/11/2023, 14:22:49->Database closed for reset Database.
Uu:26/11/2023, 14:22:49->Opening Database...
Uu:26/11/2023, 14:22:49->Database info
Uu:26/11/2023, 14:22:49->{
  "doc_count": 0,
  "update_seq": 0,
  "db_name": "Uu-livesync-v2-indexeddb",
  "auto_compaction": false,
  "adapter": "indexeddb"
}
Uu:26/11/2023, 14:22:49->Database is now ready.
Uu:26/11/2023, 14:22:49->Local Database Reset
Uu:26/11/2023, 14:22:51->Cache initialized 300 / 50000000
Uu:26/11/2023, 14:22:52->Mark this device as 'resolved'.
Uu:26/11/2023, 14:22:52->Database closed (by close)
Uu:26/11/2023, 14:22:52->Waiting for ready...
Uu:26/11/2023, 14:22:52->Cache initialized 10 / 1000000000
Uu:26/11/2023, 14:22:52->Cache initialized 300 / 50000000
Uu:26/11/2023, 14:22:52->Could not initialise xxhash v1
Uu:26/11/2023, 14:22:52->CompileError:WebAssembly.Module doesn't parse at byte 90: references are not enabled, in function at index 3
Uu:26/11/2023, 14:22:52->Opening Database...
Uu:26/11/2023, 14:22:52->Database info
Uu:26/11/2023, 14:22:52->{
  "doc_count": 1,
  "update_seq": 1,
  "db_name": "Uu-livesync-v2-indexeddb",
  "auto_compaction": false,
  "adapter": "indexeddb"
}
Uu:26/11/2023, 14:22:52->Database is now ready.
Uu:26/11/2023, 14:22:53->OneShot Sync begin... (pullOnly)
</details>
3) I'll try to get network log later, if ios update won't help.

About the WebAssembly error, could the reason be old ios version? I have ios 14 installed both on my iphone and ipad, and they have the same issue with livesync. I'll try to update my ipad and restart sync again and will give you an update.

**Comment by 9WooPWooP8** [comment]
It appears that the issue was caused by old ios version. I upgraded to ios 17, sync works perfectly now.
Closing issue.
