### ISSUE TITLE
Automatic setup using Colaboratory fails in generate server step

### ISSUE THREAD

**Issue by haak** [vrtmrz/obsidian-livesync#339]
In [Automatic setup using Colaboratory](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_flyio.md#automatic-setup-using-colaboratory), the following step causes an error.

```
# Generate server
!/root/.fly/bin/flyctl launch  --auto-confirm --generate-name --detach --no-deploy --region ${region}
!/root/.fly/bin/fly volumes create --region ${region} couchdata --size 2 --yes
```
The command expects an answer to y/N question
```
? Do you want to tweak these settings before proceeding? (y/N) 7999;999f6n
```

# Reproducing procedure
Open colab([deploy_couchdb_to_flyio_v2_with_swap.ipynb](https://gist.github.com/vrtmrz/37c3efd7842e49947aaaa7f665e5020a)) and follow instructions until the error occurs.

**Comment by dlphnkck** [comment]
Hi. Is the following relevant?

[The New Launch \- Fresh Produce \- Fly\.io](https://community.fly.io/t/the-new-launch/16490)
> There’s a slight bug in name generation that came from the chaos of getting all this merged. It doesn’t currently pull names from the working directory, and it lies about how it derived the app name it’s using. This will be fixed in v0.1.125

Sorry if this is not relevant.

**Comment by haak** [comment]
I imagine changes made to the fly cli are related

**Comment by hyunki** [comment]
same issue. Cannot skip that question on cli. Every input considered as password.

> I imagine changes made to the fly cli are related

same issue. Cannot skip that question on cli. Every input considered as password.

**Comment by vrtmrz** [comment]
Thank you for opening the issue! It may caused [upstream bug](https://github.com/superfly/flyctl/pull/3046). 
However, it seems not merged yet, and could be so inconvenient, I will address it soon.

**Comment by alichay** [comment]
> Thank you for opening the issue! It may caused [upstream bug](https://github.com/superfly/flyctl/pull/3046).

Hi! Just letting you know this finally got merged :)

**Comment by vrtmrz** [comment]
@alichay 
Thank you for letting us know!
And while we were waiting for it, a brand new fully automatic set-up was also available. Sorry that I have missed announcing this to this thread!
I hope to close the issue once by this [Setup CouchDB on fly.io](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_flyio.md). Feel free to reopen this issue!
