### ISSUE TITLE
can not parse or decrypt configuration uri when open setup url

### ISSUE THREAD

**Issue by dzhl** [vrtmrz/obsidian-livesync#350]
## Abstract
when i open setup url ,it throws "can't not parse or decrypt configuration url"

## Reproducing procedure

i setup corrent connect information in one obsidian and it can connet db,when i want to setup it in another obsidian ,i followed offical guide to use copy url from first obsidian and open setup url,I'm sure the url and password are correct, and the plugin version is the same too，the version is 0.21.5

**Comment by dzhl** [comment]
nobody know to how?

**Comment by vrtmrz** [comment]
Sorry for being late!

I regret to say this but I could not reproduce it.
I have tried the command `Copy the setup URI` (Without anything) and with a simple passphrase `AAAAA`, and it seems OK.

Would you please try like this?

**Comment by MrBlue90** [comment]
@dzhl I was getting the same error.
After a lot of changes and tests, I believe it was due to a missing reverse proxy to the DB (since I was trying to get it working on a mobile device and HTTPS is required)
Also, don't forget to create a new database in CouchDB which you enter in the connection tab.
Hope this helps.

**Comment by dzhl** [comment]
> @dzhl I was getting the same error. After a lot of changes and tests, I believe it was due to a missing reverse proxy to the DB (since I was trying to get it working on a mobile device and HTTPS is required) Also, don't forget to create a new database in CouchDB which you enter in the connection tab. Hope this helps.

What do I need to do? Do I just need to update Docker again?

**Comment by afermar** [comment]
@dzhl I have the same issue, did you solve it?

**Comment by aksagg** [comment]
@dzhl did you resolve this?

**Comment by hawe80** [comment]
Maybe you are misinterpreted the description just like me.
I followed the setup guide and generated the Setup URI like here:

```console
$ export hostname=https://tiles-photograph-routine-groundwater.trycloudflare.com #Point to your vault
$ export database=obsidiannotes #Please change as you like
$ export passphrase=dfsapkdjaskdjasdas #Please change as you like
$ deno run -A https://raw.githubusercontent.com/vrtmrz/obsidian-livesync/main/utils/flyio/generate_setupuri.ts
```
And could not use the Setup URI!

I confused the passphrase to decrypt the database with the passphrase to decrypt the Setup URI. The first one is set with the export command above. The Setup URI Passphrase is hardcoded in generate_setupuri.ts to `welcome`
https://github.com/vrtmrz/obsidian-livesync/blob/e76e7ae8ead5b7bdef18403433615ec2147cd3b7/utils/flyio/generate_setupuri.ts#L176

So even if you export your own passphrase like stated above you have to use `welcome` to decode your Setup URI.

**Comment by vrtmrz** [comment]
Sorry for missing this! I will handle this at #426, please move there.
(In the short answer, at this time, this is the designed behaviour. I would love to explain this).
