### ISSUE TITLE
Huge number of notes (2400) - replication close

### ISSUE THREAD

**Issue by stanthewizzard** [vrtmrz/obsidian-livesync#358]
Hello
begining of sync goes well and then stops

`05/01/2024, 12:03:29->↑5900 (115891) ↓0
05/01/2024, 12:03:32->↑5902 (115889) ↓0
05/01/2024, 12:03:33->Replication closed
05/01/2024, 12:03:34->↑5938 (115853) ↓0
05/01/2024, 13:37:35->OneShot Sync begin... (sync)
05/01/2024, 13:37:36->Looking for the point last synchronized point.
05/01/2024, 13:37:36->Replication activated
05/01/2024, 13:37:37->↑50 (115796) ↓0
05/01/2024, 13:37:40->↑51 (115795) ↓0
05/01/2024, 13:37:41->↑68 (115778) ↓0
05/01/2024, 13:37:43->↑100 (115746) ↓0
05/01/2024, 13:37:47->↑102 (115744) ↓0
05/01/2024, 13:37:51->Replication closed
05/01/2024, 13:37:52->↑103 (115743) ↓0`

I missing a lot of notes ...

Thanks for help

**Comment by dlphnkck** [comment]
The situation is unfortunate.

1. Is it reproducible?

- Or is it out of memory on the CouchDB server side?
- Volume usage is at 100%,
- iCloud Drive is being used. 
- etc.

2. Please provide additional information about your environment.

In reference to [New Issue inquiry? · vrtmrz/obsidian-livesync · Discussion #327](https://github.com/vrtmrz/obsidian-livesync/discussions/327), etc.
This will encourage more people to respond. It may increase the number of people willing to respond.

That is all. I wish you good luck.

**Comment by stanthewizzard** [comment]
docker	-	obsidian-livesync	running	12 hours	
CPU 0,2	
MEM 1.55G
DISK 138G used on	165G available

no icloud drive used (on windows for testing)

Photon os latest

Compose
`version: "2.1"
services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=zzzzzzzzzzzzzzzzzzzzzzzz
      - COUCHDB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 9584:5984
    restart: unless-stopped`

local.ini

`[couchdb]
single_node=true
max_document_size = 50000000

[chttpd]
require_valid_user = true
max_http_request_size = 4294967296

[chttpd_auth]
require_valid_user = true
authentication_redirect = /_utils/session.html

[httpd]
WWW-Authenticate = Basic realm="couchdb"
bind_address = 0.0.0.0
enable_cors = true

[cors]
origins = app://obsidian.md,capacitor://localhost,http://localhost
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET,PUT,POST,HEAD,DELETE
max_age = 3600`

**Comment by vrtmrz** [comment]
Thank you for opening this issue!
At first sight, I was very surprised to see that there was a tremendous number of chunks waiting to be sent.
May I ask the total file size of your vault? 

And, If you have not configured an enhancing chunk size, please try setting 'Enhance chunk size' to 100 and rebuild the databases once. It works to reduce the number of chunks to 1/100.
To rebuild both databases,  we can place 'redflag3.md' on top of the vault (which has the fine notes and is backed up), and restart obsidian, instead of using 'Hatch'. 

I hope that this information will work for us.

**Comment by stanthewizzard** [comment]
2gb I already worked with the chunks

**Comment by vrtmrz** [comment]
I am so relieved to hear that! Sorry that your confusion had not been solved earlier! 
I close this issue. Thank you for your patience!
