### ISSUE TITLE
Storing content directly into CouchDB

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#36]
In order to be able to send links from a mobile device directly into Obsidian, I currently run a Telegram bot which reads a defined .md file from my Vault on a Nextcloud Share and appends the received link (or text for that matter) to the .md file. There was some interest in this on the Obsidian forum as well if I remember correctly - and the objective here is not web clipping (so no competition here ;-) but just link storing.

Since we now have a CouchDB server with an API, I'd like to get rid of the "Nextcloud detour" and store links received via Telegram (or in the future maybe some other messaging means) directly into my CouchDB instance.

So if I understand https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/tech_info.md correctly, I would need to
- retrieve the defined doc for the to be stored link
- create a new child id 
  - here's question 1: what's the approach to generate a new unique id like h:de31526b0 ? using the couchdb Python library I get an ID like 02e38e5427c1f16e4ffc8bfb25008661 for a new document - and that clearly isn't compliant to the kind of IDs being used by livesync
- append that ID to the children list of the defined doc and save that
- on the next sync, my vault would be updated with this change

Is there anything else I would need to take care of for this to work?

**Comment by vrtmrz** [comment]
Thank you for asking this. CouchDB is so chewy. I'm glad you know it.

If you want to store the note simply to your server's CouchDB. It's so easy.

Self-hosted LiveSync (probably) still supports the primitive format.
This format should be accepted:
```
{
	_id:"filename.md",
	data:"base64_encoded_content",
	ctime:created_time_as_milliseconds,
	mtime:modified_time_as_milliseconds,
	size:filesize_of_the_doc,
	type:"notes"
}
```
If it's not, please inform me.
(Cloudant rejects this if it's over 1MB.)

If you want to append the note, It's as you said :)
Child's _id is generated by crc32 of its contents. But it is just used for dedupe, won't be checked. 
(prefix "h:" is required. The plugin tries to save children as files if it's not.) 
And when the plugin saves the file again, children are regenerated at the phase of splitting into chunks. So, don't worry about this.

And more information, Even if you're encrypting the database and some chunks are not encrypted, it doesn't matter. The plugin just read and then encrypt on save. (the database will contain old and plain one, drop history will be required in not so far someday).

**Comment by arminus** [comment]
Great, thanks a lot for helping me out here!

> CouchDB is so chewy. I'm glad you know it.

Actually not at all, I have worked a bit with MongoDB, CouchDB ist completely new to me ;-)

> Child's _id is generated by crc32 of its contents. But it is just used for dedupe, won't be checked.

Hmmm. With a CRC32 hash, I get an error if I try to insert the same content twice (obviously, the ID already exists), I think I'll better add the current time in ms to the content just for the hash calculation...?

**Comment by vrtmrz** [comment]
You will be soon! So fabulous!

> Hmmm. With a CRC32 hash, I get an error if I try to insert the same content twice

Yes, it will be rejected if ids are conflicted.
But if the hash is the same, the content should also be the same.
In the case of posting chunks, we're able to ignore the error of conflict.

**Comment by arminus** [comment]
Breadboard implementation is working, now I "just" need to wrap and integrate it - will be a couple of days.

I'll probably set this up as an eventually open-sourced, configurable and dockerized service which will host a telegram bot which will then send text to the lifesync-server. Maybe also using other "input" means like Gotify or ntfy.

That should then allow to basically push anything into an Obsidian vault from the outside without Obsidian being open/online.

**Comment by arminus** [comment]
Meanwhile I have a working implementation, will push this to a git repo shortly.

**Comment by vrtmrz** [comment]
I'm glad to hear that! Looking forward to seeing your repo.

**Comment by arminus** [comment]
Ok, here it is: https://github.com/arminus/ObsidianReceiver.git

**Comment by vrtmrz** [comment]
It's very awesome! 
Your code is so smart! I'll try it later!

**Comment by vrtmrz** [comment]
@arminus Hi! I found an important thing, could you check the test code?

**Comment by arminus** [comment]
What exactly did you find? I guess the test fails in your case because the hardcoded target doc (line 9 in test_add2couchdb.py) doesn't exist? -> change that to an existing document and it should work (I'll add that as a comment to the code an in the README)

So far I don't create new documents but simply want to test with this code if the append to an already existing document works ok.

**Comment by vrtmrz** [comment]
If use the consistent checksum for chunks, we don't have to make the chunk always.
Simply check the existence and skip saving if there is.

And are you sure to L.37 of test_add2couchdb.py?

**Comment by arminus** [comment]
> If use the consistent checksum for chunks, we don't have to make the chunk always.
> Simply check the existence and skip saving if there is.

I'm not sure what you mean by that, could you reference what code line(s) you think can be improved? If this is in regards to OBSCouchDB.py:106 - I was wondering what would happen if I would add the same exact text twice and decided to be safe and "salt" the checksum with the current time to avoid duplicate checksums/ids. (but I'm not a CouchDB expert...)

> And are you sure to L.37 of test_add2couchdb.py?

Thanks for spotting this! It'll still be in the git diff, but w/o a password it won't do anyone any good ;-)

**Comment by vrtmrz** [comment]
Sorry for the hasted reply. I thought I have to tell the second topic hurry. 
And if you were want to force-push the repo, referencing blob is kept even if referred repo had been force-pushed.

> I'm not sure what you mean by that, could you reference what code line(s) you think can be improved? If this is in regards to OBSCouchDB.py:106 - I was wondering what would happen if I would add the same exact text twice and decided to be safe and "salt" the checksum with the current time to avoid duplicate checksums/ids. (but I'm not a CouchDB expert...)

It's not only CouchDB's feature but also LiveSync's feature using CouchDB's feature.
But I read the tech_info again, it is almost undocumented, I have to improve this... 
(Just only "KEY IS DETERMINISTIC BY ITS CONTENT. SO, CHUNK WOULDN'T DUPLICATE")

I wrote the sample code.
https://github.com/vrtmrz/ObsidianReceiver/commit/10043036e80a63fbb03b65d828bb0e235e978169

**Comment by arminus** [comment]
Thanks a lot, that looks good to me, please create a pull request.

**Comment by arminus** [comment]
So I think this can be closed. I'd appreciate if you could maybe mention my project somewhere outside the issue tracker? Generally, is it ok to advertise your plugin, e.g. on Reddit /r/ObsidianMD, maybe also the Obsidian plugins forum?

**Comment by vrtmrz** [comment]
Yes, I think so!
I'd love to, If I get a chance :)
And advertising my plugin is always anywhere ok. Thank you!
