### ISSUE TITLE
Deleting sync profiles (customization sync of plugins) efficiently

### ISSUE THREAD

**Issue by xeroc** [vrtmrz/obsidian-livesync#361]
Thanks for this great plugin. What follows is optimization, not bug report, rather a feature request.

## Abstract
In "Customization Sync" dialog, I noticed that I can delete profiles of individual plugins. I would like to do so for *many* plugins since the machine behind a particular profile no longer exists.

## Expected behaviour
Ideally, i could click the trash bin on each one of them one after the other.

## Actually happened
Unfortunately, the entire Modal reloads and starts from the top making this a nightmare when more than 10 plugins are installed.

## Reproducing procedure

1. Go into Customization sync
2. Open the Model with the button at the end
3. Click "Maintenance mode" at the bottom
4. Select a profile on any plugin and click the trash icon
5. The Model reloads and starts from the top

I'd happily run some code in the JS console to assist but don't know enough of the plugin to figure out what to do.

**Comment by vrtmrz** [comment]
Thank you for your idea! Deleting multiple things will be very useful! 
Perhaps the operation will be different, but I will try to make it a bit more efficient.

**Comment by vrtmrz** [comment]
@xeroc 

Hi! Thank you for your daily patience!
Since v0.22.2, we can delete all items of made by a specific device. 
If we put the customisation sync dialogue in maintenance mode, then we will see the `Maintenance Commands` and `Delete All of [      ]`.
Would you mind if I ask you to check the behaviour, please?

**Comment by xeroc** [comment]
Wow, awesome. This was **exactly** what I was looking for. :rocket: :trophy:
