### ISSUE TITLE
The sync notification thing shows up inside the table cell i'm editing

### ISSUE THREAD

**Issue by oofdog** [vrtmrz/obsidian-livesync#366]
## Abstract
The sync notification thing shows up inside the table cell i'm editing

## Expected behaviour

- no notification thing inside the table

## Actually happened
- Synchronisation has been cancelled with the message `TypeError ... ` (captured in the attached log, around LL.10-LL.12)
- No files synchronised

## Reproducing procedure

1. create a table with a few cells
2. start editing the cells
3. when the thing starts syncing, the notification thing shows up inside the cell

### Obsidian debug info
<details>
<summary>Debug info</summary>

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Self-hosted LiveSync v0.22.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
<!-- paste here -->
```
</details>

### Screenshots

![image](https://github.com/vrtmrz/obsidian-livesync/assets/46097282/165df176-77ca-4756-931b-d6609e67fde6)

**Comment by benjwebster** [comment]
Came to report the same issue.

Small gif to show the issue and its behaviour:

![2024-01-25 18 11 30](https://github.com/vrtmrz/obsidian-livesync/assets/18141485/d864232c-9bc5-4ddf-9340-1c4b739c44d4)

**Comment by ebdavison** [comment]
I am also seeing this in tables.  Here is a screenshot.
![2024-01-27_15-01](https://github.com/vrtmrz/obsidian-livesync/assets/549431/77e7f50f-0183-4877-aa05-a48bb6d17dc9)

**Comment by vrtmrz** [comment]
Thank you all for reporting this issue, and for the detailed information with screenshots!
I had not noticed this.

This has been fixed in v0.22.3. Also, the progress indicator and single-line log are now displayed in the new notes pane as well.
May I ask you to check the latest version, please?

**Comment by benjwebster** [comment]
@vrtmrz I can no longer replicate the issue. Thanks for the fix!

**Comment by vrtmrz** [comment]
I am so happy to hear that!
I appreciate all your daily contributions! I close this issue with honour.
