### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by qiang-007** [vrtmrz/obsidian-livesync#38]
When I rename (a→b) a folder on one device, a new folder (b) is created on the other device instead of renaming the old one (a).

**Comment by vrtmrz** [comment]
Sorry for being late.
Please refer #24, if it's the same problem, could you please wait for the hourglass is disappeared?

**Comment by Robertschv** [comment]
@qiang-007 Hey, what does ipv6 have to do with your issue? Can you be more specific?

**Comment by vrtmrz** [comment]
Close this issue once. Feel free to open it again if you have new something.
