### ISSUE TITLE
failed to sync

### ISSUE THREAD

**Issue by clsx524** [vrtmrz/obsidian-livesync#39]
Hello, I am trying this plugin out with self hosted couchdb. obsidian on ipad can successfully connect to my server over https. but when I tried to sync, it would throw error “remote database is newer or corrupted, make sure to latest version of self hosted live sync”. I am  using 0.6.0 plugin and latest couchdb docker image (v3.2.1) from dockerhub. I am passing the local.ini into docker as instructed and also mounted a local directory into docker for data storage. Initially the database is empty and I can see three databases are created, _repricator, _users and obsydian_livesync_version after first connection. Did I miss something or do anything wrong?

**Comment by vrtmrz** [comment]
This message is shown when the plugin tries to synchronize with the CouchDB that once synchronized with the newer version of the plugin.
If you don't synchronize yet, it would be another reason.
Could you please enable the verbose log and capture errors around "remote database is newer or corrupted"?

**Comment by clsx524** [comment]
I found the issue. I didn’t provide the database name in the setting, thinking it would be automatically generated. It now working.
