### ISSUE TITLE
Run replicate now automatically?

### ISSUE THREAD

**Issue by v3i1y** [vrtmrz/obsidian-livesync#398]
I don't know if it's supposed to work this way, but I have to keep clicking replicate now (like a saving mechanism) otherwise the files do not get synced. (I have live sync toggle enabled). Since the "replicate now" button works relatively reliably I wonder if it's possible to just trigger what that button does automatically every second?

**Comment by v3i1y** [comment]
maybe that's what "periodic and on events" sync mode does? 🧐

**Comment by vrtmrz** [comment]
Thank you for opening the issue! As you know, #289 is the same issue. I will address it there! 
Please track it there to get the latest information. Thank you for reporting!
