### ISSUE TITLE
Problems with “?” in document title. 

### ISSUE THREAD

**Issue by OriginHosting** [vrtmrz/obsidian-livesync#4]
Firstly, thank you for writing this plugin. Really great, just what I needed. 

Today, whilst adding a new document, it failed to sync. I presumed a database error so did the usual purge and resync but it didn’t correct the issue. The title was a question, so I removed the question mark and the sync then went through ok. 

I presume there is some issue with syncing titles with special characters in, or something like that, and just wanted to notify you so you were aware. 

Thanks again for all your work on this.

**Comment by vrtmrz** [comment]
Does it fixed? If you have anything else, feel free to reopen.
