### ISSUE TITLE
Cannot sync in Android

### ISSUE THREAD

**Issue by DEAN-Cherry** [vrtmrz/obsidian-livesync#41]
It can work well on my Mac and Windows PC(10 and 11),  but when I turn to an Android device, this plugin cannot detect my files in the database. And when I press the "drop and receive", it just shows  "↑13 ↓0" with no files was downloaded, but the settings I am using are all the same as my Mac and Windows PC. What should I do to get my files in the database? 

It looks well on my PC
![image](https://user-images.githubusercontent.com/76607677/150959975-399cffd5-d07f-424a-8575-ecfb9fcd2f6e.png)

but on my Android, it looks like this.
![Screenshot_20220125-183010_Obsidian](https://user-images.githubusercontent.com/76607677/150960206-29b07574-ba28-46aa-a7e3-8b0051d6b529.jpg)

**Comment by kenjibailly** [comment]
I think it might be a bit buggy, I can confirm that I have already had the entire list on my android phone. But just like above I also had a list where I only saw my mobile plugins that I didn't push.
I explained it more thorough in #44

**Comment by DEAN-Cherry** [comment]
> I think it might be a bit buggy, I can confirm that I have already had the entire list on my android phone. But just like above I also had a list where I only saw my mobile plugins that I didn't push. I explained it more thorough in #44

**Comment by DEAN-Cherry** [comment]
> I think it might be a bit buggy, I can confirm that I have already had the entire list on my android phone. But just like above I also had a list where I only saw my mobile plugins that I didn't push. I explained it more thorough in #44

Thanks for your answers, but I still cannot get instructions about how to solve this problem. The settings in this plugin really confused me a lot, but again, thanks for your help!!!!

**Comment by kenjibailly** [comment]
> > I think it might be a bit buggy, I can confirm that I have already had the entire list on my android phone. But just like above I also had a list where I only saw my mobile plugins that I didn't push. I explained it more thorough in #44
> 
> Thanks for your answer, but I still cannot get instructions about how to solve this problem. The settings in this plugin really confused me a lot, but again, thanks for your help!!!!

After the last update I feel like it's more stable. I got it all working on my android now pretty flawlessly.
On my other device (PC) I first hit the button "Save plugins"
The thing I had to do though in order for it to show up is "Enable plugin synchronization" and then "Show own plugins and settings", if it doesn't show up just enable and disable that last one I mentioned. For some reason it then pops up. If it really doesn't show up, you can try hitting the Reload button.

Hope this works for you.

**Comment by vrtmrz** [comment]
@DEAN-Cherry 
Thank you for waiting! The new plugins and their settings dialog has been implemented!
Could this solve your problem?

**Comment by vrtmrz** [comment]
Close this issue once. Feel free to make a new issue. Thank you!
