### ISSUE TITLE
Live sync won't start

### ISSUE THREAD

**Issue by foegra** [vrtmrz/obsidian-livesync#411]
While running version 0.22.19 on desktop (window and linux) sync does not start automatically when starting Obsidian. 

The only way to start it - reapply settings for "LiveSync" mode, or toggle the compression.

Sync on android work fine.

Couchdb is running self hosted.

**Comment by StrangePeanut** [comment]
I had to downgrade to 0.22.16 to get live sync to work again.

**Comment by EsotericWaveform** [comment]
I am also having this issue. I'm running Obsidian v1.5.12 and I was using obsidian-livesync v0.22.19. I reverted to 0.22.16 and it seems to have resolved the issue after some fiddling with the sync mode.

**Comment by maru-sama** [comment]
I can confirm this.

Once updated to 0.22.19 syncing does not work at all between the devices. I also moved back to 0.22.16 and it started working again.

**Comment by foegra** [comment]
Well - I went back to 0.22.16 as well, works good now again

**Comment by foegra** [comment]
Just in case - issue is not yet solved in 0.23.1

**Comment by vrtmrz** [comment]
Sorry for my absence from the main feature! And, also apologise for your inconvenience.
However, in my environment, LiveSync seems to get started after the checkup correctly. Would you mind if I ask you to check and paste the log, please? If started once, `replication closed` might be shown. If not started totally, it may not be mentioned about replication.

At version 0.22.17, The start timing of start-up synchronisation, including LiveSync, has been moved after the check-up, to prevent unexpected file corruption (especially being wiped out). I think that it could have affected this.

**Comment by foegra** [comment]
Hej. Sorry for confusion, it actually works now, but there was a catch. 
I had to go to plugin settings and apply "livesync" preset again, after that it started to work immediately and works after Obsidian starts as well.

**Comment by maru-sama** [comment]
Hi,

I also did a quick test with two devices now. One is set to live sync while other is set to on events (tablet) and from what I can see the sync is working fine again with the latest released version.

Thank you very very much

**Comment by foegra** [comment]
Hello, again. I'd like to come back to this. After couple of days it's actually back where it was - sync does not start properly. When i start Obsidian - it's always showing 3 files in `"⏳ Working read storage processes"`. Sometimes, after like 5 minutes - sync starts, sometime not. 

Last record in verbose log: `"AM->Synchronizing hidden files done"`

**Comment by vrtmrz** [comment]
I am very happy to hear that your livesync has got be available again!
Thank you so much for your cooperation in investigating.

> it's always showing 3 files in "⏳ Working read storage processes".

This is quite worrying. However, we cannot check what file is actually pending or processing now... Toggling the `Data Compression` toggle would cause a database replication pause and restart with a new configuration. At this time, the process should be forced flushing. So, possibly it is being resolved unintentionally.

I will investigate it again! Thank you so much for your patience and reporting!

**Comment by maru-sama** [comment]
Hello,
I can also confirm, that this is now happening for me as well. Once started freshly sync is paused and I see the "Working read storage processes" hourglass. I then have to toggle the sync settings to make it sync again, BUT the hourglass stays in this case.

**Comment by maru-sama** [comment]
Hello,

tested this some more and I think it is related to the hidden file sync. If I turn it off, it works and I do not see the hourglass. Once I turn it on the hourglass shows up.

**Comment by foegra** [comment]
Yap - that's hidden file sync that is causing an issue.

**Comment by foegra** [comment]
The issue was not addressed on the latest release. May I ask - how high priority has this issue?

**Comment by vrtmrz** [comment]
Sorry, I do not actually know what has been going on yet. It is working just fine in my environment...

Would you mind sharing a configuration report and log? Report can be issued by the `Make report` button on the `Hatch` pane.
And, a log can be copied from the log pane; it can be opened by the archive box button or the `Show log` command.

**Comment by foegra** [comment]
> Sorry, I do not actually know what has been going on yet. It is working just fine in my environment...
> 
> Would you mind sharing a configuration report and log? Report can be issued by the `Make report` button on the `Hatch` pane. And, a log can be copied from the log pane; it can be opened by the archive box button or the `Show log` command.

Here is the information You asked
[log.txt](https://github.com/vrtmrz/obsidian-livesync/files/15236460/log.txt)
[report.txt](https://github.com/vrtmrz/obsidian-livesync/files/15236462/report.txt)

**Comment by foegra** [comment]
I have tried reinstalling livesync from scratch (did not reinstall database itself though) - same behavior, live sync does not start automatically after Obsidian startup.

**Comment by StrangePeanut** [comment]
It works as long as hidden file sync is disabled. Hidden file sync works up to version 0.22.16.

**Comment by foegra** [comment]
> It works as long as hidden file sync is disabled. Hidden file sync works up to version 0.22.16.

Yap. Perhaps it's just a few people using hideen file sync, does not seem like a big issue for others.

**Comment by foegra** [comment]
I can confirm, that issues is fixed in 0.23.7. Thank you very much!

**Comment by StrangePeanut** [comment]
I can confirm the same. Thanks so much.

**Comment by foegra** [comment]
I was too quick to report it closed, sorry about that. 
It worked with Windows + Android until i've upgraded my Linux device. Now - non of the device start live sync, and i get this error on every device:

5/10/2024, 3:00:31 PM->Configuration mismatching between the clients has been detected. This can be harmful or extra capacity consumption. We have to make these value unified.

**Comment by foegra** [comment]
> I was too quick to report it closed, sorry about that. It worked with Windows + Android until i've upgraded my Linux device. Now - non of the device start live sync, and i get this error on every device:
> 
> `5/10/2024, 3:00:31 PM->Configuration mismatching between the clients has been detected. This can be harmful or extra capacity consumption. We have to make these value unified.`
> 
> Going back to 0.22.16

Okay, this time it was something on my side. I've reinstalled the whole CouchDB and plugin on every workstation. Seems to work now!

**Comment by vrtmrz** [comment]
I really appreciate all your patience and contributions! So happy to hear that the problem has been fixed.


@foegra 
> Configuration mismatching between the clients has been detected. This can be harmful or extra capacity consumption. We have to make these value unified.

This has been shown by the new feature. We can disable this message in the `Do not check configuration mismatch before replication` toggle in the Hatch pane.
However, the dialogue that we can unify the configuration will be shown at the replication, and we can do so.

**Comment by foegra** [comment]
How to unify configuration?

I general - I've noticed the it takes more tyme for sync to start after Obsidian launches. It takes around 1 minute for me which is much longer than before.

**Comment by StrangePeanut** [comment]
@vrtmrz today the 'configuration mismatch' message started popping up on my devices too. The description seems rather scary yet no solution is offered. It would be great to know what it means and how to fix it.

**Comment by StrangePeanut** [comment]
> Try clicking "replicate" on ribbon. You will be prompted to unify configuration.
> 
> This is not straight forward, and window should pop up automatically in my opinion

@foegra that worked, thanks!

**Comment by StrangePeanut** [comment]
The sync mode keeps reverting back to 'events' rather than staying on 'live sync' for me. Is this something all of us are experiencing here? (If necessary I'm willing to start completely afresh considering how production stable this plug-in has been for a while now.)
