### ISSUE TITLE
Confused about plugins and settings (beta) tab in the settings

### ISSUE THREAD

**Issue by kenjibailly** [vrtmrz/obsidian-livesync#44]
First of all, this project is INCREDIBLE! I want to say a big thanks, very smooth install, although a few questions about the plugin sync.
I got the sync working after a few tries, but it confuses me a lot hence these questions:

1. Might be a bug or perhaps still in development, but nothing seems to work when without enabling "Enable plugin synchronization", there's no popup telling me that though.

2. Enabling/disabling "Show own plugins and settings" seems to bug out with what is showing under "Device and Vault name" when disabled. Sometimes it shows no config, sometimes it shows a config but the config is from another device that hasn't saved the plugins into the database. When this is disabled shouldn't it show me the plugins that are on the server and not from a random device? 

3. When loading the plugins on another device they get imported, but disabled. Not a problem, I can enable them manually. Though when enabling an addon and going in its settings, they are empty and still need to be configured. So what I'm thinking is that the data.json file inside the according plugin folder isn't included on the sync?

4. Sweeping plugins: does this mean they update automatically to the newest version, how does this work and what does it do exactly?

5. Say I have 2 PC's and 2 mobile phones and want 2 configs for the desktops and for the mobile phones, how would I setup 2 profiles, able to sync with them? In this case, should every device have its own unique name or should it use "desktop" and "mobile" for example?

6. Couldn't find documentation on this, perhaps cause it's in beta? If there is, let me know where I can find it.

Anyway love the project, things are very straight forward how they work through the guides you put up. Got it working in docker on my linux server using swag instead of caddy. Maybe a little tip: the only thing I found not really straight forward is that you have to click "Apply and receive" button in the Local database config to receive all data. Perhaps this could be simplified for users that are just trying to fetch the vault and don't know much about the configuration process.

**Comment by vrtmrz** [comment]
@kenjibailly 
In the new UI, it getting better, but configurations are almost the same.

> Might be a bug or perhaps still in development, but nothing seems to work when without enabling "Enable plugin synchronization", there's no popup telling me that though.

Yes, "Enable plugin synchronization" is the main switch. Once you enable this option, Your passphrases in some plugin's data.json are sent to the server, even you used a weak password. It couldn't be enabled by default. 

> Enabling/disabling "Show own plugins and settings" seems to bug out with what is showing under "Device and Vault name" when disabled. Sometimes it shows no config, sometimes it shows a config but the config is from another device that hasn't saved the plugins into the database. When this is disabled shouldn't it show me the plugins that are on the server and not from a random device?

"Device and Vault name" is locked when "Sweep plugins automatically" or "Sweep plugins periodically" is enabled. And if you synchronized settings of Self-hosted Livesync, It will be overwritten. The biggest problem was very troublesome to choose settings and the UI are so ambiguous. So at v0.7.0, It getting better.

> When loading the plugins on another device they get imported, but disabled. Not a problem, I can enable them manually. Though when enabling an addon and going in its settings, they are empty and still need to be configured. So what I'm thinking is that the data.json file inside the according plugin folder isn't included on the sync?

Same as the second one.

> Sweeping plugins: does this mean they update automatically to the newest version, how does this work and what does it do exactly?

Just find all ["main.js", "data.json", "style.css" and "manifest.json" ] and retrieve into database. perhaps is "sweep" not a suitable word?

> Say I have 2 PC's and 2 mobile phones and want 2 configs for the desktops and for the mobile phones, how would I setup 2 profiles, able to sync with them? In this case, should every device have its own unique name or should it use "desktop" and "mobile" for example?

It requires a unique name to pick the plugin. This plugin can downgrade the plugins.

> Couldn't find documentation on this, perhaps cause it's in beta? If there is, let me know where I can find it.

I'm terribly sorry about this, and I haven't made it yet. The new dialog seems to have stabilized, so I'll write based on this.
Thank you for the advice-giving questions!

**Comment by vrtmrz** [comment]
Close this issue once. Please feel free to open this again if you need anything else.
