### ISSUE TITLE
When I use https+domain, it show "Checking configuration failed" after clicking check-button

### ISSUE THREAD

**Issue by Mr-qing233** [vrtmrz/obsidian-livesync#450]
## Abstract
When I use https+domain, it show "Checking configuration failed" after clicking check-button.
But using http+ip work successfully.
Besides, I can browse the CouchDB Web Backstage normally.
![1717853584029](https://github.com/vrtmrz/obsidian-livesync/assets/59389583/f43abe08-0269-4ad8-97fe-00b7999e60a7)

## Expected behaviour
- Appear the message `Check successfully` after clicking `check button`

## Actually happened
- Appear the message `Checking configuration failed`
- Printed "2024/6/8 21:31:56->Checking configuration failed   2024/6/8 21:31:56->Error:net::ERR_CONNECTION_CLOSED" in log view.
![1717853556044](https://github.com/vrtmrz/obsidian-livesync/assets/59389583/1fbd9483-1d16-4c10-9196-87309db60edb)

## Reproducing procedure

1. Configure LiveSync as in the attached material. (Typing URI with `https+domain`. Username and password is correct)
2. Click the `check button`
3. Appear the error message `Checking configuration failed`

### Report from the LiveSync

<details>
<summary>Report from hatch</summary>

```
2024/6/8 21:31:33->Cache initialized 300 / 250000000000
2024/6/8 21:31:33->loading plugin
2024/6/8 21:31:33->Self-hosted LiveSync v0.23.13 0.23.13
2024/6/8 21:31:33->xxhash for plugin initialised
2024/6/8 21:31:33->Waiting for ready...
2024/6/8 21:31:33->Opening Database...
2024/6/8 21:31:33->Database is now ready.
2024/6/8 21:31:40->Checking database configuration
2024/6/8 21:31:40->Checking configuration failed
2024/6/8 21:31:40->Error:net::ERR_CONNECTION_CLOSED
2024/6/8 21:31:56->Checking database configuration
2024/6/8 21:31:56->Checking configuration failed
2024/6/8 21:31:56->Error:net::ERR_CONNECTION_CLOSED
2024/6/8 21:35:21->Log window opened
```
</details>

### Screenshots
![1717853584029](https://github.com/vrtmrz/obsidian-livesync/assets/59389583/f43abe08-0269-4ad8-97fe-00b7999e60a7)
![1717853556044](https://github.com/vrtmrz/obsidian-livesync/assets/59389583/1fbd9483-1d16-4c10-9196-87309db60edb)

**Comment by holtwick** [comment]
Same here :(

**Comment by Mr-qing233** [comment]
> Same here :( Also with working setup in version 0.20.

Maybe it is associated with the new version of the Obsidian in this days? What Obsidian version are you using? My version is v1.6.2.

**Comment by Mr-qing233** [comment]
It shows this error message in DevTools.


```shell
desktop-97285bc74b725b06:2024/6/9 19:23:09->Error:net::ERR_CONNECTION_CLOSED
plugin:obsidian-livesync:45664 desktop-97285bc74b725b06:2024/6/9 19:23:15->Checking database configuration
plugin:obsidian-livesync:45664 desktop-97285bc74b725b06:2024/6/9 19:23:15->Checking configuration failed
plugin:obsidian-livesync:45662 Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:108519)
    at SimpleURLLoaderWrapper.emit (node:events:517:28)
```

**Comment by holtwick** [comment]
> > Same here :( Also with working setup in version 0.20.
> 
> Maybe it is associated with the new version of the Obsidian in this days? What Obsidian version are you using? My version is v1.6.2.

I use 1.6.3 on macOS. I had a vault where it worked with 1.6.3. As far as I remember the livesync version was something like 0.20. After upgrading livesync I got the error message.

**Comment by Mr-qing233** [comment]
> > > Same here :( Also with working setup in version 0.20.
> > 
> > 
> > Maybe it is associated with the new version of the Obsidian in this days? What Obsidian version are you using? My version is v1.6.2.
> 
> I use 1.6.3 on macOS. I had a vault where it worked with 1.6.3. As far as I remember the livesync version was something like 0.20. After upgrading livesync I got the error message.

Maybe we should try other versions? My version is 0.23.13.

**Comment by Mr-qing233** [comment]
I have finished this problem. It is related to Chinese Internet Policy. You must registered in the Ministry of Industry and Information Technology and after verification.

这个问题的原因在于域名必须先通过工信部备案审核，才可以正常使用该服务。未通过审核前，尽管可以正常访问该网页，但是实际上应用无法使用。

**Comment by holtwick** [comment]
Mine was also a firewall issue related to https://www.obdev.at/products/littlesnitch/index.html configuration 🤦‍♂️ Now everything works great.

**Comment by ericober** [comment]
> Mine was also a firewall issue related to https://www.obdev.at/products/littlesnitch/index.html configuration 🤦‍♂️ Now everything works great.

I'm having very similar issues on MacOS. Any chance you can elloborate on how you fixed/modied your firewall. Was it your MacOS firewall?

**Comment by holtwick** [comment]
I just had a general "recject" rule on the Obsidian. I "allowed" another server, I used before for synching. I just "allowed" all connections and then it worked.
