### ISSUE TITLE
Can't update remote settings (URI, user, etc)

### ISSUE THREAD

**Issue by adrianbn** [vrtmrz/obsidian-livesync#456]
## Abstract
Once set I can't edit the remote settings, such as the URL or the user or password. I changed the domain name for my CouchDB instance and I can't edit the settings to hit it.

## Expected behaviour
Fields in the remote settings section are all editable.

## Actually happened
Remote settings are greyed out / unchangeable.

## Reproducing procedure

1. Configure LiveSync as in the attached material.
2. Go to settings & try to change the remote URI
3. Notice how it is greyed out and can't be changed.

### Screenshots
<img width="1096" alt="Screenshot 2024-06-20 at 5 12 33 PM" src="https://github.com/vrtmrz/obsidian-livesync/assets/3987397/038162b0-4bb8-4aac-8115-00a49696722f">

**Comment by Lraxer** [comment]
You should stop syncing first. In "Sync Settings"，set the "Presets" to "Disable all automatic", then try again.

**Comment by adrianbn** [comment]
That worked, thank you.

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
I am so glad it has been resolved. But sorry for being late!
However, I think that some notes should be displayed. It will be implemented in a while.

I would love to thank you all for your contributions. This issue is closed with all respect and gratitude.
