### ISSUE TITLE
Multiple vaults per database?

### ISSUE THREAD

**Issue by zkat** [vrtmrz/obsidian-livesync#462]
is it possible to get multiple different URIs out of a single server, so I can have different groups on my self hosted sync server?

**Comment by vrtmrz** [comment]
Thank you for opening the issue!

Yes, we can use multiple databases on a single server. 
It could be realised by just setting a different database in the `Database name` field.
However, if all of the group member shares the credentials, please keep in mind that E2EE encryption and path obfuscation are enabled.


If you want to use different usernames and passwords for each user, we have to configure a bit more. In that case, [the official document of CouchDB](https://docs.couchdb.org/en/stable/intro/security.html#authentication-database) will help us.

**Comment by zkat** [comment]
thank you very much!
