### ISSUE TITLE
How to encrypt the database? 

### ISSUE THREAD

**Issue by karekin** [vrtmrz/obsidian-livesync#47]
Thanks for this great work! 

When I hit "Sweep plugins automatically", the editor shows as below:   
<img width="266" alt="Snipaste_2022-02-16_19-53-16" src="https://user-images.githubusercontent.com/47046461/154259468-2e626319-85ad-46a7-a13b-ce1210eb3da8.png">

I don't know how to encrypt my database. Could you please tell me what I should do?

**Comment by kenjibailly** [comment]
> Thanks for this great work!
> 
> When I hit "Sweep plugins automatically", the editor shows as below: <img alt="Snipaste_2022-02-16_19-53-16" width="266" src="https://user-images.githubusercontent.com/47046461/154259468-2e626319-85ad-46a7-a13b-ce1210eb3da8.png">
> 
> I don't know how to encrypt my database. Could you please tell me what I should do?

You need to use the "End to End Encryption" switch button, check the screenshot below:
![image](https://user-images.githubusercontent.com/9883910/154364020-0c0a7985-f034-466f-8101-6919c235999d.png)

**Comment by vrtmrz** [comment]
Thank you for answering,@kenjibailly.
@jueshikuangshen 
Just like @kenjibailly said, you can enable End to End Encryption by toggling "End to End Encryption", setting the passphrase, and pressing "Apply and send".
and on your every other device, toggling "End to End Encryption", set the passphrase the same with your set up, and press "Apply and receive".

**Comment by jueshikuangshen** [comment]
Thank you for this project!
