### ISSUE TITLE
Remote storage size threshold window keeps popping up after start-up as of 0.23.17

### ISSUE THREAD

**Issue by StrangePeanut** [vrtmrz/obsidian-livesync#471]
## Abstract

Remote storage size threshold window keeps popping up after start-up as of 0.23.17

## Expected behaviour

- Window pops up once and never again

## Actually happened

- Window keeps popping up on all devices after start-up

## Reproducing procedure

1. Update to 0.23.17
2. Restart Obsidian
3. Wait

**Comment by Yarosvet** [comment]
I confirm this issue too

Obsidian v1.6.7
Livesync plugin 0.23.18
Windows

**Comment by dlphnkck** [comment]
Do you have "Notification" set?

**Comment by vrtmrz** [comment]
Sorry for being absent!
This can be configurable as disabled by setting 0 to the `Remote configuration`  -> `Notification`  like this:
![image](https://github.com/user-attachments/assets/1321d5e8-e0cd-4516-b174-9e75bdbcc29a)

However, I recommend that configuration to some sizes and using the `Enlarge the limit` button each time to avoid unexpected database corruption or storage running out. 
When pressing the `Enlarge the limit` button, enlarge the detection threshold to the current usage + 100MB.

![image](https://github.com/user-attachments/assets/667d7e2d-d8f8-4c6e-8525-3ca0ac18bcfb)

**Comment by Bonsailinse** [comment]
Then the bug would be that the popup does not adjust the setting, it keeps on `-1`, no matter if I choose "no limit", "800mb" or "2GB".
A hint to the actual configuration in the settings would be great as well so that users know they can adjust the setting without limiting it to the pre-selected values.

**Comment by BobWs** [comment]
I have the same issue since the latest update, it doesn't matter which limit I choose the window keeps popping up after every new start of the app. So now I have disabled the notification as noticed above. (The popup window was quite large and annoying!

**Comment by vrtmrz** [comment]
Thank you for your patience! 

There were things which I had not noticed yet. So sorry for the wrong explanation.
The actual problem was indeed as you mentioned; our decision had not been saved.

This has been fixed at v0.23.20. Would you mind if I ask you to check the behaviour, please?

**Comment by StrangePeanut** [comment]
@vrtmrz solved, thanks!

**Comment by BobWs** [comment]
@vrtmrz solved, thank you!
