### ISSUE TITLE
Trouble actually syncing

### ISSUE THREAD

**Issue by themaster567** [vrtmrz/obsidian-livesync#472]
The following is better suited for a chat like Discord, but since there is no community for this plugin and I've been at this for four hours, I'm putting this here. I apologize for not using your template for the issue tracker:

I feel like I'm going insane here. I followed the [Docker guide](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server.md) but it seems like Livesync is determined to lie to me. It repeatedly claims on both devices to be set up perfectly, no issue with connecting, and if I change the database to a new name so that it's forced to some writing to the server, it can be seen from the "_utils" web page that it is indeed creating a new database on the remote server. It should be connecting to [https://livesync.blairtech.org](https://livesync.blairtech.org), and if you go there, you'll see the proper prompt for a username and password. Obviously I won't give that sort of information, but I'm just demonstrating that I do indeed have a live URL with SSL configured properly.

The problem is that I don't have any idea whatsoever where to go from here. It is very likely that from my haze of frustration that I am just blind to the obvious answer, but whatever. As it stands, nothing actually syncs. I copy the URI link from one computer to another. All the data is on my macbook, so I copied the URI from the macbook to my Windows desktop after creating a test vault with nothing in it on it, but no other vaults appeared. I tried creating a vault with a matching name as the one on my macbook that I wanted to sync, but it didn't help. Nothing changes between the two vaults.

EDIT: I'm now at the point where it synced between two devices, until it didn't. It's a complete mess. My macbook synced its contents to my desktop, but making a change on one does not affect the other. Worse, the files seemingly keep disappearing on the mac side. I say that because, not randomly but not for a reason I've figured out yet, the entire contents of the macbook's side keep getting deleted. They're completely gone until I restart Obsidian, wait a completely random amount of time, where they'll then reappear and load if I have the tab open. If I close the tab, the contents are gone. This is 100% repeatable. Looking at the bottom, seeing that there's somehow 107 operations to complete (assuming the gear symbol means that) it seems like it's continually redownloading absolutely everything over and over and over, deleting them each time.

EDIT 2: Now it's saying "Failed to save file" and "File system operation timed out.. Make a backup of the contents of this file now to avoid losing data." I'm lost.

EDIT 3: I finally saw it sync back from the computer. Once. It took an eternity, I fiddled with a ton of different settings, and it never worked again.

EDIT 4: This is the next day. Restarting the mac seems to have finally forced it to work, after setting both sides to livesync mode and forcing the new changes to be automatically synced. They were setting themselves a different mode by default, but this isn't new info, I extensively messed with every possible setting before restarting out of desperation. Regardless of what the true fix was, it's over with. I'm just glad it works now.

**Comment by vrtmrz** [comment]
Sorry for that I have not been here much recently. First, I am so relieved to hear your troubles are now fine.

I am so sorry to read of your difficulties and confusion. I thought that there should be more explicitly displayed `Configured`, or `Not matched to the recommendation value` mark. And the way to bring the values to the default or recommendation.

I will consider whether there is a better way.
