### ISSUE TITLE
Can not sync the note and the plugin/settings. 

### ISSUE THREAD

**Issue by xfdywy** [vrtmrz/obsidian-livesync#48]
Hi,  Thanks for your great plugin!

I test the livesync in two Win10 device.  

In device 1, it works well. I can sync the note and the plugin/settings.

In device 2, it does not work. I can not sync the note and the plugin/settings. The log is as following.

If I write in the device 1, the device 2 can change as well. But if I write in the device 2, the device 1 will not change since device 2 can not upload any information.

Plugin/setting sync is the same : 1 ->  2 ok,  2->1 not ok.

![image](https://user-images.githubusercontent.com/6959554/155847792-c1eda389-b0d4-43a2-a7d9-cdf8032ceeb2.png)

If I close the plugin/setting sync, all things work well. I don't know what happened. 
 
Could you please help me? 

Thank your again for your help and great plugin!

**Comment by vrtmrz** [comment]
Thank you for asking me!
If the database is not locked in the settings dialog, Something happened in synchronizing.
Could you enable "Verbose log" in the "General Settings" and capture the logs?
(Or Open DevTools by Ctrl+Shift+I and give the screenshot on network pane like #26)

**Comment by vrtmrz** [comment]
Close the issue once. Please feel free to open this again if you need anything else.
