### ISSUE TITLE
Obsidian crashes seconds after starting replication

### ISSUE THREAD

**Issue by jorgementx** [vrtmrz/obsidian-livesync#491]
## Abstract
Obsidian crashes short time after I start the replication process. I am trying to move all my obsidian livesync setup from one VPS provider to another. CouchDB is already working on docker and obsidian can connect to it.
I also had to "Verify and Repair all files" and click on hundreds of files because the plugin said that those files where missing in the local database.
Then I proceeded to replicate manually and the crash happened.

## Expected behaviour
- Synchronisation ends or prints an error message while failing gracefully
- Disk usage in remote server should go up

## Actually happened
- Nothing updated in the remote database (disk usage is the exact same)

## Reproducing procedure

1. Run command `Self-hosted LiveSync: Replicate now` of click on the "Replicate" button in the left sidebar.
2. Wait for some seconds.
3. Black screen (While having devtools open, debugger stops execution with the message "Paused before potential out-of-memory crash". After continuing execution, the crash happens).

### Screenshots

![unknown_2024 09 14-13 46_1](https://github.com/user-attachments/assets/627c615c-ae53-471f-bdeb-336ea5593aed)

### Other information, insights and intuition.

- The whole vault is like 6GB
> In the previous VPS the data folder used as volume by the CouchDB docker container was like 8GB
- There's a lot of binaries
> They are the ones taking most of the space. Contained mainly in a single folder.
- This one should be the first replication. 
- I also updated obsidian livesync before this migration to the last version.

I'll be happy to provide more information if needed.

**Comment by vrtmrz** [comment]
Thank you for opening the issue! 
This should be a design flaw. Thanks to your information, it identified out-of-memory. 
I will be fixed at v0.22.23. However, to avoid this situation now, please disable `Send chunks in bulk` at `Sync Settings`->` Performance tweaks` on the setting dialogue for a workaround.
Sorry for your inconvenience but thank you for your patience!

**Comment by vrtmrz** [comment]
I am so relieved to hear that! 

1. The default setting will be disabled. (Unfortunately, it will not affect the migrated users). If you do not have the latency problem, and your vault once sent, it would not be so effective configuration. This feature has been made mostly for the first or larger replication. However, it indeed caused this situation. Ideally, we should be asked to use or not at the time for them. Finally, the default setting will not apply to either option.
2. Yes, we can use `Sync settings` -> `Target` -> `Non-synchronising files` to determine the targets by regular expression.

I hope this helps to the honour you have given me!

**Comment by jorgementx** [comment]
Thanks a lot!

(Don't know if I should close the issue so I will leave that to you just in case)

**Comment by vrtmrz** [comment]
I am so sorry for being late! And so relieved to hear that!

Thank you for your kindness and respectful atitude! Of course, you could close the issue!
