### ISSUE TITLE
Cannot update plugin

### ISSUE THREAD

**Issue by Deviantgit** [vrtmrz/obsidian-livesync#50]
Hello,

First of all, thank you so much for creating this plugin! It has worked flawlessly, with end-to-end encryption, since I installed it, and I now consider it invaluable. I have noticed one issue, however: when I try to update to the latest version (I am running version 0.6.1 on all my devices), it gives me an error saying "Plugin ID mismatch."

How do I solve this?

**Comment by vrtmrz** [comment]
Thank you for using this plugin and giving me an honorable comment! 
It'll improved more useful with your voice.

But it doesn't happen to me.
Could you back up your `data.json` in your vault's `.obsidian/plugins/obsidian-livesync` and uninstall Self-hosted LiveSync once, then re-install again?
The setting file is compatible. 
(Local database will not be lost except you won't re-install Obsidian)

**Comment by Deviantgit** [comment]
That worked perfectly! Thank you, and thank you again for making such a great plugin.
