### ISSUE TITLE
Livesync does not handle files modified outside Obsidian

### ISSUE THREAD

**Issue by foegra** [vrtmrz/obsidian-livesync#518]
Running now version 0.24 rc6
I sometimes need to modify files in bulk, which can only be done by external editors. 

If I do that, when Obsidian is closed - files get changed back to the the state they were before. How can this be avoided?

**Comment by vrtmrz** [comment]
Thank you for trying the dev release!  And, really glad to know that beforehand the stable release. 

I will try to reproduce it soon! Probably, some different reasons are there.
I would like to hear some additional information. Shall I? 

- The file would be back...
  - at the next start?
  - after some minutes and before closing Obsidian?
- These files' were...
  - updated with the new modified time?
  - not change its name?

And, one more thing, `Scan database and storage again` might affect you in two ways. However, I am not sure which will be happened in your situation. Would you mind if I ask you to check the behaviour of it?
- A: just causing as same you reported, files are back immediately.
- B: modification surely stored and files are sane, and can be synchronised to other devices. 

Finally, I would love to say thank you for testing the dev release!

**Comment by foegra** [comment]
I've tested it again with rc7 - could not see problem this time. Not sure exactly what happened.
