### ISSUE TITLE
Hidden directory sync

### ISSUE THREAD

**Issue by echo-saurav** [vrtmrz/obsidian-livesync#52]
Am i missing somthing or livesync doesn't sync hidden directory?? 
I have two obsidian config dir (mobile and pc) but they are not syncing. I see plugin syncing settings, but i want to sync my css config too

**Comment by vrtmrz** [comment]
Thank you for using this plugin!

But unfortunately, the hidden directory is not supported. 
Modifications of CSS and configs of Core plugins couldn't be detected in normal ways.
So we have to sweep these configurations in some ways. 
We need some ideas...

**Comment by vrtmrz** [comment]
@echo-saurav 
I thought that changing CSS and configurations is not something that happens so often, so I created a utility.
Does [Screwdriver](https://github.com/vrtmrz/obsidian-screwdriver) useful to solve this problem?

**Comment by echo-saurav** [comment]
hey that's awesome, thank you
