### ISSUE TITLE
got "bad_request:invalid UTF-8 JSON" in test server

### ISSUE THREAD

**Issue by Petingo** [vrtmrz/obsidian-livesync#53]
Hello, I met this error when trying to connect to the test server:
```
3/17/2022, 3:41:21 PM->could not connect to https://olstaste.vrtmrz.net/ls-706574657374323339 : obsidian 
(bad_request:invalid UTF-8 JSON)
```
I have two machines, one runs win11 and another runs macOS Monterey, both with Obsidian v0.13.33, and they have the same error.

**Comment by vrtmrz** [comment]
Sorry! I didn't notice this!
The test server rebooted! and a new connecting method will resolve troubles about connecting.
Could you please try v0.8.1?
