### ISSUE TITLE
Installation of CouchDB with Yunohost

### ISSUE THREAD

**Issue by Limezy** [vrtmrz/obsidian-livesync#55]
Hi @vrtmrz thank you so much for that plugin.
There is a very easy way to install CouchDB on a VPS with full https etc... which is Yunohost [with CouchDB app](https://github.com/YunoHost-Apps/couchdb_ynh).
If you agree I can make a quick PR to update the dedicated documentation and add a link for those who would be interested

**Comment by vrtmrz** [comment]
Thank you for your proposal and information! I think this distro is useful.
And, of cource! Your contributions are always welcome! 
I was on the run out from explaining server setting up by just only this word: `And, be sure to check the server log and be careful of malicious access`.
