### ISSUE TITLE
New documents in iPhone can't be synchronized to couchdb

### ISSUE THREAD

**Issue by victor10292** [vrtmrz/obsidian-livesync#550]
It has been working fine until I rebuilt the couchdb in my own server. I have two terminals, a PC and a iPhone. The changes in PC can be uploaded into remote couchdb. And the replication process is finished normally. In the log console, 'Replication completed' is printed. 

I also re-configured the plugin in iPhone. All the documents can be retrieved from couchdb successfully. However, I found new documents in iPhone can't be synchronized. There is no new messages after 'Replication activated' in the console. Then I checked the couchdb log. It showed that one task was repeated without end. I suspected something is wrong with my local documents in iPhone. I have no idea how to find that document. Could you please help check it? The log in couchdb is attached. 

Thanks
![2024-11-30_13-55](https://github.com/user-attachments/assets/fa94391e-c986-47fe-9647-abb5798313ad)

**Comment by vrtmrz** [comment]
Thank you for asking me! And also thank you for the log!

This is the normal behaviour. At the first replication, the new device would track the changes until the latest one on the remote database. This does not transfer any content. Just for comparing the changeset and marking the point of the previously scanned.
Once tracked, only differences will be scanned and transferred (if the device needs it).

Please wait for a while with the device on (and it is even faster if you are connected to a fast network).

As per your log, your batch size seems 25, and the processing change sequence number seems 26125. So, it may take around 1000 requests. To improve this performance, It can be larger by the `Batch size` `Power users` pane.

And, the Latest sequence no. can be seen in your log (Please enable `Verbose log`).  This can be different on each device. However, almost the same.
![image](https://github.com/user-attachments/assets/c0f40381-6066-4667-adc1-d011b3b83462)

**Comment by victor10292** [comment]
Thanks for your prompt response and advise. I re-installed the couchdb and strictly followed your installation instruction. It works. Thanks for your time to take care of this issue. I will close it.
