### ISSUE TITLE
plugin can't load on Android 

### ISSUE THREAD

**Issue by heddxh** [vrtmrz/obsidian-livesync#56]
When I update to the latest version (both Obsidian and this plugin),it can't be loaded. 
Does it use an API that isn't available on mobile?

DEVICE: Pixel 4 XL Android 12

**Comment by heddxh** [comment]
What should I offer?

**Comment by heddxh** [comment]
ohh I reinstalled the plugin and it worded!
sorry for disturbing

**Comment by vrtmrz** [comment]
I'm very happy to hear that!
