### ISSUE TITLE
Obsidian-less Livesync?

### ISSUE THREAD

**Issue by heywoodlh** [vrtmrz/obsidian-livesync#57]
Disclaimer: I completely understand if this is not desired or out of scope for this project as it is an Obsidian plugin.

I was wondering if there is any functionality for livesyncing without Obsidian being open? The use-case is that I would love to use something like `vim` for writing notes on my computers but be able to continue using the Obsidian app on mobile and have it livesync without the Obsidian app needing to be open on my computer.

If this isn't possible or desired I understand, but perhaps I could be given some tips on where to look at the code that does the syncing in the plugin. 

I'd love to implement a client-side daemon that connects to my CouchDB instance and updates my livesync notes.

**Comment by vrtmrz** [comment]
Thank you for giving me your voice!

It's will be useful. And we can. 
I implemented this in just for single direction (from CouchDB to real files) as a part of [LiveSync-classroom](https://github.com/vrtmrz/livesync-classroom).
As you said, perhaps real file handling should be separated into a dedicated app. Then we will implement the file system watcher more simply. (CouchDB watcher already exists on PouchDB). 

And we have to make some common parts to be some library in the future.

**Comment by heywoodlh** [comment]
> perhaps real file handling should be separated into a dedicated app

This would be super cool! 

Let me know if there's any way I could help.

**Comment by heywoodlh** [comment]
Whoa cool! That was so quick, thanks! If you provide a README on how to build/run I will totally test it out.

**Comment by heywoodlh** [comment]
Thanks for implementing filesystem-livesync! It works perfect for me. Documented my workflow on usage here: 

https://the-empire.systems/use-vim-with-obsidian



Thank you for all the work you put into this!!!
