### ISSUE TITLE
Plugin Naming Feedback

### ISSUE THREAD

**Issue by lishid** [vrtmrz/obsidian-livesync#6]
Hi there! I've received feedback from a couple of community members and moderators that the naming of this plugin could be confused with Obsidian's own Sync add-on.

Is there any chance you'd consider a tweak to the plugin's name, perhaps something like `obsidian-couchdb-livesync` to make it more distinguishable?

Thanks!

**Comment by vrtmrz** [comment]
Thank you for letting me know. I think too.
Of course.
Actually, I asked some questions from a few people, "this is an alternative solution?" "Why did they accept this plugin?"
I answered "Complementary one." "Looks similar, but aimed to different purposes"

So I thought that It should have

**Comment by vrtmrz** [comment]
Sorry, closed by mistake.

**Comment by vrtmrz** [comment]
@lishid 
What do you think about `Self-hosted Live Sync`?

And if I changed the name, how do I have to do?
I think as below.
Must
 - Change the manifest (leave id and change name only)
 - make a pull req to obsidian-releases.
 
 Needed? 
- Change the repo name

**Comment by vrtmrz** [comment]
@lishid 
Ah.. If official sync provides selfhosted server, `selfhosted-livesync` will make confusion again.
Ok, Please pick the name as you like.

**Comment by vrtmrz** [comment]
Finally, I changed the plugin name to Self-hosted LiveSync and add the note "Community implementation" to description.
May i close this issue?

**Comment by lishid** [comment]
Sounds good! Sorry I haven't gotten a chance to respond earlier, I think this works great. Thanks again for your hard work.
