### ISSUE TITLE
CSS Snippets not being Synced

### ISSUE THREAD

**Issue by turulix** [vrtmrz/obsidian-livesync#62]
Hey! I'm using CSS Snippets for a few optimisations on my vault, I noticed they do not get synced which is a little problematic for me, any intentions to work on this in the future?

**Comment by vrtmrz** [comment]
Thank you for using this plugin!

I thought too! After some consideration, I noticed this: Unlike plugins and settings, CSS Snippets are not so changed frequently.
So I made [Screwdriver](https://github.com/vrtmrz/obsidian-screwdriver). It doesn't help you?

**Comment by vrtmrz** [comment]
Synchronization of hidden files are implemented in v.0.12.0! Close this issue once. Feel free to make a new issue. Thank you!
