### ISSUE TITLE
can we have an option to not sync Untitled notes?

### ISSUE THREAD

**Issue by rakanzaidm** [vrtmrz/obsidian-livesync#65]
working with pc-android, when i'm creating new notes, sometimes it synced before i have the chance to name the note, and when i finally name the note, sometimes the synced untitled notes disappear, but sometimes it's still stuck there and i have to delete them manually. it would be great to have an option to just not sync those types of notes. thank you in advance!

also for more context, the Untitled getting synced usually happens when i create a new note right after opening obsidian (obsidian livesync is still checking and processing stuff i'm guessing)

oh and i think the option to not sync Untitled notes would solve another issue that sometimes happens to me when creating new notes, because i'm using templater with automatic template, when i have both pc and android open, and the Untitled notes got synced, both devices compete with creating template because both thought that it was a newly created note, so a conflict happen. if the Untitled notes never got synced in the first place, the problem would be gone :D

**Comment by vrtmrz** [comment]
Thank you for your suggestion!

I thought it is the key to our problem:
> also for more context, the Untitled getting synced usually happens when I create a new note right after opening obsidian (obsidian livesync is still checking and processing stuff i'm guessing)

Yes. As you said, This was the problem. We spent so much time detecting and reflecting offline changes between database and storage.
Now, it is much faster. LiveSync speeds up on v0.8.5. 
Could you please try this version?

(The filename filter is still under considering how to be implemented.)

**Comment by vrtmrz** [comment]
Sorry for forgotten reply, it has been implemented as `Regurar expression to ignore files`.
Please feel free to open it again if you need anything else.

**Comment by wchorski** [comment]
I've been trying to figure out how to ignore `Untitled.md` files with no success. possibly my limited knowledge of regex.

![image](https://user-images.githubusercontent.com/33769609/193134455-02208e6e-de99-489c-9c34-5f995b6293b0.png)


I've put this on the host Vault's settings yet still `Untitled.md` files still sync. Do I have to "save settings" to get this to work?

**Comment by vrtmrz** [comment]
Sorry for being delayed!
If we want to ignore the file like `Untitled xx.md`, we have to configure `Regular expression to ignore files` to `Untitled.*\.md$`. 
Your wondering is right, they lack unity. I should have been prudent.

**Comment by wchorski** [comment]
Thank you! `Untitled.*\.md$` works. Regex feels like feeling your way in the dark.

I was trying to apply this logic to the "Skip Patterns" to ignore directories.

![image](https://user-images.githubusercontent.com/33769609/194678893-bf63611b-7e37-4546-9175-6fb4c62c0646.png)

I'm testing between my **mobile android** and **desktop** app. They both have this `/private/` and `/private*$/` entry. But it still syncs  this `private` directory placed in the root of the vault. Even the child files get synced still

- Is this "skip patterns" only used when a certain setting is turned on?
- is the regex correct when ignoring a directory in the root?
- how would I expand upon this logic to use wildcard characters?

**Comment by vrtmrz** [comment]
Skip patterns are only working on Hidden file synchronisation. To ignore workspaces state(i.e., Opening files, Panes) and anything in LiveSync (If not, we will be so troubled on upgrading)
If we want to ignore specific standard files, we can use the `Regular expression to ignore files`. 

This site is useful for checking regex.
https://regex101.com/
Copy the path of the file (we can do this in context-menu of File explorer) and paste it into the checker, and try some expressions.

**Comment by gssantana** [comment]
@vrtmrz continuing this thread. Is it possible sync hidden files in one unique direction?

For example:

A - My private computer where I install/update plugins, arrange workspace, set hotkeys, css snippets and so on.
B - my work computer

I would like B can receive all this hide files, but any update in these files in B can not override files in A, or where we can choose to allow specific files, per examples, hotkeys.

Why I would like to do this... I have lived situation where after to setup my private and work computer, my hide files like hotkeys files have been override.

Independent this is possible or not, I would like to thanks your dedication and works for this great and hard work. This plugin let me my notes to be with me together always :) Thanks
