### ISSUE TITLE
When I turn on real-time synchronization on my mobile phone, the software will be very stuck. I cannot open the notes I want to open, nor can I switch my notes, and I cannot delete them.  My document, I can't rename my document,

### ISSUE THREAD

**Issue by bbcghh123** [vrtmrz/obsidian-livesync#72]
1. Hello, I have updated the latest version, but the problem has not been solved. When I turn on real-time synchronization on my mobile phone, the software will be very stuck. I cannot open the notes I want to open, nor can I switch my notes, and I cannot delete them.  My document, I can't rename my document, I recorded a video you can take a look at, please solve 
2. I want you to set up a telegram exchange group.  
3. Video address[Video address](https://spfrp5a6ok.feishu.cn/file/boxcnKjoCSE4TFc4f3LpeirMd0f)  ：https://spfrp5a6ok.feishu.cn/file/boxcnKjoCSE4TFc4f3LpeirMd0f

4. My device information
My mobile phone information
---------- Equipment --------- Equipment Name: Galaxy S10 Model: SM-G973U1 Manufacturer: Samsung Equipment: Beyond1Q Motherboard: MSMnile Platform: QCOM Brand: Samsung

 --------- System --------- Version: Android 12 S API version: 31 System version number: SP1A.210812.016.G973U1UES6HVD1 Construction Time: 31 March 2022 15:11:23 GMT + 08: 00 Equipment version number: SP1A.210812.016 Program Safety Patch Level: 2022-03-01 Guidance Loader: G973U1UES6HVD1 Based Version: G973UES6HVD1

**Comment by vrtmrz** [comment]
Thank you for the detailed information! It also helps me!

It looks like the same problem as #63. Thank you for waiting a long time.
Could you please try v0.8.6

**Comment by bbcghh123** [comment]
I've installed it and haven't had issues yet, it's great, thank you so much.Can you watch my video normally please, can I turn it off using the old connecting method

**Comment by vrtmrz** [comment]
Close this issue. It should be fixed. Feel free to open it again if you have new something.
