### ISSUE TITLE
What did I do wrong? Ask for help

### ISSUE THREAD

**Issue by i-iooi-i** [vrtmrz/obsidian-livesync#73]
The first time I use livesync, when I successfully link the database and turn on the livesync option.

![image](https://user-images.githubusercontent.com/1827701/167296562-065f1bb1-3bbb-46c7-ade2-1974748f88a1.png)

I will receive a prompt in the red box. Before that, I didn't turn on other options. What do I need to do? It seems to be an error message for me.

![image](https://user-images.githubusercontent.com/1827701/167296522-a369378a-2d7c-4c0e-b3d9-191c1ea44993.png)

**Comment by SONDLecT** [comment]
Just untoggle "Live Sync" if you want to change any settings on that tab. Turn the toggle back on when you are ready to enable the feature.

**Comment by i-iooi-i** [comment]
> Just untoggle "Live Sync" if you want to change any settings on that tab. Turn the toggle back on when you are ready to enable the feature. I don't believe anything isn't working as intended here.

Later, I found this problem. Livesync on PC turns off "end to end encryption" by default. It seems that livesync I installed on iPhone turns on "end to end encryption" by default after installation. When I create notes on my mobile phone, it can synchronize note files, but the synchronized note content is blank. 
![Snipaste_2022-05-10_21-49-05](https://user-images.githubusercontent.com/1827701/167645786-b3f89155-1de0-4ca5-a53b-7f8088b56268.png)

Then I started “livesync”,As you can see, the red box appears. I thought it was an error prompt, but I didn't know where the error was, so I came here to ask a question.😂😂😂
![image](https://user-images.githubusercontent.com/1827701/167646171-543fa840-514a-48f8-8650-f9b091b1fcf0.png)

There are many options in the plug-in, which is a little complicated for people who use it for the first time. But now it's much better. I find that I just need to turn on "livesync", and I keep other options as default. Now everything is going well.😼

**Comment by vrtmrz** [comment]
Thank you for asking us!
The default setting does not use encryption.
I wonder why it was... I'll test it.
Anyway, the encryption setting should be same between every device.

Could you please try setting password and press “Apply and send” in any device. And press “Apply and receive” in any other devices(One by one).

**Comment by i-iooi-i** [comment]
> Thank you for asking us! The default setting does not use encryption. I wonder why it was... I'll test it. Anyway, the encryption setting should be same between every device.
> 
> Could you please try setting password and press “Apply and send” in any device. And press “Apply and receive” in any other devices(One by one). (If you synchronized the DB once, the contents in the local database is mixed with one with encrypted with another passphrase. )

Hi, thank you for developing great plug-ins!

I think it's my first time to use it. I created some confusion myself. I open "end to end" on my PC, but it didn't open on my mobile phone. When syncing some articles, there will be some errors, such as only the title and no content.😂

Now I use it correctly, so the problem doesn't exist. In a word, it's my first attempt. I won't use it because I can't understand the meaning of so many options. Now it's perfect as long as you turn on "live sync" without doing anything else

In addition, whether to consider changing the red box to other colors,👇 because now it looks like an "error prompt" rather than a "attention prompt". For example, in different cases, it is marked with different colors. Especially for those who are not familiar with English, it will cause some confusion.🥲

Thank you again for your efforts. It's really great!❤️❤️❤️

![image](https://user-images.githubusercontent.com/1827701/168414217-bf601726-4570-4cbf-addf-eba302e7ea3b.png)

**Comment by vrtmrz** [comment]
Hi! I'm really sorry to forget to answer this!
From v0.10.0, notice and warning are separated into different styles and headings.
Could you please check the dialog?

**Comment by i-iooi-i** [comment]
> Hi! I'm really sorry to forget to answer this! From v0.10.0, notice and warning are separated into different styles and headings. Could you please check the dialog?

Thank you very much. I have updated to the latest version. It's really great, and it turns yellow instead of an anxious red warning. Thank you very much for your efforts. 💕💕💕
