### ISSUE TITLE
Settings to turn off notifications 

### ISSUE THREAD

**Issue by echo-saurav** [vrtmrz/obsidian-livesync#74]
This plugin works great! but when i am outside not connected to my local network it keep showing me notification that it can not connect to database. 
Its so distracting on mobile, can we have a setting to turn off notification completely

**Comment by vrtmrz** [comment]
Thank you for asking me!
This was previous behavior but looks like I forgot implementation.
Fixed on v0.8.8. could you please try this?

**Comment by echo-saurav** [comment]
yup fixed, thank you
