### ISSUE TITLE
CouchDB created but then throws remote database is newer or corrupted error.

### ISSUE THREAD

**Issue by vactomas** [vrtmrz/obsidian-livesync#77]
# Information about used configuration
Platform: Windows 11
LiveSync version: 0.11 – downloaded through Obsidian
Database: CouchDB docker – 3.2.2
Reverse proxy: Caddy docker – 2.51

# Bug
After setting up the docker container with CouchDB, I have added the correct URL, username and password into the LiveSync settings page. After hitting apply, I got the “Initilize done!” notification and later a notification saying that I should lock the remote database. When I tried to sync my files to the DB, an error saying Remote database is newer or corrupted showed up.

# Expected behaviour
After setup, data syncs without issues.

# Additional info
I have not tested it on any other platform. Simply after setting up the CouchDB container, I tried to upload the DB with Obsidian without any previous database initiation.

**Comment by vrtmrz** [comment]
Thank you for making the issue!
May I ask for the information shown when you hit the `Check database configuration` button?
Did everything pass with a checkmark?

**Comment by vactomas** [comment]
Yeah, it seems like it did pass.

![image](https://user-images.githubusercontent.com/68682763/173317610-fabc75c9-ff18-4d99-b584-482c6beb377c.png)

**Comment by vrtmrz** [comment]
Thank you for your testing!
I'll investigate this!

**Comment by vactomas** [comment]
If any additional information regarding my configuration would help you, just tell me what you need.

**Comment by vactomas** [comment]
Fixed it. It was an issue with db name.

**Comment by vrtmrz** [comment]
@vactomas 
I’m so relieved to hear that! May I ask for the database name? 
I have to fix the checking database logic (It has to say 'database name is wrong')

**Comment by vactomas** [comment]
I didn’t realise, that it needed to be a single word and used spaces (e.g. My Vault).

Could you maybe mark the field as mandatory and place a comment there regarding how the name should look like?
