### ISSUE TITLE
Can not connect to CouchDB in Synology Docker

### ISSUE THREAD

**Issue by Cityjohn** [vrtmrz/obsidian-livesync#79]
For a non-profit it would be VERY helpful if we could run several couchDB databases for obisidian collaboration
But it turns out to be a bit more difficult to set up that I thought and I'm having a major issue setting up a couchDB on my synology for livesync:

I set up the docker image using the following command:

sudo docker run -d --name VV -it -e COUCHDB_USER=.nectifecon -e COUCHDB_PASSWORD=[password] -v /volume1/docker/couchdb_ini/local.ini:/opt/couchdb/etc/local.ini -p 5984:5984 couchdb:latest

Then I opened port 5984 on my synology server and tested it, it is open.

Checked my container which looks like this:

![12434366](https://user-images.githubusercontent.com/34970833/173345394-6d728e19-ae7a-4d70-a7a4-476fcf034e17.JPG)

But I still always get the same error no matter what URI I use:
I tried the local network ip and external ip using either http or https with different ports.
I thought that https://192.168.178.12:5984/ should be the correct one.

![Screenshot 2022-06-13 13 30 11](https://user-images.githubusercontent.com/34970833/173345433-6ede98fe-277b-48c2-9568-18abc93685de.png)

Anyone have any idea what I'm doing wrong?

**Comment by vactomas** [comment]
You might want to try to open the URL in your browser. It will give you an idea, if the container works properly or not. Furthermore, you can check the logs of the CouchDB container to see if there aren't any errors there.

**Comment by Cityjohn** [comment]
Good points, I tried to connect via browser and it timed out. The logs did show me that a few hours ago some connections sort of got through but not quite so I figured I'd try several more combinations of URI's and I got one to work.

I think I found the issues. http:// works to connect instead of https:// And the second issue was that VV is an illegal database name since capital letters are not allowed.

![image](https://user-images.githubusercontent.com/34970833/173360398-460eaa85-db32-45e1-b051-a6591db9fa2c.png)

How does one get https:// to work and is it really necessary for secure operations?

**Comment by vrtmrz** [comment]
Thank you for using this plugin! And so thank you for supporting me @vactomas. 

@Cityjohn 

> issue was that VV is an illegal database name since capital letters are not allowed.
Thank you! I'll implement this into checking the configuration. 

> How does one get https:// to work and is it really necessary for secure operations?

It doesn’t be required if you are using only a PC or Mac and run on the intranet. But if you want to expose the database via the internet, you have to. 
In Synology, you can set up the reverse proxy in Control panel -> login application  -> details (If same as DSM 6)
The KB is [here](https://kb.synology.com/en-us/DSM/help/DSM/AdminCenter/application_appportalias?version=6).

**Comment by Cityjohn** [comment]
Aha wait i think I have to make a Let's encrypt certificate for each domain name but Synology won't allow me to because of a non descript error.

![image](https://user-images.githubusercontent.com/34970833/174124033-6c5a7309-f618-4ef4-84cb-397910f64af2.png)

**Comment by Cityjohn** [comment]
Great it worked by turning off UPNP on my router and opening port 443 manually.

Now when I use these settings to connect to the database:

![image](https://user-images.githubusercontent.com/34970833/174125815-d6d3db3c-c5d3-4f4f-b229-aad7890a5d6f.png)

I get an immediate error:

![image](https://user-images.githubusercontent.com/34970833/174125914-07bb2db1-d4d4-4315-b551-74a105268d88.png)

Where do I open inspector?

**Comment by Cityjohn** [comment]
I DID IT!

![image](https://user-images.githubusercontent.com/34970833/174126832-5051ae4c-83f8-4353-802c-439a0bf10ef7.png)

The problem was that in the Synology GUI, after you have issued the certificate, you have to also configure it to be subject to the specific domain name so that you do not get a NET::ERR_CERT_COMMON_NAME_INVALID error.

Now I can move on to testing how these databases work haha.

**Comment by Cityjohn** [comment]
Works like a charm, I'm so happy. I hope this helps others with Synology who are finding it hard to get it running as I imagine a lot of people will want to use this system on their synology servers.

Just to elaborate the previous statement, when creating a certificate in the synology GUI, and when you press config, you can select which third party signed certificate belongs to which domain name, which is important.

Blue is correct, and red is incorrect and will yield the invalid name error:

![image](https://user-images.githubusercontent.com/34970833/174144132-2136ba69-8b20-46f5-9d95-7c47a0c7a8eb.png)
