### ISSUE TITLE
Docs of Setup CouchDB is needed.

### ISSUE THREAD

**Issue by vrtmrz** [vrtmrz/obsidian-livesync#8]
From Forum:

Basics
- Self-hosting limitations.
- Setup CouchDB ( bare? / dockerimage? )
- Preferred configurations
- Expose to the internet by ngrok for testing.

Additional
- Expose to the internet by own domain and the setup the reverse proxy with SSL.

**Comment by vrtmrz** [comment]
I think if I encourage someone to host and maintain a server. End to End encryption is needed to reduce the impacts of misconfigurations and/or vulnerabilities.

**Comment by arminus** [comment]
FYI - https://github.com/vrtmrz/obsidian-livesync/issues/17 has a working docker-compose.yml - just add another volume line with the local.ini as shown by @vrtmrz 
```
    volumes:
        - ./conf/couchdb/local.ini:/opt/couchdb/etc/local.ini
```

and put an .env file like this in the same dir as your docker-compose.yml:

```
COUCHDB_SERVER=<fully qualified server name>
COUCHDB_USER=<(to be created) couchdb user name>
COUCHDB_PW=<(to be created) couchdb password>
```

[Caddy Docker Proxy](https://github.com/lucaslorentz/caddy-docker-proxy) will get a LetsEncrypt cert on its own and you should be all set...

**Comment by arminus** [comment]
Not there yet for multiple devices, see https://github.com/vrtmrz/obsidian-livesync/issues/20

**Comment by arminus** [comment]
For me, this [docker-compose.yml](https://gist.github.com/arminus/8447f5a840a0b63dde84e55b09f834dc) together with the following CouchDB local.ini works now:
```
[chttpd]
require_valid_user = true

[chttpd_auth]
require_valid_user = true

[httpd]
WWW-Authenticate = Basic realm="couchdb"
enable_cors = true

[cors]
origins = app://obsidian.md, capacitor://localhost
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
```

Android probably has a 3rd origin, haven't tested that yet, will update as soon as I have

**Comment by vrtmrz** [comment]
Thank you for awsome information! It's very helpful!

I'm making the repo for docker-compose. 
After I tested to establish bland new server by the repo. 
It will be public.

And if you don't mind, may I add your name(arminus is ok?) into the docker-compose.yml?

**Comment by arminus** [comment]
> And if you don't mind, may I add your name(arminus is ok?) into the docker-compose.yml?

sure

**Comment by vrtmrz** [comment]
I wrote simple instructions and docker-compose.yml on [new repo](https://github.com/vrtmrz/self-hosted-livesync-server)
I really appreciate your investigations and giving me your docker-compose.yml

**Comment by vrtmrz** [comment]
it took 26 days but was finally done :)

**Comment by SutanuNandigrami** [comment]
Can we put it behind a forward authentication through for example authentik ?

**Comment by vrtmrz** [comment]
This is the first time I have heard of Authentik. This is fantastic. (I thought about adopting it personally).

However, currently, Self-hosted LiveSync cannot use this. It cannot open the UI for authentication during the replication connection. (However, if it were possible, it would make easier connection configuration, especially in the office or lab environment. It is very interesting).
From Authentik's functional point of view, if it could be opened, it would at least be available in Proxy Provider.

I regret to say this, but this is now a situation.

**Comment by princinv** [comment]
@vrtmrz dang, i was here hoping for authentik as well. 

if the device i am using has already been logged in to authentik and should not need interaction with authentication, is it still not able to be forwarded by authentik to the domain, hands free?
