### ISSUE TITLE
Plugin Sync without encryption

### ISSUE THREAD

**Issue by niieani** [vrtmrz/obsidian-livesync#81]
Hi @vrtmrz! Awesome work on your plugin. 
I don't encrypt e2e, because it seemingly adds complexity to the system, and the data is on a private server. 
I was wondering why is encryption mandatory for Plugin Sync to work? Would it be feasible to enable this functionality without encryption?

Thanks!

**Comment by vrtmrz** [comment]
@niieani 
It was just a safety valve to avoid exposing credentials stored in the setting of the plugin. 
But recently I noticed that I had written the credentials in my note. Maybe it was nonsense. 
I will unlock this and add the notification about the plug-in’s credentials.

**Comment by niieani** [comment]
Thanks @vrtmrz! Yeah, it would make sense in case you're not hosted on your own server. But if you are, and using HTTPS, I don't see any reason why encryption would have to be mandatory. 👍

**Comment by vrtmrz** [comment]
@niieani 
I think so. It was a good chance to organize what and how we have to solve. Thank you so much.
As your idea, E2EE became not required for synchronizing plugins from v0.11.5. (I forgot to add the release note. And maybe we have to drop databases once when switching e2ee)

**Comment by niieani** [comment]
Seems to work, thanks @vrtmrz!
