### ISSUE TITLE
Error while CHECK FILE STATUS - In 'e.cache(t)', 'e.cache' is undefined

### ISSUE THREAD

**Issue by MohamedBassem** [vrtmrz/obsidian-livesync#90]
First of all, thanks for the amazing plugin!

I'm currently facing a reproducable issue every time I open my iOS obsidian app. I get the following error messages whenever the sync kicks in:

![IMG_0FD51BAE7010-1](https://user-images.githubusercontent.com/2418637/178701257-60aa544f-248a-4549-a2e1-8857f666a986.jpeg)

(sorry for the screenshot, can't copy the log lines from the app). Enabling verbose logging doesn't seem to show extra log lines for this error. I also don't get them on the macos app, only the iOS one.

Any idea what's going on?

**Comment by MohamedBassem** [comment]
Hi, updating to v0.11.10 seems to have solved the issue. Thanks a lot for the quick response and fix! I'll be sending a small contribution on github sponsors to support the development of this awesome plugin! Thanks a lot again!

**Comment by vrtmrz** [comment]
I am very relieved to hear that! 
And, I appreciate your gratitude. I feel so honored!
