### ISSUE TITLE
Files get removed on conflict

### ISSUE THREAD

**Issue by moosapour-arash** [vrtmrz/obsidian-livesync#96]
Hello, i just completed my setup using CouchDB on a VPS and obsidian on PC and Android Phone. everything works fine except resolving conflicts.    
when a conflict occurs whether choosing Keep A , Keep B or Concat, the file gets removed by itself on the next synchronization from both devices.

Plugin version : 0.13.0

**Comment by vrtmrz** [comment]
Thank you for informing me! 
I wonder why I did not notice that, I made a mistake. 

The deletion mark is being made instead of deleting each conflicted revision. I will fix it tomorrow!

**Comment by vrtmrz** [comment]
@moosapour-arash 
Sorry for the trouble. It's fixed on v0.13.1.
Could you please try this version?
Perhaps you can roll that back by `Pick a file to show history` and `Back to this revision` if you lost some files.

**Comment by vrtmrz** [comment]
Sorry, v0.13.1 had been not enough. Could you please try v0.13.2 again?

**Comment by moosapour-arash** [comment]
wow, thank you for your quick response.   
I can confirm it works as expected in v0.13.2
So I'm closing this
