### ISSUE TITLE
About revisions and potential optimization 

### ISSUE THREAD

**Issue by Miigon** [vrtmrz/obsidian-livesync#99]
After reading this part of the documentation:
> Q: Database is growing, how can I shrink it up? A: each of the docs is saved with their old 100 revisions to detect and resolve confliction. Picture yourself that one device has been off the line for a while, and joined again. The device has to check his note and remote saved note. If exists in revision histories of remote notes even though the device's note is a little different from the latest one, it could be merged safely. Even if that is not in revision histories, we only have to check differences after the revision that both devices commonly have. This is like The git's conflict resolving method. So, We have to make the database again like an enlarged git repo if you want to solve the root of the problem.

I have a few questions:
* What is a "revision"? Is it a diff to the previous revision or a full copy of the file at that point in time?
* What would happen if the remote has already have over 100 new revisions while a device is offline? What would the device do to sync up? Does it do a full download of the file?

100 revisions seems a lot and not enough at the same time for someone like me who syncs frequently, and I am thinking maybe we can come up with some way to optimize it.

**Comment by vrtmrz** [comment]
Hi! Thank you for asking me!

> What is a "revision"? Is it a diff to the previous revision or a full copy of the file at that point in time?

LiveSync saves the doc as metadata and chunks. And as the result, only new chunks will be kept in the database. chunk will be reused if there are already exists.
So 100 revisions mean 100 metadata and some chunks (Usually it is as same as a number of lines in an editable file, if a non-editable file, it will be split by some sizes. It depends on configuration).
This is a draft, but we will get a sense of it. (Of course, I will enhance it)
https://github.com/vrtmrz/livesync-docs/blob/main/docs/What%20is%20the%20database.md

> What would happen if the remote has already have over 100 new revisions while a device is offline? What would the device do to sync up? Does it do a full download of the file?

The content will be transferred as some chunks, but only the diffs are.
(Of course, it may have some unused chunks included).
And intermediate revisions will be omitted automatically when synchronising.

**Comment by vrtmrz** [comment]
Close this issue once. Feel free to open it again if you have new something.
